### PR TITLE
Account for falsey test_variant in FeedsController

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Fix bug where feed is empty when test_variant is falsy.
## Related Tickets & Documents
n/a
## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
n/a
## Added tests?
- [x] no, because they aren't needed

## Added to documentation?
- [x] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?
n/a

### CODE REVIEW

**Comment by rhymes** [comment]
If think that if you remove the base case from the hash and do something like:

```ruby
if test_variant == "base" or test_variant.to_s == ""
  # run base
else
  # get stuff from the hash and run it
end
```

you should be fine :)

**Comment by lightalloy** [comment]
I agree with @rhymes suggestion. This also will make code more clear because `default_home_feed` is called with arguments, not like other methods. (but I would use `||` instead of `or`, though in this case the behavior would be the same)

**Comment by citizen428** [comment]
> if test_variant == "base" or test_variant.to_s == ""

@rhymes You snuck in a little Python here. Note that in Ruby `or` is quite different from `||`, as the former has super low precendence:

```ruby
a = false
b = true
c = a || b
c
#=> true
d = a or b
d
#=> false
```

That's because the `or` line will be parsed as `(d = a) or b` due to the low precedence.

**Comment by rhymes** [comment]
> > if test_variant == "base" or test_variant.to_s == ""
> 
> @rhymes You snuck in a little Python here. 

ahha yeah, I was talking to @lightalloy about this just yesterday. I was reading a Python article while I was reviewing this :D

**Comment by maestromac** [comment]
Thanks for the suggestion @thepracticaldev/oss ❤️  
I've applied it and it's still 100% test coverage.

**Pull request merged**
