### PR TITLE
Remove unused images

### LINKED ISSUE #5917: Remove unused images
**Describe the bug**

Not exactly a _bug_ perse, but some low-hanging fruit that we likely should prioritize: we have a bunch of images in `app/assets/images` that seem to be currently unused! We should remove these if we're not using them. For example, `jess.jpg` and `triple-unicorn.png`. This will make it much easier for our future selves to know which images are available to us to use, and will also reduce the size of assets that we're bundling or even including in our repo.

**To Reproduce**

N/A 

**Expected behavior**

I'd expect that every image in our `assets/images` directory is explicitly used in the app somewhere.

**Screenshots**

N/A 

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

Any PRs around this issue will need manual testing (I'm not entirely sure that we have test coverage that will catch changes here!)

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Optimization

## Description

@vaidehijoshi found some unused images in `app/assets/images` and thought it might be a good idea to clean this up a little. I basically just scripted this: iterate over all image assets (`find`) and if we can't find the `basename` anywhere in the codebase (`rg`), `git rm` the image. 

This *definitely* needs some sanity checking though, especially around all the special icon types (`android-icon*`, `apple-icon*`, `ms-icon*`).

## Related Tickets & Documents

Closes #5917 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

### CODE REVIEW

**Comment by citizen428** [comment]
@vaidehijoshi If I understand you correct, that's exactly what `basename` does:

```sh
$ basename app/assets/images/ben.jpg
ben.jpg
```

That said, I did a few files by hand before scripting it, and `ben.jpg` was amongst them. Looking at my shell history I apparent grepped for `ben.svg` by mistake. I'll restore this file now.

**Comment by vaidehijoshi** [comment]
@citizen428 ah, I don't think I realized that fact about basename! Good to know.

**Comment by rhymes** [comment]
@vaidehijoshi yeah, it could have been that. Usually one has to regenate snapshots with `yarn test -u`

**Comment by citizen428** [comment]
@rhymes I ran `yarn test -u` locally and this is the only  change it would make, so I think we're good:

```diff
diff --git a/app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap b/app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap
index 391e0522..49e62f5e 100644
--- a/app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap
+++ b/app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap
@@ -189,7 +189,7 @@ preact-render-spy (1 nodes)
       <a href="25/edit">
         <h2>hehhehe (expired)</h2>
       </a>
-      <span class="dashboard-listing-date">Jun 11</span>
+      <span class="dashboard-listing-date">Jun 12</span>
       <span class="dashboard-listing-category">
         <a href="/listings/cfp/">cfp</a>
       </span>
```

**Comment by vaidehijoshi** [comment]
thanks for this, @citizen428! deployed it for you :)

**Pull request merged**
