### PR TITLE
Replace current_user.id with session_current_user_id

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update
- [x] Optimization

## Description
This is a micro-optimization in some high leverage areas of the code. Fewer queries, fewer `current_user` objects getting loaded into memory.

### CODE REVIEW

**Comment by rhymes** [comment]
Cool!`efficient_current_user_id` is a weird name, mabe we should rename it `session_current_user_id` to describe its purpose 👀 

Another place we could probably use this is `PageViewsController#update` so we avoid loading the user each time just to create page views

**Comment by benhalpern** [comment]
> Another place we could probably use this is PageViewsController#update so we avoid loading the user each time just to create page views

I did this already, right? Unless I'm misinterpreting what you mean?

**Comment by rhymes** [comment]
@benhalpern do you think it'd make sense to use that method here?

https://github.com/thepracticaldev/dev.to/blob/c9a07faf6ae426d49d141a5b297e4fd2645b9bec/app/controllers/page_views_controller.rb#L17-L26

Something like:

```ruby
    if efficient_user_id
      page_view = PageView.where(article_id: params[:id], user_id: efficient_user_id).last
      # pageview is sometimes missing if failure on prior creation.
      page_view ||= PageView.create(user_id: efficient_user_id, article_id: params[:id])
      page_view.update_column(:time_tracked_in_seconds, page_view.time_tracked_in_seconds + 15)
    end
```

**Comment by benhalpern** [comment]
I merged before 24 hours because it got 2 approvals and I'm interested in observing any possibly notable effects over the weekend.

**Comment by mstruve** [comment]
Aaand I forgot about that guideline as well on the PR I just merged! 😬 Thanks for the reminder @benhalpern

**Pull request merged**
