### PR TITLE
Change background color of the selected setting

### PR DESCRIPTION
**Pull request by perlatsp**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
 Will make the background color of the selected setting tab to match the footer container and make it more visible
## Before
Before
## After
After

### CODE REVIEW

**Comment by maestromac** [comment]
Thanks for this PR @perlatsp ! Can you please kindly provide us a before and after screenshot?

**Comment by perlatsp** [comment]
@maestromac You are welcome.
Apologies for that added screenshots :)

**Comment by Link2Twenty** [comment]
It looks like you're not using the CSS variables but rather hard coding a new colour. 🙂

Going forward we'd like to use variables rather than changing the colours in styles.

Ben's post mentions how to use the new variables

```css
color: $medium-gray; 
color: var(--theme-secondary-color, $medium-gray);
```

https://dev.to/devteam/contributors-wanted-night-mode-themes-on-dev-i8n

**Comment by maestromac** [comment]
Thank you again for the PR but unfortunately Ben addressed this issue in https://github.com/thepracticaldev/dev.to/pull/2427 with the new color variables.

**Pull request closed without merging**
