### PR TITLE
Refactor: Tags.jsx (ES-LINT)

### PR DESCRIPTION
**Pull request by RakChamp25**
Refactor: Tags.jsx

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Related Tickets & Documents

https://github.com/thepracticaldev/dev.to/issues/2470

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @RakChamp25, you have a conflict, usually it happens because another PR was merged before this one

**Comment by RakChamp25** [comment]
> Hi @RakChamp25, you have a conflict, usually it happens because another PR was merged before this one

resolved @rhymes

**Comment by rhymes** [comment]
@RakChamp25 now there are failing tests :) please check the build results each time you push!

**Comment by rhymes** [comment]
@RakChamp25 I think there are some issues with the way you synchronized your branch with master.

How did you go about it? What commands did you use? Maybe I can help, because I've noticed you've unsynced branches in many PRs you've submit :)

**Comment by rhymes** [comment]
Hi @RakChamp25, I'm going to close this because there's clearly something wrong in your branch, see https://github.com/thepracticaldev/dev.to/pull/4378#event-2713799699, this also tags 49 people and the PR went from 1 file to 204.

Please reopen a separate PR after you've updated your local master branch and cut a new branch on which to apply changes.

If you don't know how to do it, let me know, I can help

**Pull request closed without merging**
