### PR TITLE
Bump Rails to 5.2.1

### PR DESCRIPTION
**Pull request by greysteil**
Rails 5.2 did a pretty good job of being backwards compatible, so this update may not be too bad. The other gems bumped to enable this are `administrate`, `devise`, `acts-as-taggable-on` and `ancestry`, all of which should be backwards compatible.

I've disabled the new encrypted cookies setting so that this update can be rolled back easily, although hopefully we'll catch any issues in testing.

Release notes: https://edgeguides.rubyonrails.org/5_2_release_notes.html

### CODE REVIEW

**Comment by greysteil** [comment]
I'm a little stumped by the remaining failures. I'll try to pick this up again soon, but if anyone else has any insights let me know!

**Comment by benhalpern** [comment]
Thanks a lot for the PR. Great to have you @greysteil! Those errors are, indeed, bizarre. Will look into this.

**Comment by maestromac** [comment]
While we didn't have an immediate plan to upgrade, we really appreciate your PR @greysteil and thank you for your amazing work on dependabot!

Superseded by https://github.com/thepracticaldev/dev.to/pull/1408

**Comment by greysteil** [comment]
No worries!

**Pull request closed without merging**
