### PR TITLE
[WIP] Migrate to system test

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Testing this on Travis CI 
## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by abraham** [comment]
As a side note, GitHub just introduced [draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/) that you can use instead of WIP.

**Comment by maestromac** [comment]
@abraham draft PR doesn't kick start CI for me :(

**Comment by abraham** [comment]
@maestromac Interesting. It looks like push runs are turned off for Travis, maybe those should be turned back on.

**Comment by maestromac** [comment]
Alright, I'm glad this is working but I'll wait for rails 5.2 upgrade first.

**Comment by rhymes** [comment]
@maestromac I think we'll have to wait a bit. I have the impression their going to release the new minor version around the time they release Rails 6

**Comment by maestromac** [comment]
@rhymes hmm alright, thanks for the heads-up. I don't think we are in dire need of system test.

**Pull request closed without merging**
