### PR TITLE
Remove debouncing from Tags component to fix glitching in autocompletion

### PR DESCRIPTION
**Pull request by mandaputtra**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
The search on tags are too fast sometimes it makes a glitch when typing uncommon tags.

## Related Tickets & Documents
#6478 

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [x] no, because I need help, I don't know should I add? I don't think so.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by mandaputtra** [comment]
There are lint-error here '/home/mptr8/Code/Projects/mandaputtra/dev.to/app/assets/javascripts/initializers/initializePodcastPlayback.js' I just bypass it. 

Tell me if I should to fix this. seems like it should be ignored.

Screenshot from 2020-03-12 17-02-27

**Comment by rhymes** [comment]
> I believe the issue we're seeing is not entirely related to the speed of the request but also on how the component inserts chars: as you can see when you type fast it does overwrite the content of the text field, which is probably where the issue actually lies.

For example, if you open your browser now and start typing. The browser shows you the autocompleted results, it doesn't override what youre typing. That's why I think the issue lies there

**Comment by mandaputtra** [comment]
I just tried again that its still remove some char if its uncommon tags, I think its lies on how the component insert char. I also agree that mostly we use short tag and if we are slow typer ~ it will remove the ',' too.

I'll look into how the component insert char, Thanks @rhymes .

**Comment by benhalpern** [comment]
I'd definitely favor more latency for results over the glitches, so let's try to come up with the best solution ASAP, maybe this one for the time being.

**Comment by mandaputtra** [comment]
Sorry for a long wait here is what I found yesterday. @benhalpern there is glitch that I don't know where does it happening. whether It using 800 / 500 / 250, the glitch only happens if you write uncommon tags. 

glitch

It's random. 

I'm still doesn't know why does the value changed. its already striped on [`handleInput()`](https://github.com/thepracticaldev/dev.to/blob/d0c1467ab0aabacb9cb7f50b2a7b216d4875a971/app/javascript/shared/components/tags.jsx#L240).

**Comment by rhymes** [comment]
Hi @mandaputtra, sorry for the delay in answering. I've tried at length to debug the issue but can't figure it out.

In the meantime, I verified it works, since this is a pretty important part of the website, could you please amend your PR to remove the usage of `debouncedAction` and just call `onInput={this.handleInput}` in the event handler?

Thank you, and again, sorry for the delay.

**Comment by mandaputtra** [comment]
@rhymes Change implemented. I remove the debouncedAction import too.

**Comment by rhymes** [comment]
Thanks a lot!!

**Pull request merged**
