### PR TITLE
Refactor tags components

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

[According to Code Climate](https://codeclimate.com/github/thepracticaldev/dev.to/app/javascript/article-form/elements/tags.jsx/source#issue-8ca60d3b1e2b296b92ea9664b66ed0eb) these two React components are nearly identical. There are just a few pieces of unique functionality for the listing version of the tags component.

I merged the two components into one with just a few less than ideal conditionals based on a Boolean passed in as a property.

The only downside to this, afaik, is that you now need to pass in a couple of extra properties when rendering this shared component.

I did modify the tests a little bit (and update screenshots), so some QA there would be appreciated.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Listing view after the change:
Screen Shot 2019-09-01 at 6 51 01 PM

Editor after the change:
Screen Shot 2019-09-01 at 6 51 11 PM

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

transformers combining into one

### CODE REVIEW

**Comment by jacobherrington** [comment]
This appears to fix 38 or so Code Climate complaints -- though I'd like some opinions on this approach of using shared components rather than just pandering to CC. 🤓

**Comment by rhymes** [comment]
Well done!! FYI: I think the failing tests are due to the need to update the snapshots now that you changed the HTML a bit. If you run `yarn test -u` to update the snapshots and then check the diff you should be set!

**Comment by jacobherrington** [comment]
@rhymes Thanks! I forgot that I needed to update the screenshots again. 🤠

**Comment by jacobherrington** [comment]
@benhalpern Does anything need to be done to get this PR reviewed? CodeClimate is complaining, but this actually is a net gain concerning CC issues. #3933 is in the same state, iirc.

**Pull request merged**
