### PR TITLE
Remove temporary site config script and unused env

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

This is a follow up to #5400:

- removes `DEFAULT_SITE_EMAIL` which is unused and its usage was removed in #5399
- removes the temporary script now that the variables have been migrated to site configuration

### CODE REVIEW

**Comment by rhymes** [comment]
I got confirmation the script has been ran, we can go ahead.

I agree with the rest, we'll end up building some scaffolding tools for generalization I guess

**Comment by mstruve** [comment]
Made an issue for it! https://github.com/thepracticaldev/dev.to/issues/5500

**Comment by rhymes** [comment]
Great catch @mstruve, this came back from the window in a PR and we didn't notice it :( 
How hasn't it broken production?

**Comment by rhymes** [comment]
I had to force push because I had to rebase to incorporate that change

**Pull request merged**
