### PR TITLE
connect message spacing fix

### LINKED ISSUE #1256: Certain code blocks in chat affect the chat details' width
This code block seems to cause the channel details sidebar width to shrink a bit.
```
type Test = { k?: string; };
type Strict<T> = T extends infer S | undefined ? Exclude<S, undefined> : never;
type Strictify<T> = { [K in keyof T]: Strict<T[K]> };
type StrictTest = Strict<Test>
```

Example:

This can happen in group channels and DMs. Reproduced locally in Chrome and Firefox.

### LINKED ISSUE #1257: Long messages are not text-wrapped properly with Firefox
A long message like `klajsflksdjfklsjfkldsfjsd;lkfjdsjf;lksadjfkl;dsfkldskfjdskl;fjsdkl;fjdasl;fjdkls;fkldsajklajsflksdjfklsjfkldsfjsd;lkfjdsjf;lksadjfkl;dsfjklajsflksdjfklsjfkldsfjsd;lkfjdsjf;lksadjfkl;dsfkldskfjdskl;fjsdkl;fjdasl;fjdkls;fkldsajklajsflksdjfklsjfkldsfjsd;lkfjdsjf;lksadjfkl;dsfj` (274 characters) shrinks both the left and right sidebars.

This seems to only affect Firefox. I tested this on macOS; not sure if it affects Windows or Linux.

screen shot 2018-12-04 at 3 48 29 pm

### PR DESCRIPTION
**Pull request by mariocsee**
## What type of PR is this? 

- [x] Bug Fix

## Description
It seems like content in `<code>` and `<pre>` took precedence over other HTML elements in Connect. Rather than using the previous approach and forcing breaks in the line, I have added `width` assertions in CSS to prevent the channel list on the left and the channel content on the right from being squished. The code blocks and messages are capped and adjust to the opening and closing of content on the right. 

One notable change I have made is that in mobile, is that when right content is opened, rather than pushing all others to the left, I decided to overlay it on top of the chat preventing a horizontal scroll from appearing on mobile pages. 

## Related Tickets & Documents
resolves #1256 and resolves #1257 

### Firefox word-break:
screen shot 2019-01-08 at 17 18 29

## Added to documentation?

- [x] no documentation needed

## What gif best describes this PR or how it makes you feel?
interstella 5555

### CODE REVIEW

**Comment by benhalpern** [comment]
Hmmm I think `<pre>` blocks should have horizontal scrolling as opposed to line breaks. I think this is the expected behavior with code.

**Comment by mariocsee** [comment]
Gotcha, I'll adjust styling so that overflow horizontal scrolling happens so that the channel details and sidebar width isn't affected. 

@benhalpern What are your thoughts on `break-word` to `break-all` so that strings on Firefox in #1257 are chopped (but then it breaks any word that isn't really long)? Should I instead adjust for overflow and allow horizontal scrolling?

**Comment by benhalpern** [comment]
For normal text we should not have scrolling and we should prefer to break words. I'm not totally sure about #1257 but don't see it as a critical issue to fix. Long words should be broken. I'm not sure about the details on how to do that exactly.

Horizontal scrolling should only apply to `<pre>` tags, just as it does in articles/comments on the site,

e.g.

https://dev.to/deciduously/comment/7bo3

**Comment by mariocsee** [comment]
Somehow the way Firefox handles `break-word` doesn't actually chop particular words into shorter segments, so I can't address #1257 without accepting the repercussions of using `break-all`. 

After a lot of tinkering around, my hunch is that the problem of the `<pre>` code blocks  in chat vs elsewhere is that its width isn't hard capped at a maximum, which explains why `overflow-x` doesn't seem like its working in chat but works in comments and articles. The length/size of its content in both `<pre>` and `<code>` always takes precedence over the determined `max-width`.

**Pull request merged**
