### PR TITLE
Add views count for authenticated users articles [#4250]

### PR DESCRIPTION
**Pull request by matisnape**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [x] Documentation Update

## Description
I added page_views_count to me/articles - published, unpublished, all

## Related Tickets & Documents
Issue: #4250 

## Added to documentation?

- [x] docs.dev.to
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

fabulous

### CODE REVIEW

**Comment by benhalpern** [comment]
@matisnape this looks good to me. Let's merge once the version is bumped, as @rhymes mentioned.

Thanks a lot for the PR!

Note to self. We had committed to always making a blog post about changes to the API, so we'll need to organize to do that once this is merged. It should not hold things up.

**Comment by matisnape** [comment]
@benhalpern BTW, I didn't find info in the docs about bumping API version being required. Is it there? Or maybe it would be worth to add it?

**Comment by rhymes** [comment]
@matisnape yeah, it would be worth adding it, but in a separate PR! There's a page that contains info about API docs: https://docs.dev.to/contributing_api/ but we should probably add a notice also in the general contributing guide

Would you like to make this change?

**Comment by matisnape** [comment]
@rhymes will do! :)

**Comment by rhymes** [comment]
@matisnape good question, I've always thought it as the version of both, in theory the API docs and the API should go hand in hand, even though right now the docs are way behind the actual API functionality (they've been added only recently).

**Comment by matisnape** [comment]
@rhymes Maybe I could contribute here? With updating docs? What areas would be most needed?

**Comment by rhymes** [comment]
@matisnape sure! that would be lovely, do you have experience with OpenAPI?

I just opened a PR to update the info about errors in the docs - https://github.com/thepracticaldev/dev.to/pull/4459 - I think after that is merged we can start!

> What areas would be most needed?

Basically everything :D If you check https://docs.dev.to/api/ you'll notice the only parts of the API that are documented are `/articles` and `/webhooks` and their endpoints.

If you check the routes:

https://github.com/thepracticaldev/dev.to/blob/ee8ae66e4708d4025756d4d1860d1dfa624d2638/config/routes.rb#L81-L123

and the API controllers folder - https://github.com/thepracticaldev/dev.to/tree/master/app/controllers/api/v0 - you'll notice there's much more to be documented :)

**Comment by matisnape** [comment]
@rhymes I'm not familiar with OpenAPI when it comes to writing, but that's why there's a documentation on how to write it, right? :) I'll give it a try after you're done and we'll see how it goes :)

**Comment by rhymes** [comment]
@matisnape good, great!

**Comment by rhymes** [comment]
@matisnape https://github.com/thepracticaldev/dev.to/issues/4474 :)

**Pull request merged**
