### PR TITLE
[UI] Fix scrollbar overlapse bug

### LINKED ISSUE #1332: Header following a code block - scrollbar overlapse
**Describe the bug**
Making a header next to a code block with a horizontal scrollbar makes an area overlapping with the scrollbar and the header.

Tested under Firefox only.

image
image

This makes us select the text instead of / while moving the scrollbar, which is annoying.

**To Reproduce**

Create a blog post with the following content:
```
-``` Ignore the prefixed -, this is for the github markdown. --- Continuing the line to get a scrollbar, you can ignore this content.
-```
# This is a header. It should overlap with the scrollbar.
```
Preview or post it, and try moving the horizontal scrollbar by selecting an area above the header text.

**Expected behavior**
The scrollbar moves without selecting the text.

**Screenshots**

image
image

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Version: 64.0

**Additional context**

This can be fixed with the following CSS:
```
div.highlight + h1 {
    margin-top: 50px;
}
```
Where h1 can be h1-h6.

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Removed two CSS line to fix a UI bug. Will need another pair of eyes to verify I didn't break anything somewhere else though.
## Related Tickets & Documents
Resolves #1332 
## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
before

After
screen shot 2019-01-14 at 4 24 10 pm

## Added to documentation?
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by Link2Twenty** [comment]
While we're here, how do we feel about adding a link icon after headers?

Maybe something like this?

http://jsfiddle.net/link2twenty/u972rLx0/

**Comment by maestromac** [comment]
I knew I broke something.

**Comment by Zhao-Andy** [comment]
Also @Link2Twenty I think it makes sense for this PR to only fix the bug. Like the use of an emoji for the icon though.

Would you like to open a feature request issue for the icon? I think it makes sense, too; there are some implementation details we'll want to discuss that probably should be left in a separate issue.

**Comment by benhalpern** [comment]
@maestromac @Zhao-Andy @Link2Twenty I think this can be fixed most simply by making the `z-index` of the code area higher than the `z-index` of the header, eh?

With the link thing: I think the left margin is still my favorite place for it. And possibly only on hover?

We'd previously had an implementation of this idea which shipped the image in the actual HTML which didn't seem right. I think ideally this would maybe be something included in the CSS `::before` or something along those lines. Does that make sense?

**Comment by maestromac** [comment]
@benhalpern I've toyed around with adjusting z-index in [this commit](https://github.com/thepracticaldev/dev.to/pull/1540/commits/4e7b6d2a7e456deca4813ee40e862bc1518d2853) but it doesn't seem to work. Maybe I did it wrong? This error is reproducible on Firefox 64 on MacOS (just make sure your scrollbar are always displayed

**Comment by Link2Twenty** [comment]
@Zhao-Andy @benhalpern I'll raise a feature request in the morning, for the anchor links, but it sounds like Ben is hoping for something like this.

http://jsfiddle.net/link2twenty/2z7rqu1k/

**Pull request merged**
