### PR TITLE
Created the <ButtonGroup /> Preact Component

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Converted the design system button group to a Preact component.

Here is the [ButtonGroup in Storybook](https://devto-storybook.now.sh/?path=/story/components-buttongroup--default)

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

An example usage of the <ButtonGroup /> component.

image

## Added tests?

- [x] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Elf in the movie Elf pressing as many elevator buttons as possible at the same time

### CODE REVIEW

**Comment by nickytonline** [comment]
Note this needs to be rebased off master still since it's currently based off the work of #6987.

**Comment by nickytonline** [comment]
> Not like we need to take care of it in the component itself (it should rather be mentioned in the documentation of the components, which I'll take care of) BUT after looking at your screenshot I wanna make small clarification: this is meant to be used only with one type of a button at a time :P so you shouldn't really mix `danger + primary + ...` types. instead you should have `primary + primary + primary ...` or `danger + danger + danger + ...` or... you get the idea..
> 
> otherwise, sweet!

I updated my tests and Storybook example to reflect this as well as the image in the PR description.

**Comment by benhalpern** [comment]
😍

**Comment by rhymes** [comment]
Nice look!

ps. I think this branch contains #6987

**Comment by nickytonline** [comment]
> Nice look!
> 
> ps. I think this branch contains #6987

See https://github.com/thepracticaldev/dev.to/pull/7048#issuecomment-607989879

**Comment by nickytonline** [comment]
@rhymes, this has been rebased off of master now. Good for a review now.

**Pull request merged**
