### PR TITLE
Remove redundant JS dependencies

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
- [x] Misc.
## Description
We rely mostly on [@rails/webpacker](https://www.npmjs.com/package/@rails/webpacker) and it comes with most basic css and transpiling necessities. Removing these redundencies will also help refine our use of dependabot.
## Added to documentation?
  - [x] no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
@maestromac, these dependencies are used in Storybook, https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/.storybook/webpack.config.js#L3

**Comment by nickytonline** [comment]
Maybe the sass one can be removed. You'd have to try removing the loaders from the storybook webpack config to see if it still builds.

**Comment by maestromac** [comment]
@nickytonline I was concerned about that. I ran both `yarn storybook` & `yarn build-storybook` and they both seems to work fine.

**Comment by nickytonline** [comment]
Cool. If it's all good then remove away! 😉

**Pull request merged**
