### PR TITLE
Delete search.xml

### PR DESCRIPTION
**Pull request by tcgumus**
Couldn't find any use of this page.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description
Couldn't find any use of this page.
## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [x] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by citizen428** [comment]
This file is for [OpenSearch](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md). It doesn't need to be referenced anywhere else in the code base.

**Comment by rhymes** [comment]
We should also generalize it as it harcoded DEV's strings, in a similar way in which we moved the sitemap from a hardcoded file to a controller in https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/sitemaps_controller.rb

Let us know how you'd want to proceed and we can assist

**Comment by tcgumus** [comment]
I would like to help. I will check the sitemap  example and try to proceed. Thank you very much

**Comment by rhymes** [comment]
@tcgumus thank you! If you plan on working on this PR don't forget to change the title/rewrite the description or you can always open a new one. Both are fine options :)

**Comment by mstruve** [comment]
Hi @tcgumus! 

Thank you so much for the PR and for taking the leap to contributing! We are so happy you are here 😄 

With that said, we are in the process of going through and cleaning up some of our PR history to help us better prioritize what we need to be focusing on. Since this PR has not been active for a while I am going to close it for now. If you would still like to get this merged please feel free to update it and open when you believe it is ready to be merged. We would be more than happy to help you push this through if you would like! 

Thank you so much for contributing! Ping us anytime if you have questions!

**Pull request closed without merging**
