### PR TITLE
Add community_member_description, tagline and mascot_image_url to SiteConfig. Enable Cloudinary for primary_sticker_image

### PR DESCRIPTION
**Pull request by JibranKalia**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Adding `community_member_description`, `tagline` and `mascot_image_url` to SiteConfig. Also enabling cloudinary for `primary_sticker_url` which was created by #6746. 

The only thing missing in order to complete issue https://github.com/thepracticaldev/dev.to/issues/5477 is implementing `secondary_sticker_image_url`. However, that purple logo is implemented in jsx. I am not really sure how to push SiteConfig details into javascript.

## Related Tickets & Documents
#5477

### community_member_description

Screen Shot 2020-03-23 at 8 18 09 AM

Screen Shot 2020-03-23 at 8 35 07 AM

### tagline

Screen Shot 2020-03-23 at 8 31 00 AM

Screen Shot 2020-03-23 at 8 31 19 AM

### mascot_image_url

Screen Shot 2020-03-23 at 9 06 11 AM

Screen Shot 2020-03-23 at 9 06 03 AM

## Added tests?

- [X] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

### CODE REVIEW

**Comment by JibranKalia** [comment]
Thank You @rhymes. For some reason I don't see your comment.

**Comment by rhymes** [comment]
ahahaha I forgot to save it :-( 

I was saying that in https://github.com/thepracticaldev/dev.to/pull/7056/files#diff-beebbcf083b2d6c99f787d52d3f90a74R8 we might want to put the alternative description as a default, so that other communities can change it too. "Sloan" makes sense only if "Sloan" is the content of the image. you can use it too in the other places where you call `SiteConfig.mascot_image_url`

**Comment by JibranKalia** [comment]
@rhymes  Good point. Updated.

**Comment by JibranKalia** [comment]
Thank You @vaidehijoshi. Fixed test. Do you prefer that I squash now or do y'all use the `Squash Merge` option by github?

**Comment by vaidehijoshi** [comment]
@JibranKalia thanks for that! We use the "squash and merge" option by default :)

**Pull request merged**
