### PR TITLE
Use ActiveSupport::Cache::RedisCacheStore As RedisRailsCache

### PR DESCRIPTION
**Pull request by mstruve**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Soooooo I took the roundabout way to get here but what matters is that I got here 😂 
Let's not try to reinvent the wheel and instead simply use the beautiful cache store that Rails has already given us ❤️️

## Related Issue
Issues #4670 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

gif saying its too easy

### CODE REVIEW

**Comment by sabunt** [comment]
I suggest using gem 'hiredis' for more power and speed

**Comment by rhymes** [comment]
@sabunt good suggestion. I see that the official [RedisCacheStore](https://api.rubyonrails.org/classes/ActiveSupport/Cache/RedisCacheStore.html) supports `hiredis`!

**Comment by mstruve** [comment]
In terms of using hiredis, I choose not to use it bc it adds another layer of complexity and it will only really benefit us if we are pushing much larger requests

> For simple line or bulk replies, the throughput improvement is insignificant, while the larger multi bulk responses will have a noticeable higher throughput.

I would rather hold off on adding it until we determine it would really add a performance benefit. 

@rhymes, I will get the fallbacks and automatic expirations hooked up! 👍

**Comment by rhymes** [comment]
@mstruve I agree, we shouldn't prematurely optimize, we know it's a cardinal sin in programming ;-)

**Comment by mstruve** [comment]
[deploy/netlify failure is unrelated]( https://www.netlifystatus.com/incidents/wp74mq2b01jf) so this should be ready to go

**Pull request merged**
