### PR TITLE
Feature/reading list loadmore button

### PR DESCRIPTION
**Pull request by bellsenawat**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
A load more button will show when reading list is array length more than 64 and it will hide when no reading list to load from API. 

## Related Tickets & Documents
#3122 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
dev_to_ss

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by benhalpern** [comment]
Thanks for the PR, could you sign the CLA before this can be merged? Thanks!

**Comment by rhymes** [comment]
@benhalpern I wonder if we could align on the UI between the history and the reading list before merging this.

**Reading List:**

"Load more reading list" and 

Screenshot 2019-06-19 at 9 06 15 AM

**History:**

Load more and a slightly different UI

**Comment by benhalpern** [comment]
@rhymes I agree. We should look to get these interfaces unified.

**Comment by bellsenawat** [comment]
@rhymes @benhalpern I don't know where the history page and I agree to make it consistent :) by the way the button style came from listing page :)

**Pull request merged**
