### PR TITLE
Add number_with_delimiter to post count on tags page

### PR DESCRIPTION
**Pull request by atsmith813**
## What type of PR is this? (check all applicable)
- [x] Optimization

## Description
Format large numbers with commas on the tags page https://dev.to/tags

## QA Instructions, Screenshots, Recordings
**Before**
Screen Shot 2020-07-09 at 1 03 02 PM

**After**
Screen Shot 2020-07-09 at 1 02 36 PM

## Added tests?
- [x] no, because they aren't needed

## Added to documentation?
- [x] no documentation needed

no_biggy_gif

### CODE REVIEW

**Comment by atsmith813** [comment]
@Zhao-Andy I believe so because it defaults to [defaults to current locale](https://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_with_delimiter). Do you know if that is sufficient? Or should we be passing an the option to override it instead?

**Comment by Zhao-Andy** [comment]
Ahh yeah I think that's fine then! Missed that part in the description.

**Comment by rhymes** [comment]
Awesome @atsmith813 It's a great idea.

Though as it's done server side it's going to use the server's locale which means that in my case, even though I know we're taking about thousands, I'm instinctively `23,861 post published` as "23 posts point 861" as in in my locale that would be written as `23.861` :-D 

If we want to do it according to the browser locale we should use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

**Comment by atsmith813** [comment]
Ahhhh I see - makes sense. Thanks, @rhymes! TIL. I'll revert this PR and we can circle back in the future and use JS instead.

**Pull request merged**
