### PR TITLE
[WIP] Publishing from RSS documentation

### PR DESCRIPTION
**Pull request by stephaniekyyip**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [X] Documentation Update

## Description
This PR is to improve documentation for the publishing from RSS feature. This includes documenting what tags are used in creating drafts from the user's RSS feeds. For reference, I looked into the code behind Feedjira to understand how exactly the feed parsing worked. 

This WIP is to make sure that I'm creating the new page and route in the right place. 

## Related Tickets & Documents
#321 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

### CODE REVIEW

**Comment by stephaniekyyip** [comment]
Sorry for all the commits! I didn't merge things correctly before, so I'm trying to fix everything now. 😅

**Comment by rhymes** [comment]
@stephaniekyyip I feel like it's probably easier if you reapply your commits about the publishing guide on top of the current master. It sounds like a lot less work than fixing the conflicts.

Maybe you can create a new branch from the current master, use `git cherry-pick COMMIT_HASH` to re-apply https://github.com/thepracticaldev/dev.to/pull/1037/commits/e5463d54a101e4ba70ad287e446b877e0f8dbdf4 and https://github.com/thepracticaldev/dev.to/pull/1037/commits/d81a20128a4ec19f05f935510984a14fe93944f7 and start from there.

This would mean closing this PR and opening another one.

Another possibility is to use rebase I guess

**Comment by stephaniekyyip** [comment]
Finally getting back to this. Thanks @rhymes. I'll close this PR and reopen it once I fix everything.

**Comment by maestromac** [comment]
Hey @stephaniekyyip ! just want to point out that somebody else also submitted a PR (https://github.com/thepracticaldev/dev.to/pull/1151). You are encouraged to review that PR since you attempted to add this documentation.

**Pull request closed without merging**
