### PR TITLE
console message ascii art & message to repo

### PR DESCRIPTION
**Pull request by mariocsee**
## What type of PR is this? (check all applicable)
- [x] Feature

## Description
Adds the DEV ascii art from `bin/setup` without the back-ticks to console with a short message that tells the visitor that we're open source and shows a link to this GitHub repo. 

Current message right now is: "Hey there! Interested in the code behind dev.to? Well you're in luck - we're open source! Come say hi, tell us about your problems, or even lend a hand in our repo - https://github.com/thepracticaldev/dev.to/". Suggestions/changes are welcome. 😀 

I encountered some console messages on other websites with a link to their career page. I found it cute and might lead some new people into the repo. 

## Related Tickets & Documents
N/A 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Screen Shot 2019-04-11 at 17 23 36

## Added to documentation?

- [x] no documentation needed

## What gif best describes this PR or how it makes you feel?

oh hi mark

### CODE REVIEW

**Comment by maestromac** [comment]
I like it. This is fun and fine by me. I want to point out that ASCII art get Squished when the screen is narrow.

**Comment by mariocsee** [comment]
@maestromac Yeah the ASCII art gets squished at a certain size. I can probably lessen the whitespace on both sizes, but I don't wanna spend time making the ascii art smaller lol.

**Comment by mariocsee** [comment]
Narrower now!
Screen Shot 2019-04-16 at 16 10 00

**Comment by Link2Twenty** [comment]
Did you know you can add colour to text in the console, so if you wanted to mimic the rainbow 🌈 dev logo it would be possible.

Just a thought 🙂

**Comment by mariocsee** [comment]
@Link2Twenty I didn't know that. Great idea! Would be a nice contribution if someone in the community wants to get creative with it. 😃

**Pull request merged**
