### PR TITLE
Add markdown version for DEV badge link

### PR DESCRIPTION
**Pull request by bravemaster619**
See the post: https://dev.to/bravemaster619/add-a-markdown-version-for-dev-badge-link-1bep

Nathan Kallman and others suggested me to create a PR

### CODE REVIEW

**Comment by NuruddeenSalis** [comment]
[]()
<a href="https://dev.to/theligh3"> Nuruddeen Salis's DEV Profile </a>

**Comment by NuruddeenSalis** [comment]
**...for Dev Badge Link:**

@bravemaster619 create a PR


[]()[Nuruddeen Salis's DEV Profile](https://dev.to/theligh3)

**Review by NuruddeenSalis — APPROVED** [review]
Hello World

**Comment by siddhantvirus** [comment]
Is their anyway to resize the svg using this markdown syntax ?

**Comment by rhymes** [comment]
@siddhantvirus nope, but markdown supports HTML so you can use the `` tag and specify sizes in it

**Pull request merged**
