### PR TITLE
App JS Content: Refactor of display and removal of unused block

### PR DESCRIPTION
**Pull request by fredhase**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Removed a block that was never reached (same if as another block), removed 'ifs' and added an object literal to select which content to render.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by citizen428** [comment]
@fredhase Thanks for your contribution! However, it seems like you incorrectly classified this PR as "Feature" instead of "Refactor", can you please update the description.

Also there seem to be some merge conflicts, would it be possible to fix them? Thank you!

**Comment by fredhase** [comment]
Sure. I already updated the description. My mistake. And I need to correct somethings with my git. I realized that I've been using branches in the wrong way. So, is it fine if I resend the PRs that I've made? They're basically refactoring. I'm really sorry about the mistakes.

**Comment by citizen428** [comment]
No need to be sorry @fredhase, we all make mistakes. If you think it's easier for you, please close your current PRs (and leave a comment as to why you're closing them) and open new ones.

**Comment by nickytonline** [comment]
As mentioned @fredhase in another PR, if you need a hand with git/branches, don't hesitate if you need a hand. My DM's are open on DEV.

**Comment by fredhase** [comment]
@nickytonline I really appreciate and if I need help, I will send a message :)
For now, I think I know the mistake that I've made
@citizen428 I'm going to close them now and specify the reason, and soon as I can i will resend them as new PRs. Thanks for understanding, both of you :)

**Comment by fredhase** [comment]
Closing this PR for some branche mistakes that caused conflict

**Pull request closed without merging**
