### PR TITLE
Add share to hacker news link

### PR DESCRIPTION
**Pull request by aligoren**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Hi. I didn't see share link for the hacker news. I added it. I tried this change on my local environment.

Links will be like that: 

[How I Structure My Flask Apps](https://news.ycombinator.com/submitlink?u=https://dev.to/aligoren/how-i-structure-my-flask-apps-3eh8&t=How%20I%20Structure%20My%20Flask%20Apps)

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by aligoren** [comment]
> [CLA assistant check](https://cla-assistant.io/thepracticaldev/dev.to?pullRequest=3297)
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/thepracticaldev/dev.to?pullRequest=3297) before we can accept your contribution.
> **Ali** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/thepracticaldev/dev.to?pullRequest=3297) it.

I signed :cry:

**Comment by maestromac** [comment]
Thanks for this PR @aligoren !

Do you see that [the commit](https://github.com/thepracticaldev/dev.to/pull/3297/commits) does not have your profile picture? It's because the email you used to sign that commit does not match the email you have on GitHub. You can either
1. Change your machine's git's (either local or global) email config to the one you use on GitHub, then amend the commit.
2. Or you can add the email you've used to commit the work to Github. I have never tried this but it should work in theory.

**Comment by aligoren** [comment]
> Thanks for this PR @aligoren !
> 
> Do you see that [the commit](https://github.com/thepracticaldev/dev.to/pull/3297/commits) does not have your profile picture? It's because the email you used to sign that commit does not match the email you have on GitHub. You can either
> 
>     1. Change your machine's git's (either local or global) email config to the one you use on GitHub, then amend the commit.
> 
>     2. Or you can add the email you've used to commit the work to Github. I have never tried this but it should work in theory.

Actually, I used my mail to commit. Interesting. Should I re-commit?

**Comment by aligoren** [comment]
I signed. Hmm. I think this happened because of my work computer and my personal computer have different configs.

Should I go back to work :P

**Comment by aligoren** [comment]
> Sorry I'm just getting back to this @aligoren . Do you mind only signing the commit with your `@yandex.com` email?
> you can do the following
> 
> 1. Since you only need the first commit.`git reset --hard a6716cd6e5cb33eda8a9dee2cfb2a951bded7f2d`
> 2. `git commit --amend --author="aligoren <goren.ali@yandex.com>"`
> 3. Force push the commit

I did. I think I should close this PR and re-open a new one. I don't know why is this happens. I can't also sign cla again. Because I already did.

**Comment by maestromac** [comment]
It's alright @aligoren . Please  copy/paste `I have read and agree to the CLA` as a comment in this issue.

**Comment by aligoren** [comment]
I have read and agree to the CLA

**Pull request merged**
