### PR TITLE
updating Prerequisite link under table of content in README.

### LINKED ISSUE #285: Prerequisite in table of contents of README file doesn't navigate to Pre-requisites section in README.
User Story / Description : Prerequisite vs Pre-requisites causing this. Table of content has Prerequisite whereas description has Pre-requisites because of which hyperlink doesn't work

Definition of Done : Clicking on  Prerequisite should work,

Current Behavior : Clicking on  Prerequisite doesn't work.
Expected Behavior: Clicking on  Prerequisite should take one to  Prerequisite section in the README.

### PR DESCRIPTION
**Pull request by Awdesh**
## What type of PR is this? (check all applicable)
- [ ] Refactor
- [ ] Feature
- [x] Bug Fix

## Description
Updating link under Prerequisite section in table of content section inside the README file. fixes #285 
## Added to documentation?
  - [ ] docs.dev.to
  - [ ] readme
  - [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
Easy

### CODE REVIEW

**Comment by benhalpern** [comment]
Hmmmm, since prerequisite is one word, not a hyphenated word, I think the correct outcome would be to change the header to Prerequisites and leave the link as-is.

**Comment by Awdesh** [comment]
Ok. Currently header is 'prerequisite' (singular). I think I should change header to prerequisite which will keep the link unchanged.

**Comment by Awdesh** [comment]
@CLAassistant @benhalpern would you be able to remove 'Awdesh Sharma' user from from CLA. I don't have access to email address that belong to that user.

**Comment by maestromac** [comment]
Hello @Awdesh , I see that `all committers have signed the CLA`. Do you still require actions from us or is it resolved?

also, this is a nit-pick: Could you capitalize the `p` in `prerequisites` on line 128? if not I can commit directly to this pr.

**Comment by Awdesh** [comment]
@maestromac I have made the suggested changes. I think it should be resolved once all the checks passes.

**Pull request merged**
