### PR TITLE
Conditionally install foreman during setup

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

We should avoid install foreman during `bin/setup` if it is already
installed.

I'm not sure if we should dictate a version here - anyone have thoughts?

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by benhalpern** [comment]
@jacobherrington @rhymes yeah could we check what version of foreman exists and include that in the logic here?

**Comment by jacobherrington** [comment]
@benhalpern At what version do we force an update? It's worth noting that [foreman seems really stable](https://rubygems.org/gems/foreman/versions).

**Comment by rhymes** [comment]
@jacobherrington i think we can just simply check the latest available, if we ever break foreman in development we'll know soon enough as we all use it

**Comment by jacobherrington** [comment]
@rhymes @benhalpern Updated!

**Pull request merged**
