### PR TITLE
Refactor app/javascript/article-form/elements/bodyPreview.jsx

### PR DESCRIPTION
**Pull request by RajaSK05**
Refactor to component model

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by rhymes** [comment]
@RajaSK05 don't forget to sign the CLA :)

**Comment by RajaSK05** [comment]
> @RajaSK05 don't forget to sign the CLA :)

Just now done 😄

**Comment by rhymes** [comment]
Hi @RajaSK05, can I ask why you force pushed? I have to redo the review now eheh 👀

**Comment by RajaSK05** [comment]
> Hi @RajaSK05, can I ask why you force pushed after it was approved? I have to redo the review now eheh 👀

Mistakenly I've commited the changes under another mail id of me which is not integrated with github. So, I changed my mail id, made the commit and when pushing it, it asked for force push 😬

**Pull request merged**
