### PR TITLE
Onboarding : fixed bug that prevented toggle by clicking on label

### PR DESCRIPTION
**Pull request by theaupoulat**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x ] Bug Fix
- [ ] Documentation Update

## Description

emailing related <input>  were missing an id to refer to their  <label> parent.

## Related Tickets & Documents

Issue #3720

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

first_time

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @theaupoulat, thanks for this PR!

To fix the failing JavaScript test you need to regenerate the HTML snapshot by running `yarn test -u` locally and then commit the updated snapshot.

It should be fine after that.

**Comment by benhalpern** [comment]
Thanks for the PR @theaupoulat, onboarding can be a bit of a black box for these kinds of bugs because people just don't see it repeatedly like other bugs and features. So very great to have this PR. As @rhymes mentioned, you'll need to run test snapshot update (or manually update the snapshot) and then it will be good to go.

**Comment by theaupoulat** [comment]
Ok ! Will do today.

**Comment by theaupoulat** [comment]
Thanks !

**Comment by theaupoulat** [comment]
@rhymes @benhalpern was it done correctly ? codeclimate still fails (only recommending a refactor)

**Comment by rhymes** [comment]
@theaupoulat it's perfectly fine, thank you!

**Pull request merged**
