### PR TITLE
[WIP] Create SortableCount model for better rankable data caches

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

This PR adds a table called `sortable_counts` which is a model designed to hold a "countable" thing.

This starts with creating sortable counts for tags. These can be extended via `has_many` relationship to store lots of rankable data for organization and performance.

This is related to #4825, #4939, etc. I think it's a pretty scalable solution for some of what we might want to do along these lines. I'm not totally sure about all this though.

This doesn't really make use of the "sortable" part, but is the first screen which makes use of this sort of data:

Screen Shot 2019-12-30 at 7 21 44 PM

### CODE REVIEW

**Comment by mstruve** [comment]
One thing that sticks out to me is that we are trying to store a lot of constantly changing count data which is hard bc it leads to having to recalculate it a lot. It also stands out that this is data we might want to sort and do further analysis with. I honestly think data like tags counts for articles, user reaction counts, etc are going to be a piece of cake to get once I have overhauled our search. Aggregating on things like tags, finding the most popular ones and then breaking down there use is what aggregations were made for and they do it incredibly fast. 

I'm betting the need to store a lot of these counts in the db goes away once we have a well-architected search solution in place.

**Comment by benhalpern** [comment]
Thanks for the feedback @rhymes.

I wanted to have this discussion and I thought tossing up a PR would get things rolling.

I had thought about option 1 that you described and I saw that table getting really big really quickly with different timeframe data. Although I'm not sure it's really a problem that it gets big quickly, it just sort of deterred me.

Option 2 is intriguing. Can we sort on all that data effectively?

I could go with either approaches. In terms of use cases to tackle, here is what I'm thinking:

- Situations like included here, where it's more for _display_ than sorting, but still nice to not gum up the main table on displays that don't happen most times we query the table.
- Sortable data to help query for information like "trending tags" etc. where we want to pre-compute some information and then sort.
- Aggregating data we want to pay attention to for user analytics, such as "active days this week", which would be a number between 1 and 7 depending on how many days they logged in. This would help us tally up how many everyday users we have vs 1 day users to help us observe trends and also build in behaviors. The key user-facing component of this would be stuff like modifying the feed for 1-day-a-week users vs 7-day-a-week users to have more "top" stuff for 1-dayers and more "fresh" stuff for 7-dayers. On the internal side of the site we could track daily users vs monthly etc. Currently we just don't have this shape of data overly accessible.

I think this all definitely lends to the idea that we should have sibling tables. I'm not totally sure which of options 1 and 2 I like, but I could go either way.

I switched this PR to `WIP`.

@mstruve where does the search solution come into play for the custom aggregates as described above, where we want to count "number of days active" which is not strictly a count of any other clearly defined information? I'm super duper in favor of trying to solve most of this with a robust search solution, but trying to understand which use cases might need which solutions.

**Comment by mstruve** [comment]
@benhalpern do you have a list of things that you want to count? What do you mean by "number of days active"? Is that like number of days a user has interacted with the site? That's something you could increment in a datastore like ES and then once that attribute is in there you could average it, get percentiles etc. Is that like what you were thinking?

**Comment by rhymes** [comment]
@benhalpern 

> I had thought about option 1 that you described and I saw that table getting really big really quickly with different timeframe data. Although I'm not sure it's really a problem that it gets big quickly, it just sort of deterred me.

I understand, we'd have N big tables instead 1 huge table, a little better but not great. That's also why I thought of option 2 

> Option 2 is intriguing. Can we sort on all that data effectively?

I believe so, you can create an index on a specific counter in the json payload and then tell SQL to order by it. Thanks to Rails we can even access the counters like: `user.counters.likes_count` instead of `user.counters.data[:likes_count]`. 

I can create a MVP/demo in the next few days to have an idea of how we could go about option 2.

Another advantage of option 2 is that we'd have only one row per user (or per tag or per article) and we load all counters related to that row from one column.

@mstruve I wonder if ES in this case is still worth it given the proximity of the data that has to be aggregated and the aggregated count (factoring the potential SQL query you already have to do plus the ES query plus the network roundtrip). Though the idea of asking Redis or Elasticsearch "tell me how many of these we have" instead of explicitly doing "SELECT COUNT(*)" on millions of rows in the background to update a counter is intruguing :) 

Anyway, the great thing about these discussions is that we'll figure out what's the best approach eventually and get there in steps :)

**Comment by benhalpern** [comment]
> I can create a MVP/demo in the next few days to have an idea of how we could go about option 2.

@rhymes getting a version of option 2 as a PR to evaluate would be really great!

We should focus primarily on the users table because that's the one we really want to count more closely, and in ways that aggregate other data in weird ways.

So if you start with some basic counts that offer functionality like what I wrote up in the `count_user_data` part of this PR, that would be great.

If we choose the wrong approach we can revisit this shortly without losing much, but a well-executed option 2 sounds great. I think introducing that use of JSONB into the codebase will help act as an example for further functionality.

I'll close this

**Comment by mstruve** [comment]
I like option 2 as well. Interested to see all the fields you want to count and then I might be able to work all or some of them into ES docs when those get rearchitected

**Comment by rhymes** [comment]
Agreed! I'll work on it :)

**Comment by rhymes** [comment]
I opened a work in progress PR here https://github.com/thepracticaldev/dev.to/pull/5373

**Comment by mstruve** [comment]
We are basically doing this with Datadog now so I am not even sure if we need this anymore. Going to close since it has been really inactive and has lots of conflicts. @benhalpern feel free to resolve the conflicts and reopen if we want to revisit this idea.

**Comment by rhymes** [comment]
@mstruve should we remove the code added with https://github.com/thepracticaldev/dev.to/pull/5373 too?

**Comment by mstruve** [comment]
Yeah! Let's get that cleaned up so it doesn't cause confusion in the future. I feel like we still have a bit of that type of code laying around

**Pull request closed without merging**
