### PR TITLE
Add twitter hashtag to the site config

### PR DESCRIPTION
**Pull request by JuanVqz**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents
Issue #7254

## Added tests?

- [x] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

**We need to set `SiteConfig.twitter_hastag = "DEVCommunity"` in the console.**

### CODE REVIEW

**Comment by JuanVqz** [comment]
Should I add some twitter hashtag by default?
Should I change the specific hashtag to this hashtag config on all the pages I may see?

**Comment by lightalloy** [comment]
Hi, @JuanVqz . Thanks for the pr!
> Should I add some twitter hashtag by default?
I think there is no need to add the default hashtag, but you'll need to add a note to the pr for a person who will merge it to update the current value on DEV:
`SiteConfig.twitter_hastag = "DEVCommunity"` (similar to the note in this pr => https://github.com/thepracticaldev/dev.to/pull/7564)

>  Should I change the specific hashtag to this hashtag config on all the pages I may see?
You're right, the hardcoded `DEVCommunity` should be replaced with the configurable one. You will need to update the related tests as well.

Another thing to add is the field in the `app/views/internal/configs/show.html.erb` so that the admins would be able to set up the hashtag.

**Comment by Ridhwana** [comment]
Hi @JuanVqz 😊 This PR is coming along nicely - if you'd like we can take this PR through review and live and then replace the twitter hashtags with the Site Config variables in a subsequent one, if this would be easier and quicker for you?

**Comment by JuanVqz** [comment]
Please don't forget this.
We need to set SiteConfig.twitter_hastag = "DEVCommunity" in the console.

**Comment by Ridhwana** [comment]
> Please don't forget this.
> We need to set SiteConfig.twitter_hastag = "DEVCommunity" in the console.

Thanks @JuanVqz 😊 I've added this to the PR description under post deployment tasks and I've added a label too. I'll add another issue tomorrow to replace the hashtags with the Site Config.

**Comment by Ridhwana** [comment]
@Zhao-Andy noticed that you on pager duty so dropping you a note on this PR: 

I'm merging this but not deploying it as yet as its still early for the US team :). 
After our next deploy (which will take this PR along) we'd need to set the record from the post deployment task. It won't break anything if it's not set immediately because we not using this config variable anywhere as yet 😊

**Comment by Zhao-Andy** [comment]
Updated, thanks for the ping!

**Pull request merged**
