### PR TITLE
[BUGFIX] Fix weird alignment for additional contents

### PR DESCRIPTION
**Pull request by wei-tg**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
Fixes alignment issue for divs appearing outside `home` container

## Related Tickets & Documents
#4379

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @wei-tg, thanks for your PR! I was wondering how did you find this? It's awesome!

Did you manage to reproduce this alignment problem?

**Comment by wei-tg** [comment]
Hi @rhymes, I did a DOM comparison between a working page and a page with problems mentioned in the issue. This helped narrow down to where it broke, which was in `div class="comments-container-container"`. 
The broken page had the class `show-comments-footer` outside of the `comments-container-container` when it should have been inside.

**Comment by rhymes** [comment]
@wei-tg can you please sign the CLA? thanks!

**Comment by wei-tg** [comment]
done so :)

**Comment by wei-tg** [comment]
Okay, I think the problem was when `full_comments_area` was refactored to use a partial view. It needs a parent container, so by moving the `</div>` to wrap the entire partial view, it worked because now `<div id="comments">` became the parent container.

I traced where this code first originated to https://github.com/thepracticaldev/dev.to/pull/642/commits/76afb4363edf6e4721492037586a45bafd48689e
and I feel a container like this `<div id="comments" style="margin-top: -50px;padding-bottom:50px;position:relative;z-index:-100"></div>` served no meaning, so might as well make it the parent container for `_full_comments_area.html.erb`

**Comment by rhymes** [comment]
@wei-tg great investigative skills!

**Pull request merged**
