### PR TITLE
[WIP] Add sorting to comments [#3001]

### LINKED ISSUE #3001: Add ability to sort comments by most recent
**Is your feature request related to a problem? Please describe.**
As a DEV commenter and thread watcher, I want to be able to more easily track new comments directly on the thread as they come in.

**Describe the solution you'd like**
An option at the top of the comment section that allows me to sort by newest.

**Additional context**
- For the scope of this request, I don't think we need to consider anything but top-level comments.

- This will make tracking super long threads, such as the Welcome thread, much easier.

### PR DESCRIPTION
**Pull request by matisnape**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Add sorting by Most recent and Oldest comments in /article#comments and /article/comments views.

TODO:
- [x] Styling
- [ ] Add tests

## Related Tickets & Documents
Fixes #3001 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by matisnape** [comment]
I have really big problems with merging upstream master into my fork ;/ Husky keeps returning errors for stuff I didn't touch, like:
```Rails/OutputSafety: Tagging a string as html safe may be a security risk.
In file: app/views/comments/index.html.erb:58

Rails/OutputSafety: Tagging a string as html safe may be a security risk.
In file: app/views/comments/index.html.erb:62

Rails/OutputSafety: Tagging a string as html safe may be a security risk.
In file: app/views/comments/index.html.erb:120

Rails/OutputSafety: Tagging a string as html safe may be a security risk.
In file: app/views/comments/index.html.erb:121

Rails/OutputSafety: Tagging a string as html safe may be a security risk.
In file: app/views/comments/index.html.erb:122

Rails/OutputSafety: Tagging a string as html safe may be a security risk.
In file: app/views/comments/index.html.erb:123```

**Comment by rhymes** [comment]
Hi @matisnape, I added the [WIP] tag since I've noticed the TODO list in the description, I also replaced `Issue #3001` with `Fixes #3001` in the description so that GitHub will automatically close the issue when this is approved and merged. Please remove it when you're done so we can go ahead and review the code in one pass.

I think you can ignore those `html_safe` warnings for now, those strings are all escaped and filtered when entering the code so it's safe to mark them as such. We'll review the code at the end no matter what.

It would be great if you could at least write some system tests acting as the user.

I have a question, what happens to subtree comments?  Are they all sorted by most recent or they are sorted relative to the leading comment?

Could you also provide UI screenshots for approval/discussion? If you install [Licecap](https://www.cockos.com/licecap/) or a similar tool you can also record the UI as an additional way to show how the feature works.

Thank you a lot!

**Comment by matisnape** [comment]
@rhymes 
1. Will write a test :)
2. I intended to sort by root comment, as the original issue suggested. I think it makes sense, for the sake of simplicity
3. Will add a screencast, too :)

**Comment by matisnape** [comment]
@rhymes I double checked - actually, subcomments also count into the sorting, so and old root with newer subcomment will move the thread according to the sorting order. Is that OK or shall I sort only by root comment?

**Comment by rhymes** [comment]
@jessleenyc @pkfrank what do you think? should we have sorting based on the root comment or newer comments? I don't think either is wrong per se but I imagine there are expectations and consequence in UX in either choice

**Comment by pkfrank** [comment]
I'd be interested in getting @benhalpern to weigh in on the root comment v. any comment for sorting purposes question.  I would probably expect root comment, but I don't feel strongly, and that might make it harder to keep track of new activity flowing in.

**Comment by mstruve** [comment]
Hey @matisnape! 

Looks like our team majorly dropped the ball on getting back to you about the root comment sorting issue. I am terribly sorry about that! 

With that said, we are in the process of going through and cleaning up some of our PR history to help us better prioritize what we need to be focusing on. Since this PR has not been active for a while and has some conflicts I am going to close it for now. If you would still like to get this merged please feel free to resolve the conflicts and then open the PR back up. We would be more than happy to help push this through if you would like!

Thanks so much for being an awesome contributor! Ping us anytime if you have questions!

**Pull request closed without merging**
