### PR TITLE
Topbar icons states

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description
This PR introduces hover states for icons in top bar. It also adds a styling for "current" state that will come a bit later.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

image

## Added tests?

- [x] no, because they aren't needed

## Added to documentation?

- [x] no documentation needed

### CODE REVIEW

**Comment by ludwiczakpawel** [comment]
I'd like to stick to current colors as they are mainly because I don't want to introduce another color variable if not needed. If we see a need for this extra shade between `-10` and `-20` in other places, I'll revise that. 

Also, visually I'm fairly ok with this shade as it is to be honest.. But I might be biased a little :D

**Comment by ludwiczakpawel** [comment]
> it's oddly shaped for the connect icon:
whoops, should be fixed now! good catch!

> is it normal that the default theme and the minimal theme have the same topbar background color?
yea, this is fine. we will revise ALL colors for other themes in some separate PR, but not sure when :P but generally it's fine.

**Comment by rhymes** [comment]
@ludwiczakpawel I think by merging you've resulted in some conflicts :(

**Comment by ludwiczakpawel** [comment]
@rhymes umm... whoops... i missed it :X fixing..

**Comment by ludwiczakpawel** [comment]
@rhymes should be good now.

**Pull request merged**
