### PR TITLE
preview of organization logo design on settings

### PR DESCRIPTION
**Pull request by artoodeeto**
- created a shared partial logo_design file
- moved text, bg and logo from profile.html.erb to logo_design.html.erb
- used logo_design to org_admin

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
org admin can preview dev.to design logo

## Related Tickets & Documents

feature-request #4321. See also #4212

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
**SAMPLE**
ezgif com-optimize
**DB**
Screen Shot 2019-10-09 at 9 57 24 PM

**mobile**
Screen Shot 2019-10-09 at 8 49 23 PM

**tablet**
Screen Shot 2019-10-09 at 8 49 37 PM

**desktop**
Screen Shot 2019-10-09 at 8 50 04 PM

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

shy

### CODE REVIEW

**Comment by artoodeeto** [comment]
hallooo there are some test that failed but unrelated to this issue.

```
 1) User visits articles by tag when user hasn't logged in when 2 articles shows the header
     Failure/Error: raise Pundit::NotAuthorizedError, "You must be logged in" unless user
     
     Pundit::NotAuthorizedError:
       You must be logged in
```

```
2) Reading list without tags when large readinglist shows the large reading list
     Failure/Error: params = { filters: "viewable_by:#{current_user.id}" }
     
     NoMethodError:
       undefined method `id' for nil:NilClass
```

**Comment by artoodeeto** [comment]
@rhymes yea for sure. no problem. thank you. I didn't much do anything really. I just moved it to a different file. :smile:

**Comment by Link2Twenty** [comment]
Now that there is a partial we could in easily add a contrast indicator that will exist on each instance   🎉 🎉

**Comment by coolbrg** [comment]
Hi @artoodeeto ,

You forgot to update one file. Please check https://github.com/coolbrg/dev.to/commit/3c74ffcabe0270a4bf3f4d50058c1c0214694de3

PR looks nice now. 👍

**Comment by artoodeeto** [comment]
@coolbrg opps. thank you. thought only for admins. :smile:

**Pull request merged**
