### PR TITLE
Fix remaining erblint errors

### LINKED ISSUE #8370: Errors when running `bundle exec erblint --lint-all`
**Describe the bug**

Running `bundle exec erblint --lint-all` outputs `130 error(s) were found in ERB files`.

**To Reproduce**

1. Run `bundle exec erblint --lint-all`
2. See 130 errors

**Expected behavior**

There shouldn't be any errors.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04 (WSL2)
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

I found this while working on #8369, as one error (fixed on that PR) was preventing me from creating a commit with changes on the file with such error. I had to fix that error manually as the pre-commit hook, which runs erblint with the `--autocorrect` flag, wouldn't work.

I'm happy to work on fixing this issue!

### PR DESCRIPTION
**Pull request by AlbertoPdRF**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

This PR fixes the remaining errors resulting from running `bundle exec erblint --lint-all` 🎉 I didn't make separate PRs for them because there's only one file affected in each folder and not too many files.

## Related Tickets & Documents

~This PR is part of #8370. I haven't typed `Fixes #8370` because there's still something that requires a fix. I'll comment about that on the issue right now.~

Fixes #8370.

This PR includes a fix that was previously included in #8369, so that PR will need to be rebased after this one is merged!

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Done gif

### CODE REVIEW

**Comment by AlbertoPdRF** [comment]
> do you want to add [#8370 (comment)](https://github.com/thepracticaldev/dev.to/issues/8370#issuecomment-642670607) to this PR as well?

Sure! I'll push a commit including that.

**Comment by AlbertoPdRF** [comment]
I've updated the original comment so that merging this PR closes #8370 🎉

**Comment by rhymes** [comment]
closing and reopening it to see if Travis gets unstuck

**Comment by rhymes** [comment]
@AlbertoPdRF could you kindly rebase on top of master? We likely fixed the problem with the parallel builds

**Comment by AlbertoPdRF** [comment]
Done!

**Pull request merged**
