### PR TITLE
Bump eslint

### PR DESCRIPTION
**Pull request by greysteil**
Replacement for #470. By default, Travis uses an ancient version of Node. Caching the `.$HOME/.nvm` directory should mean we can use a more up-to-date one without slowing down CI. (Setup lifted from [Rails](https://github.com/rails/rails/blob/master/.travis.yml).)

### CODE REVIEW

**Comment by greysteil** [comment]
💚.

Looks like the ESLint bump is fine to merge. You may want to change the `nvm install ...` line to install whatever version of Node you're running in production, though.

**Comment by maestromac** [comment]
@dependabot-bot rebase

**Comment by greysteil** [comment]
Ah, it can’t do this one because I created this PR separately. I’ll rebase it, though!

**Comment by maestromac** [comment]
@greysteil oh right 😅

**Comment by greysteil** [comment]
@maestromac - good to go now.

**Pull request merged**
