### PR TITLE
Branded authentication buttons

### PR DESCRIPTION
**Pull request by ludwiczakpawel**
## What type of PR is this? (check all applicable)

- [x] Feature
- [x] Optimization

## Description

This PR introduces "branded" styling for authentication buttons. Instead of all auth button being purple they now have appropriate styling for github, twitter and apple (you won't see apple one since this is [in progress](https://github.com/thepracticaldev/dev.to/pull/7952), but the styling is there)

## Related Tickets & Documents

- https://github.com/thepracticaldev/dev.to/pull/7952

## QA Instructions, Screenshots, Recordings

image

You can see them in right hand sidebar when logged out.

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by ludwiczakpawel** [comment]
@rhymes I need help with failing test and that IF statement I mentioned on Slack:
1. https://github.com/thepracticaldev/dev.to/pull/8679/files#diff-2674c9d86272e71a291f0014ccfd0be8R1-R3
2. https://github.com/thepracticaldev/dev.to/pull/8679/files#diff-6eed6243f04a64c3b2b4ce4b7d7d25aeR3-R5

**Comment by nickytonline** [comment]
Love that these are branded now. Just giving the PR a review.

**Comment by ludwiczakpawel** [comment]
>  @rhymes, is that enabled for DEV yet?

@nickytonline It's actually [the reason](https://github.com/thepracticaldev/dev.to/pull/7952#issuecomment-644006417) why I'm adding this :)

**Comment by benhalpern** [comment]
Looks good to me, but some of the tests need to be modified slightly to account for new button content.

**Comment by rhymes** [comment]
@benhalpern on it :)

**Pull request merged**
