### PR TITLE
Feature🚀: Ability to see chat history by scrolling up

### PR DESCRIPTION
**Pull request by sarthology**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Ability to see chat history, by scrolling up. Very time you scroll up you 150 messages will be fetched till you reach in the end.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

### CODE REVIEW

**Comment by sarthology** [comment]
> One thing I wanted to ask, by looking at the code it's not clear what `messageOffset` represents, is that the ID of the last seen message?

So`messageOffset` is just a number to set an offset while fetching messages from DB. That offset is basically equal to the amount of message already fetched in previous requests.

` @chat_messages = @chat_channel.messages.includes(:user).order("created_at DESC").offset(params[:message_offset]).limit(150)`

**Comment by rhymes** [comment]
I'm trying to think about this in my head: do you think is there a scenario where a message is skipped because the offset is the wrong length because new messages have appearead in the meantime down at the bottom?

**Comment by sarthology** [comment]
I don’t think so but I will run that scenario

**Comment by sarthology** [comment]
But if you have some suggestions, am all ears. 🙂

**Comment by rhymes** [comment]
Not yet, it's just an intuition but I haven't zeroed on it yet :-)

**Comment by benhalpern** [comment]
I was about to agree with @rhymes but I _think_ this is safe because you're always re-querying the total number of messages displayed. I think this concern harkens to race conditions with traditional pagination with less total information available. I think this is safe.

I'm experiencing an issue when my window is _huge_ with scrolling up glitching me back to the bottom (I have a huge 4k monitor). I'm not sure what exactly triggers this.

But related to this, and as a general thought.... Every single scroll updates the entire state, which leads to some re-renders of components which shouldn't re-render so consistently.

I think this problem is bigger than just this one change, but it's something to keep in mind. We should begin making better use of `shouldComponentUpdate` and similar lifecycle functions (or new fancy things I don't know about) to make sure this all functions smoothly and efficiently, avoiding avoidable re-renders.

**Comment by sarthology** [comment]
I agree re-rendering should be avoided in those cases where it can be avoided, like the case of showing and hiding *Jump Back* button. So I removed it. But the real problem was that I was using the fixed numbers to calculate how much messages are scrolled, like this `this.scroller.scrollTop < this.scroller.scrollHeight - 2000` but now I'm calculating a more precise ratio to know the same, and it's like this
` (this.scroller.scrollTop + this.scroller.clientHeight) / this.scroller.scrollHeight; `

Please give it another try.

**Comment by rhymes** [comment]
Such a cool feature! I've been scrolling all morning ahhaha

**Pull request merged**
