### PR TITLE
Add vault-rails gem

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Feature

## Description

We're currently leaning towards introducing Vault for secret management, this draft PR gives @jdoss something to play with.

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by jdoss** [comment]
@mstruve is checking this out too. Let's try and sync efforts here soon.

**Comment by citizen428** [comment]
@jdoss For sure. This PR only addds the gem and a basic initializer so far.

**Comment by mstruve** [comment]
After doing some work with this yesterday I am pretty sure we don't need vault-rails, we only need the vault Ruby Gem. This gem is what we would want if we were using vault to encrypt fields on our ActiveRecord models. Instead, we want to use it to store auth and third party tokens.

**Comment by citizen428** [comment]
@mstruve Good point, changed this PR to use `vault-ruby`.

**Comment by mstruve** [comment]
Closing in favor of https://github.com/thepracticaldev/dev.to/pull/8891

**Pull request closed without merging**
