### PR TITLE
style: fixed z-indexing bug in sidebar reactions

### PR DESCRIPTION
**Pull request by anuraghazra**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Fixed zindex in Sidebar reactions panel which was overlapping with the navbar.

## QA Instructions, Screenshots, Recordings
devtofix

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Very small fix
alt_text

### CODE REVIEW

**Comment by ludwiczakpawel** [comment]
Hey @anuraghazra , would you mind explaining me in what scenario have you noticed this issue? I mean, I'm trying to repro that issue locally and I don't know how to do it. I'd love to know a bit more context if you don't mind since this should not happen (but I could be wrong easily :))

**Comment by anuraghazra** [comment]
This is happening for all the dev.to posts. 

1. Goto any dev.to article.
2. Scroll to bottom until you see "Read next" posts.
3. Notice the Navigation bar

image

**Comment by ludwiczakpawel** [comment]
Oh wow yea :D Good catch!

**Comment by rhymes** [comment]
Closing it and repening as Travis is not reporting the successful builds

**Comment by rhymes** [comment]
Added an empty commit to retrigger the builds

**Pull request merged**
