### PR TITLE
Refactor duplicate blocks in users_controller#onboarding_*

### PR DESCRIPTION
**Pull request by notapatch**
- Work for #3739

## What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Refactoring of duplicate blocks within users_controller

## Related Tickets & Documents
#3739 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by FeruzOripov** [comment]
Oh I see, I have also refactored the same file #3822. I will close my PR.

**Comment by notapatch** [comment]
giphy

**Comment by rhymes** [comment]
Hi @notapatch, sorry for us taking so long to review this. I know how much time and effort can go in setting up systems and contribute to them.

Unfortunately we believe there's not enough duplication to warrant this refactoring, sometimes Code climate is overzealous in recommending restructures and this one though seemingly simple has an impact on readability.

Thanks for the contribution and we hope to see your name around the repo again!

**Comment by notapatch** [comment]
Yeah, I've had a long time to think about it :-)  I agree, premature refactoring is more dangerous than two duplicated blocks of code.

**Pull request closed without merging**
