### PR TITLE
Add a /quickin route for development

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
**Initial Description** 
This PR adds a route to allow someone in development to grab an account easily. Sometimes you need multiple accounts to reproduce a bug, and this allows for that!

If this PR goes unmerged, this tactic should at least be documented for people wishing to contribute, that way people don't have to DM Andy 😉

```
This is a trick that Andy shared with me for grabbing a user during
local development. I totally get why this commit might be best left out
of the repository, but I think it should be fine as a workaround while
an alternative method for masquerading as users is developed.
```

**Post Feedback Description**
So I've rolled this stuff into an engine in the lib directory that is only required in the development group.

Hopefully, I've also documented that this is pretty hacky well enough.

You won't hurt my feelings if you say this is too sketchy.. it's pretty sketchy. 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

If this is determined to be an acceptable solution, I will make a follow-up PR to document this route in both contributing.md and the development documentation site.

## [optional] What gif best describes this PR or how it makes you feel?

Fallout lockpicking gif

### CODE REVIEW

**Comment by jacobherrington** [comment]
I have seen a few flaky tests, but I haven't actually been able to get this one to fail locally.

**Comment by rhymes** [comment]
I think the test is failing because `All the King's Men` gets quoted to `All the King&#39;s Men` in the HTML. The test should take that into account. I'll take care of it in a separate PR.

Regarding the quickin, a previous unmerged PR https://github.com/thepracticaldev/dev.to/pull/2361 had it as well and as much as handy it can be I think we're not still 100% sure this should be part of the code base in master.

I do have something similar in a local branch that I keep synced with master and I use from time to time when I have to test something that pertains the relationship between two users.

**Comment by jacobherrington** [comment]
@rhymes I can agree with apprehension on this change, but it'd be great to include this method as a note in the documentation. Do you think that would be a better approach?

An alternative to this approach could be rolling this route and action into a gem in the lib directory that only gets required in development. Does that sound more palatable?

Ultimately, you could ease the need for this feature if we implemented some masquerade feature described in this [article by ThoughtBot](https://thoughtbot.com/blog/how-to-masquerade-as-another-user-to-see-how-they-use-yo) or by using something like the [devise_masquerade](https://github.com/oivoodoo/devise_masquerade) gem (but probably not that gem because it looks a bit unmaintained). I would advocate restricting such a feature to development.

Thoughts on any of those points? If you feel this feature is best left out of the codebase, I'd be happy to just put this snippet in the documentation.

**Comment by rhymes** [comment]
> I can agree with apprehension on this change, but it'd be great to include this method as a note in the documentation. Do you think that would be a better approach?

I don't know yet, that's why I'm a little uncomfortable with it. But I agree with you that it should be explicitly enabled only in development in as much places as possible :D It shouldn't run in any other environment, we don't want to end up like "view as" like Facebook :D

> An alternative to this approach could be rolling this route and action into a gem in the lib directory that only gets required in development. Does that sound more palatable?

Right now it'd probably be easier to have all the code in the monolith, but that's a good idea too!

I'm not here to make a decision either way, I just wanted to voice my concerns

**Comment by Zhao-Andy** [comment]
I like the idea of moving it into a gem that is only required for development!

**Comment by jacobherrington** [comment]
@Zhao-Andy I moved it into a gem. This is pretty hacky, but it does work... It will also make deleting it incredibly easy 😂

**Comment by jacobherrington** [comment]
@Zhao-Andy I might re-implement it at some point and put it on RubyGems, but for now, I think we should keep a short leash on it. lol

**Comment by jacobherrington** [comment]
@Zhao-Andy I added some documentation around this -- it dismissed your review. Sorry 🙃

**Comment by benhalpern** [comment]
This is really nice. I like the establishment of using internal gems to solve some of these problems. We're going to sleep on it and make sure we're all cool with the approach.

**Comment by jacobherrington** [comment]
@benhalpern That's a good idea. It's definitely a little weird.

**Comment by keithrbennett** [comment]
In my opinion, having this option available in development mode would be super helpful, and would lower the barrier to others getting involved in the project.

**Comment by jacobherrington** [comment]
I'm going to go ahead and close this!

**Pull request closed without merging**
