### PR TITLE
Fix linting issues in app/views/internal

### PR DESCRIPTION
**Pull request by arnellebalane**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Fix linting issues in views located in `app/views/internal` (excluding those in `articles` directory, that's done in #1873 ).

The remaining `Lint/UselessAssignment` issues are just left alone since it's already being disabled in #1886 .

## Related Tickets & Documents

#1842 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by arnellebalane** [comment]
@lightalloy How should the `Lint/SafeNavigationChain` error be handled? The line of code that's raising this issue looks like:

```erb
<% feedback_message.notes&.order("created_at").each do |note| %>
```

**Comment by rhymes** [comment]
@arnellebalane if you check Rubocop's doc on [Lint/SafeNavigationChain](https://rubocop.readthedocs.io/en/latest/cops_lint/#lintsafenavigationchain) you'll see that their recommendation is that you're supposed to use the chain `&` operator after each method call after the first one that could be nil. So in this case, it would be:

```ruby
notes&.order("created_at")&.each do |note|
```

This should make it go away, I haven't tried.

**Comment by arnellebalane** [comment]
@rhymes I was initially undecided between adding `&` to the succeeding method calls or removing the `&` from the first one. I guess I'll also just go with the former (as per your/rubocop's suggestion) since it feels much safer than the latter.

I will update my PRs to try incorporate this. Thank you for guidance ❤️

**Comment by rhymes** [comment]
@arnellebalane I wouldn't remove it because if notes is nil the partial crashes :D

**Comment by arnellebalane** [comment]
@rhymes Haha that makes sense, should have realized that earlier on 😅 . Thank you!

**Comment by lightalloy** [comment]
I think the `&`s could be removed, cause `notes` is an activerecord collection, so there's no chance that it'll be `nil`

**Pull request merged**
