### PR TITLE
Refactor: initializeDrawerSliders.js

### PR DESCRIPTION
**Pull request by sagarchoudhary96**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Refactors file according to eslint rules.

## Related Tickets & Documents
#3777 

# Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@rhymes @benhalpern  this is the new PR with same changes.

**Comment by rhymes** [comment]
Linking https://github.com/thepracticaldev/dev.to/pull/4316 because the initial review sits there

**Comment by rhymes** [comment]
@benhalpern my review is in the previous PR this was duplicated from https://github.com/thepracticaldev/dev.to/pull/4316#pullrequestreview-299239227

**Comment by sagarchoudhary96** [comment]
@rhymes any updates on this?

**Comment by rhymes** [comment]
@sagarchoudhary96 I just updated it to the current master, because we changed Ruby version and other things. I'll review it promptly

**Comment by sagarchoudhary96** [comment]
> Hi @sagarchoudhary96, sorry for the delay.
> 
> I've noticed you didn't apply che changes requested in the previous branch - [#4316 (review)](https://github.com/thepracticaldev/dev.to/pull/4316#pullrequestreview-299239227) - so I'm going to reject this on the same principle.
> 
> Please take a look at that review.
> 
> In the meantime I went ahead and updated your branch to the current master, please do a `git pull` on your local copy before working on this

for this, i didn't make changes till now because you mentioned that few things need to be reviewed by @benhalpern, so I'm waiting for his confirmation on the PR then only i can go ahead making the changes

**Comment by mstruve** [comment]
Hey @sagarchoudhary96!
 
Thank you so much for the refactoring PR! With that said, we are in the process of going through and cleaning up some of our PR history to help us better prioritize what we need to be focusing on. Since this PR has not been active for a while I am going to close it for now. 

If you would still like to get this merged please feel free to make the requested changes and then open the PR back up. We would be more than happy to help push this through if you would like!

Thanks so much for being a contributor! Ping us anytime if you have questions!

**Pull request closed without merging**
