### PR TITLE
Refactor stories show

### PR DESCRIPTION
**Pull request by delbetu**
## What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Improving stories_controller#show implementation.

## Related Tickets & Documents
Related to https://github.com/thepracticaldev/dev.to/issues/2914
Regarding the code climate issues.
* Two of them are regarding the usage of `html_safe`. Since that code was already working I assume that is correct.
* The other one is invalid, code climate thinks that the rendered template could be manipulated, but in fact, it only can contain two static values.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by delbetu** [comment]
@lightalloy Maybe you're interested in this change.

**Comment by mstruve** [comment]
Hey @delbetu! Thank you so much for the thoughtful PR! 

I have to agree with @lightalloy on this one. I think the main thing we were going for in this refractor was to make all of these routes more "Rails" like so we don't have to have a long set of `if` statements trying to figure out what we want to load. This would also help with performance bc you don't have to do a bunch of checking every time you load this single route. Instead using the routing as Rails intends would allow us to know what we are looking for just based on the route that is hit. Does all of that make sense? 

Let us know if you have any questions or suggestions to help us make the Issue more clear! We definitely strive to make things as clear as possible but it looks like we missed the mark a bit on this one.

**Comment by delbetu** [comment]
@mstruve I think that what you're saying is:
`"We're performing routing logic inside the controller, that logic should be in Rails Routes"`
That is because the url `/xxx/yyy` matches only one controller action but is being used for multiple purposes.

After this refactor those purposes are cleared expressed. [see](https://github.com/thepracticaldev/dev.to/pull/5009/files#diff-083205a4907086cda7bfb330fabc046aR45-R57)
In previous code that logic was spread over multiple places.

Moving that routing logic to Routes would involve several stories of kind `"Support new URL for xxxxxx"`.
These stories would need to:
* Add new route for supporting new url
* Replace existing links
* Investigate: what happens with legacy url? should we remove or support it?
* Take into account that these url could be bookmarked or shared through social media by many users. should we support legacy url and redirect to new url ??

I consider this PR as a previous step before tackling these stories.

What do you think?

**Comment by mstruve** [comment]
I 100% agree that this PR allows those routes to be more clearly expressed, but at the same time a large refactor like this contains risks. We know the code as-is works. Refactoring it in this large way means we might introduce some unexpected bugs. I believe the safer approach is to maintain the status quo as is and walk through the steps you mentioned for setting up each new route. As we set up each new route we can also add additional tests to ensure those new routes work as intended. I think updating routes individually is less likely to lead to new bugs than trying to refactor this big complicated controller as is.  

In an effort to make the [related issue](https://github.com/thepracticaldev/dev.to/issues/2914) more clear I added those steps you mentioned above for breaking out the logic of the stories controller into individual routes since that is really what we are after. Seriously, thank you so much for those clearly laid out steps! I sincerely apologize that [the issue](https://github.com/thepracticaldev/dev.to/issues/2914) was not as clear as it should have been and that caused you to spend a lot of your valuable time working on something which wasn't quite what we wanted 😞  

I am going to close this PR but if you have any other advice or feedback to help us make [that issue](https://github.com/thepracticaldev/dev.to/issues/2914) or others more clear please let us know so that we can avoid any confusion in the future. We truly want contributing to be as easy and seamless as possible.

**Comment by delbetu** [comment]
@mstruve I was afraid that such a big PR wasn't going to be accepted due to the risk that it represents.
Since the [contribuition guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md#how-to-contribute) says:
```
Refactoring code,.... you can rely on existing tests to ensure that your refactoring doesn't introduce any unexpected behavior. However, you might be asked to write a regression test if the area you've refactored isn't well covered.
```

Let's say that I create a separate PR introducing a set of acceptance tests to make sure we cover all the cases supported by `/xxxx/yyyy` URLs.

After getting those tests in place, would you accept this PR?

**Comment by delbetu** [comment]
@lightalloy let me comment between lines.

`the logic stays in the same route. Using separate routes could be beneficial in terms of optimization in the future, we could look at the metrics and find out which route needs optimization.`
That is right, this PR intention is not to separate into multiple routes.

`all the logic also stays in the same controller and is managed by a number of Stories::Show's arguments, which leads to lots of if statements and doesn't help understanding.`
I'll draw a dependency graph showing the new structure:
```
StoriesController --> Articles::Show --> Artilces::Show::Presenter
                                |------> PodcastShowPresenter
```
Basically there is only one `conditional` which is [this one](https://github.com/thepracticaldev/dev.to/pull/5009/files#diff-083205a4907086cda7bfb330fabc046aR38-R58)
The switch statement is made over the strings that the `url_format` returns.
(those strings are not necessarily, their intention is to explain the format of the url to the reader.)

let me show you how the initial controller method used to look like:
(This is after inlining all the methods that `show` was calling. They were private methods of the controller)
```ruby
def show
    @story_show = true
    if (@article = Article.find_by(path: "/#{params[:username].downcase}/#{params[:slug]}")&.decorate)
      # assign_article_show_variables
      @article_show = true
      @variant_number = params[:variant_version] || (user_signed_in? ? 0 : rand(2))
      # assign_user_and_org
      @user = @article.user || not_found
      @organization = @article.organization if @article.organization_id.present?
      @comments_to_show_count = @article.cached_tag_list_array.include?("discuss") ? 50 : 30
      # assign_second_and_third_user
      if !@article.second_user_id.blank?
        @second_user = User.find(@article.second_user_id)
        @third_user = User.find(@article.third_user_id) if @article.third_user_id.present?
      end

      not_found if permission_denied?
      @comment = Comment.new(body_markdown: @article&.comment_template)

      set_surrogate_key_header @article.record_key
      redirect_to "/internal/articles/#{@article.id}" if params[:view] == "moderate"
      return if performed? # did previous redirect happen?

      render template: "articles/show"
    elsif (@article = Article.find_by(slug: params[:slug])&.decorate)
      potential_username = params[:username].tr("@", "").downcase
      @user = User.find_by("old_username = ? OR old_old_username = ?", potential_username, potential_username)
      if @user&.articles&.find_by(slug: params[:slug])
        redirect_to URI.parse("/#{@user.username}/#{params[:slug]}").path
        return
      elsif (@organization = @article.organization)
        redirect_to URI.parse("/#{@organization.slug}/#{params[:slug]}").path
        return
      end
      not_found # this is not covered by tests
    else
      @podcast = Podcast.available.find_by!(slug: params[:username])
      @episode = PodcastEpisode.available.find_by!(slug: params[:slug])
      set_surrogate_key_header @episode.record_key
      @episode = @episode.decorate
      @podcast_episode_show = true
      @comments_to_show_count = 25
      @comment = Comment.new
      render template: "podcast_episodes/show"
      nil
    end
  end
```
and how it looks now:
```ruby
  def show
    @story_show = true

    result = Stories::Show.new(
      first_scope: params[:username],
      second_scope: params[:slug],
      moderate: params[:view] == "moderate",
      preview_value: params[:preview],
      user_signed_in: user_signed_in?,
      variant_version: params[:variant_version],
    ).execute

    if result.redirect
      redirect_to result.destination_url
    else
      @presenter = result.presenter
      set_surrogate_key_header result.surrogate_key
      render template: result.template
    end
  end
```

**Comment by delbetu** [comment]
Also, the new classes have clearly defined responsibilities.
**StoriesController**
Delegate call to Articles show
Take the result and decide whether it needs to redirect or render some page.
**Articles::Show**
Determine how the url is intended to be interpreted and delegate to the correct case(articles/podcast/redirect).
**Artilces::Show::Presenter**
Hold data to be accessed in the view
**PodcastShowPresenter**
Hold data to be accessed in the view

**Comment by mstruve** [comment]
Hey @delbetu, while a comprehensive set of acceptance tests for this endpoint would be amazing, we still think time would be better spent moving towards the more Rails like approach and writing comprehensive tests as we move towards that approach. Even with a new set of acceptance tests, there is still going to be some risk with a refactor this large. Right now we don't think that risk is worth it since we are not achieving our end goal of a more Rails like architecture with this code.

Once again, I am so sorry we were not more clear in the initial issue as I know you spent a lot of time on this PR. Let us know if you have any other further questions!

**Pull request closed without merging**
