### PR TITLE
Replace querySelector and getElementsByTagName when selecting for head and body

### PR DESCRIPTION
**Pull request by icncsx**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

Addresses #6380 - replacing `querySelector` and `getElementsByTagName` when selecting for `<head />` and `<body />` in favor of [document.head](https://developer.mozilla.org/en-US/docs/Web/API/Document/head) and [document.body](https://developer.mozilla.org/en-US/docs/Web/API/Document/body). Coverage is solid across all browsers: desktop and tablet/mobile.

Other changes are cosmetic and are made automatically by the pre-commit hook (husky). It looks they are mostly linting clean-up operations.

## Related Tickets & Documents

Issue #6380.

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by icncsx** [comment]
Hey @rhymes Do I have to do anything for the `codeclimate/diff-coverage` failure? Admittedly, I have no idea what that even means.

**Comment by nickytonline** [comment]
@icncsx, don't worry about the code climate changes. We'll take care of it. The only thing left to do is fix the conflicting file mentioned. I'd suggest merging the latest of master to resolve this.

**Comment by icncsx** [comment]
Hi, @nickytonline. It looks like Ben did that for me. Let me know if you need anything else!

**Comment by nickytonline** [comment]
Looks good @icncsx! Thanks for the PR!

**Pull request merged**
