### PR TITLE
FIX: Disable instantClick on mobile devices

### PR DESCRIPTION
**Pull request by venarius**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
Today, I explored the dev.to website a bit more on my mobile device and suddenly noticed a strange behavior when scrolling the tag list:

Peek 2019-04-15 17-53
( Bad to notice on this gif )

It was lagging like hell and not really nice to scroll this way. That's why I investigated a bit more on this occurence on my desktop using mobile mode, enabled the profiler and noticed this:

Screenshot from 2019-04-15 17-54-52
KvzU

The javascript was doing requests to agolia search every single second! Also loaded a lot of network objects ( pictures, css and js files ) that my computer and phone had to stand.

Looking a bit more into it, I noticed that I came from the JS-Library InstantClick. While InstantClick may make the site "feel" a bit faster, it comes at a **big** sacrifice of hitting your backend. ( We had that same discussion a couple of weeks ago at Discourse ). And if you also hit a service like Agolia with it, it may also increase the costs of this service by a lot.

Also, InstantClick should **always** be disabled on mobile phones, since it can consume lots of data. That's why I added a mobile check to the InstantClick function to make it only work on desktop browsers. That changed a lot:

Screenshot from 2019-04-15 18-04-51

Not only are all the ajax requests in the back gone, the site also feels a lot more responsive on the phones now.

source

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Great catch @venarius - I wonder if this it's going to have any impact on the UX of users inside the webview of https://github.com/thepracticaldev/DEV-ios - What do you think?

**Comment by venarius** [comment]
@rhymes if its going to have any impact, then probably only on the good side. With that amount of ajax requests in the tags view for example even my galaxy note 8 got slowed down.

**Comment by benhalpern** [comment]
> requests to agolia search every single second

I feel like this may be a separate issues than InstantClick—or at least an unintended side effect. I'm going to look into this more.

**Comment by benhalpern** [comment]
Hey, I was never able to determine that this was actually the issue going on. So I'm going to close this for now. Perhaps open an issue to discuss this problem?

**Pull request closed without merging**
