### PR TITLE
Documentation Improvements to Storybook

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description

Introduces the Storybook [notes addon](https://github.com/storybookjs/storybook/tree/master/addons/notes).

Notes allow one to add notes to a particular component. Notes are written in markdown.

The 1st section of our Storybook, "Guidelines", that were written in HTML and in JSX originally as a fake story are now markdown.

## QA Instructions, Screenshots, Recordings

image

To test:

- Navigate to the [Storybook Netlify preview](https://deploy-preview-8947--storybookdevto.netlify.app/?path=/story/3-components-buttons--default)
- In the panel below the button component, click on the Notes tab. There will be a note about button components.

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Winston from New Girl at a job interview saying he knows Microsoft Word

### CODE REVIEW

**Comment by nickytonline** [comment]
> Sooo soooo cool!
> 
> Any reason why sometimes notes are in markdown and sometimes in HTML?

All notes are in markdown. I left the guidelines in HTML (taken from https://dev.to/page/crayons), because there are no Storybook stories for them. They can be converted to markdown if you want and then everything is markdown. I'm good either way.

**Comment by nickytonline** [comment]
@ludwiczakpawel, actually, it just makes sense to make everything markdown. I just converted it to markdown (thank you Google). So no HTML now.

**Comment by nickytonline** [comment]
> Looks cool! I wonder if we should replace `DEV` with `Forem` over the various documentation files

@rhymes, I’d say do that once we can also deploy Storybook to a Forem URL. We currently deploy to https://storybook.dev.to

**Comment by rhymes** [comment]
@nickytonline that makes sense, it's just that we've been changing DEV to Forem in docs.dev.to as well, that's why it popped in my mind, see https://docs.dev.to/contributing_forem/ and https://github.com/thepracticaldev/dev.to/pull/8939

**Comment by nickytonline** [comment]
> @nickytonline that makes sense, it's just that we've been changing DEV to Forem in docs.dev.to as well, that's why it popped in my mind, see https://docs.dev.to/contributing_forem/ and https://github.com/thepracticaldev/dev.to/pull/8939

Yeah, good point. Not thinking clearly. 😅 I can do that.

**Comment by nickytonline** [comment]
> This is a really good idea! 👍
> 
> I think there is room to flesh these docs out and refine them, but having the documentation in place is a win and we shouldn't spend a ton of time editing them up front. I am good with merging this as is, that way we can work on content edits as we go! 🤓

We had the same documentation previously in Storybook. It was just harder to update. Now that we're on Preact X, we can use the notes addon which makes it a lot easier and is in line with the rest of our documentation, a.k.a. markdown.

**Pull request merged**
