### PR TITLE
Add headings to header tags

### LINKED ISSUE #127: Markup: Headers should contain headings
# _TASK_
### Request or User Story
As of now, any `<header>` without an `<h*>` in it isn't really semantic. The header indicates a section of content describing the rest, but still needs an `<h2>` or what have you.

### PR DESCRIPTION
**Pull request by ashwinv11**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Updating all `<header>` tags to have appropriate `<h*>` tags inside them where applicable. Replacing some header tags with semantically correct alternatives.

## Related Tickets & Documents

fixes #127 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

N/A

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

popit

### CODE REVIEW

**Comment by benhalpern** [comment]
Hey just wanted to say thanks a lot for this. I'll get to reviewing this tomorrow. Sorry, it's a bit daunting to ensure there are no gotchas.

**Comment by bennypowers** [comment]
Please don't neglect https://github.com/thepracticaldev/dev.to/pull/713 which is related (and afaict ready to merge)

**Comment by ashwinv11** [comment]
Nice! Will work on the conflicts tonight so we can get this reviewed as well.

**Comment by Zhao-Andy** [comment]
Hey @ashwinv11, happy to fix the conflicts for you if you'd like. I'll review your PR at the same time. :)

**Comment by ashwinv11** [comment]
@Zhao-Andy that'd be great! :)

**Comment by benhalpern** [comment]
Some refactoring has caused this PR some pain. All the HTML is pretty much the same, but the content has been moved around to some different files.

Sorry about the ongoing issues with this one. We'll work to get this fixed and merged asap.

**Pull request merged**
