### PR TITLE
Bust cache for articles in series

### LINKED ISSUE #3003: Ensure each post in a series reflects latest changes
**Describe the bug**
After adding a new post to the series, a previous post has not updated the "index" of the series at the top of the article.  Probably caching related.

**Expected behavior**
All posts in a series are in sync as it relates to the navigation at the top.

**Screenshots**
example of issue

### PR DESCRIPTION
**Pull request by edisonywh**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description

Currently `article` already has `after_save  :bust_cache` callback, which will bust the cache, however the problem right now is the other articles in the collections aren't being cache-busted too. The idea is to bust all other articles in the collection's cache when a single one is busted. Fix is as follow:

* Adds `touch: true`  to `Article/Collection`, so when a single article is updated,
it'll update the corresponding `Collection`.

* Adds an `after_touch` callback to `Collection`, so when it's being
updated (specifically being `touched` only), it'll also update all
articles in the collection.

## Note
* I'm not exactly sure how to test this cache, would appreciate any pointer
* I'm not sure if we want to run ALL the callbacks for `Article`. See [here](https://guides.rubyonrails.org/active_record_callbacks.html#updating-an-object) for list of callbacks that'll get triggered when I call `update_all` in `Collection`

## Related Tickets & Documents
Fixes #3003

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

guy in ghostbuster suit dancing

### CODE REVIEW

**Comment by edisonywh** [comment]
@benhalpern hey is there anything I can do to move this forward? :)

**Comment by maestromac** [comment]
Hello @edisonywh can you create `collection_spec.rb` and add tests to this?

**Comment by edisonywh** [comment]
Ah that's one way to test it, thanks! Will implement it and update you guys when I've done so!

**Comment by edisonywh** [comment]
Hey @maestromac, I managed to push an update, this took a bit longer because I was stuck when I came across these two problems:

1) `Article` has a `before_validation` callback that calls `evaluate_markdown`, which in turns makes a call to `evaluate_front_matter`. The problem lies at `app/models/article.rb#486`, **if front_matter does not have `series` tag (which the factory doesn't), then the association will just not get saved, silently.**. Took me awhile to figure out why.

To fix that, I introduced a `with_collection` transient attribute that'll allow us to pass in a collection to be associated with articles.

2) Evaluating `Time` is pretty tricky, the specs were updated but they kept failing within microseconds of difference.

A quick google around shows a workaround, which is to call either `to_i` or `to_s` before the expectation, so that's why there's some calls to `map(&:to_i)` in the code.

Happy to take any feedback!

**Comment by maestromac** [comment]
Nice job on that use of transient @edisonywh ! You could rely on our `Timecop` gem to help you out with the time. Since you don't really need to verify what value `updated_at` would be because you only need to know it changed; you could super slim down your test with the follow.
```
expect { random_article.touch }.to change { collection.articles.map(&:updated_at) }
```
If you are wondering if that really tests it, switching `:updated_at` to `:created_at` and you'll see it fails.

**Comment by edisonywh** [comment]
I was going to work on this today! Sorry for that & thanks for taking it up :)

**Pull request merged**
