### PR TITLE
Remove code for legacy mentoring feature

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

This removes the "legacy" mentoring feature code. It also removes columns in the `users` table and the `mentor_relationships` table.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
I believe the two failing tests are unrelated and probably flaky, I've tried to re-run the build but it fails nonetheless

**Comment by rhymes** [comment]
I believe the two failing tests are unrelated and probably flaky, I've tried to re-run the build but it fails nonetheless

**Comment by rhymes** [comment]
I think the failing test is just flaky, I can't reproduce it locally

**Comment by benhalpern** [comment]
I'm not sure why this test is failing

**Comment by rhymes** [comment]
@benhalpern me neither TBH. I checked if there was something related to the mentoring features but there's no such thing in the comment validators. I also can't reproduce the failure

**Comment by lightalloy** [comment]
@benhalpern @rhymes I looked into this failing test issue and found out that there could be titles like this:
```
"\n\nPour-over single-origin coffee vinegar 90&#39;s letterpress meggings flexitaria..."
```
So, the leading and trailing whitespaces are not removed and `truncate` also escapes characters by default which leads to larger `size` in some cases.
That's not related to mentorship, but a nice catch to fix in another pr.

**Pull request merged**
