### PR TITLE
Add chat channel index worker

### PR DESCRIPTION
**Pull request by wildeng**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This creates a new IndexWorker for chat channels. After the deployment I will create a new PR to remove the old job.

## Related Tickets & Documents
#5305 
## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

fingers crossed

### CODE REVIEW

**Comment by wildeng** [comment]
@mstruve I've done it!

**Comment by rhymes** [comment]
> As I look at this worker I am wondering if we even need it bc I am not seeing chat channels searched anywhere in our codebase. @rhymes, @lightalloy, or @benhalpern do you know if we actually search "SecuredChatChannel_#{Rails.env}" anywhere?

You do have a point @mstruve, it looks like we only search in the `SecuredChatChannelMembership_` and `searchables_` indexes but not in `SecuredChatChannel_`. 

The client asks the `SecuredChatChannelMembership_` channel to know whose channel the user belongs to before rendering the chat.

I think this job might safely be removed, unless I'm missing something, @benhalpern ?

**Comment by wildeng** [comment]
Just let me know if you want me to remove it  @mstruve

**Comment by mstruve** [comment]
@wildeng let's remove it! 🔪 You can close this PR and open a new one OR just rename it and push the changes here. I'm game for either! 

Thank you for going with the flow on this one! I have a feeling a lot of these job moves will be eye-openers like this one.

**Pull request closed without merging**
