### PR TITLE
Strip EXIF and GPS data from uploaded images

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

This PR strips EXIF data (including GPS data) from uploaded images.

I also added tests for all uploaders.

This PR requires `ImageMagick` to be installed both for tests and development mode.

Heroku already has ImageMagick installed

### Before

```shell
$ exiftool image.jpg | rg -i gps
GPS Latitude Ref                : North
GPS Longitude Ref               : East
GPS Altitude Ref                : Above Sea Level
GPS Time Stamp                  : 14:27:07.24
GPS Satellites                  : 06
GPS Img Direction Ref           : Unknown ()
GPS Map Datum                   : WGS-84
GPS Date Stamp                  : 2008:10:23
GPS Date/Time                   : 2008:10:23 14:27:07.24Z
GPS Latitude                    : 43 deg 28' 2.81" N
GPS Longitude                   : 11 deg 53' 6.46" E
GPS Position                    : 43 deg 28' 2.81" N, 11 deg 53' 6.46" E
```

### After upload

```shell
$ curl -O http://localhost:3000/uploads/badge/badge_image/2/image_gps_data.jpg
$ exiftool image_gps_data.jpg | rg -i GPS
```

### CODE REVIEW

**Comment by Glennmen** [comment]
Is it possible to check if ImageMagick is installed and if not don't start and trough a warning/error.

I know that in PHP you can add a requirement in your project `composer.json` file:
```json
"require": {
    "ext-imagick": "*"
  }
```

**Comment by Glennmen** [comment]
@rhymes I know from personal experience that I would easily forget to install any dependencies that are not npm/yarn or gem/composer/... related. A little warning that not all dependencies are met could save a lot of time 😉

**Comment by rhymes** [comment]
@Glennmen ahhaa that's why I've updated the installation guide :D 

maybe we could raise a runtime error in case imagemagick is not installed at startup...

**Comment by rhymes** [comment]
@maestromac they will. I was surprised too that they went through at the first attempt, I guess Travis linux images have ImageMagick :D

**Comment by rhymes** [comment]
@maestromac I fixed the conflict, I guess you have to re-review :(

**Comment by rhymes** [comment]
@maestromac imagemagick is a third party app, so I don't think so :(

**Pull request merged**
