### PR TITLE
Implement KatexTag

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
- [x] Feature

## Description
Used [katex-ruby gem](https://github.com/glebm/katex-ruby) to make a Katex Liquid Tag.

- In order to make this work, I had to turn off Redcarpet's superscripts feature. I was more comfortable with this change when I learn that Github and [Gitlab](https://docs.gitlab.com/ee/user/markdown.html#superscripts--subscripts) shared similar settings.
- I found it impossible to pass our storybook prebuild because it can't resolve `@import _katex` as that is a geminifed CSS. I've decided to copy provided CSS into our own app. I'd imagine this would help with serving up CSS for stack bit apps. If this is a bad idea please let me know.

Misc resources: 
- similar [jekyll implementation](https://github.com/linjer/jekyll-katex/blob/master/lib/jekyll/tags/katex_math_mode.rb)

## Related Tickets & Documents
Resolves https://github.com/thepracticaldev/dev.to/issues/182
Resolves https://github.com/thepracticaldev/dev.to/issues/97
## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Kapture 2020-02-21 at 16 07 15
image

## Added tests?

- [x] yes

## Added to documentation?

- [x] yes, need to add in the editor guide 

## [optional] Are there any post-deployment tasks we need to perform?
n/a

### CODE REVIEW

**Comment by maestromac** [comment]
Thanks for the suggestion @rhymes !

> what happens to existing articles that have the super script feature enabled?

Those articles generally are fine but upon resaving, it will change things like 4<sup>5</sup> to 4^5. I personally think that's an acceptable side affect easily remedied with `<sup>` tags

> I think we can manage to fix the CSS issues by doing the following things:...

Perhaps you meant to `@import '_katex';` instead of `@import '_katex';`. Sorry if I wasn't clear or I missed a step, but I was having trouble running 
`yarn run build-storybook -c app/javascript/.storybook -s app/assets` and the error still persists.

**Comment by rhymes** [comment]
> Sorry if I wasn't clear or I missed a step, but I was having trouble running
yarn run build-storybook -c app/javascript/.storybook -s app/assets and the error still persists.

Oooh, I thought in general, maybe we can ask @nickytonline to have a look at the storybook part of this. I'm going to approve it in the meantime. Tested it again, works well!

**Comment by maestromac** [comment]
⚠️ This isn't merge ready. 

The feature is ready but it breaks out storybook

**Comment by benhalpern** [comment]
@maestromac I'm concerned about the inclusion of the css for this in `LiquidTags.scss` since it's a lot of new CSS and will be in-lined on basically every page.

I think we should instead create a standalone css file which could live within the liquid tag itself. Not inline, but just a normal css file we call so that it will be cached if someone uses multiple katex on one post

This would be a divergence from our absolute norms, but I think because this will not be used super often it would be nice to co-locate the bulk with the use of the feature itself. That make sense?

**Comment by maestromac** [comment]
@benhalpern yep that makes complete sense and it might this storybook/webpacker issue we are having. I'm going to give that a try

**Comment by maestromac** [comment]
@benhalpern Liquid provide a context object that is used throughout a parsing. I use it to keep track of whether or not KateX was rendered in the prior before. If it's the first time, the CSS will be part of the render.

**Comment by nickytonline** [comment]
What's it breaking in Storybook exactly @maestromac?

**Comment by maestromac** [comment]
@nickytonline I'm not sure how but the issue resolved itself 😕 .

**Comment by nickytonline** [comment]
I think this is good to go as long as the CSS is only loaded as @benhalpern mentioned only when this liquid tag exists.

**Comment by benhalpern** [comment]
This is exciting!

Here's me adding `<h1><%= should_render_css %></h1>` to see for myself. 😄

Screen Shot 2020-03-09 at 5 57 28 PM

**Pull request merged**
