### PR TITLE
add Docker support

### PR DESCRIPTION
**Pull request by bdod**
## What type of PR is this? (check all applicable)
- [ ] Refactor
- [x] Feature
- [ ] Bug Fix

## Added to documentation?
  - [ ] docs.dev.to
  - [x] readme
  - [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
alt-text

### CODE REVIEW

**Comment by bdod** [comment]
Just run put envs to .env and run docker-commpose up -d  and wait until it started ^__^  ...

**Comment by iMerica** [comment]
Hi @bdod,

As you noticed, there is already work being done towards this effort. It's best to collaborate, rather then duplicate effort.

**Comment by benhalpern** [comment]
Yes, I'm going to close this, and feel free to help out in #296 by @iMerica.

Sorry for the extra work, but anything you went through in the process may be helpful in #296 and beyond. Thanks for the PR!

**Comment by bdod** [comment]
wasted time

**Pull request closed without merging**
