### PR TITLE
Embedded comment date alignment (issue #962)

### PR DESCRIPTION
**Pull request by Link2Twenty**
Use child combinator in .comment-date rule 

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
Stop style bleeding when embedding comments

## Related Tickets & Documents
See issue #962

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by benhalpern** [comment]
Makes sense to me, but can someone double-check this and merge it?

**Comment by benhalpern** [comment]
Hmmm this is quite funky

**Comment by Link2Twenty** [comment]
Ah, my mistake @Zhao-Andy how about changing 

https://github.com/thepracticaldev/dev.to/blob/master/app/assets/stylesheets/comments.scss#L540-L557

to 

```SCCS
  .inner-comment
    > .details{
        padding:0px;
        border-top-left-radius:3px;
        border-top-left-radius:3px;
        color:$dark-gray;
        position:relative;
        // background:$light-gray;
        .comment-date{
          border: none;
          position: absolute;
          top: calc(16px - 0.25vw);
          right: calc(35px + 0.2vw);
          font-size:12px;
          text-align:right;
          a{
            color:$medium-gray;
          }
        }
    }
```

This is the bit that is setting `.detail` to have `position:relative`

**Comment by Zhao-Andy** [comment]
@Link2Twenty I don't think the issue is with the nesting. Pretty sure the date alignment is based on the Liquid tag SCSS file I mentioned earlier. `comment.scss` is for the actual comment, and the date on regular comments do not have any issues.

**Comment by Link2Twenty** [comment]
@Zhao-Andy the style from the regular comment bleeds down to the Liquid comment, which is what causes the problem, if you have a Liquid comment in your post, as opposed to in a comment, the date looks fine.

**Comment in a post:**
https://dev.to/devteam/top-5-dev-comments-from-the-past-week-1jkl

**Comment in a comment:**
https://dev.to/ben/comment/692o

**Comment by Zhao-Andy** [comment]
@Link2Twenty sorry for the late reply. Didn't realize it was working in posts but not comments; I'll take a look again.

**Comment by Zhao-Andy** [comment]
Hey @Link2Twenty, sorry for the late reply again. Happy to review it if you'd like to reopen this!

**Pull request closed without merging**
