### PR TITLE
Internal Reports: Searching and sorting with Ransack

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR introduces the [Ransack gem](https://github.com/activerecord-hackery/ransack) to let us do search, sorting, and other cool stuff in Internal without using Algolia. Ransack can probably handle anything we're going to be doing in Internal for the foreseeable future (I think).

Also, adding this sort of functionality to our other Internal views should be pretty trivial going forward! :smile:

Assuming this gets merged, I'll follow up with some mention of Ransack in the documentation.

## Related Tickets & Documents

https://github.com/thepracticaldev/dev.to/issues/5012

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

https://www.loom.com/share/065c4478a9924e54a3cad6832cff74c0

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

external-content duckduckgo com

### CODE REVIEW

**Comment by jacobherrington** [comment]
@rhymes Adding indexes around Ransack makes sense. Especially if we expand this to other tables (like users or articles), I suspect the same functionality would be useful in those cases.

It also might valuable to see which of these searching and filtering fields are most frequently used by @michael-tharrington and @pkfrank. It may not be necessary to include all of them as options.

**Comment by jacobherrington** [comment]
Rebased to fix conflicts and removed the filter on report_type for now, since that seems superfluous.

**Comment by citizen428** [comment]
> ARel which is a really cool engine to build predicates on SQL, though it's largely undocumented since it was merged within Rails 

It's also undocumented because it's considered a private API that may have breaking changes at any point 😉

**Comment by rhymes** [comment]
@citizen428 yeah, I know, it's a pity :)

**Comment by citizen428** [comment]
Also re the actual discussion: Postgres only uses indexes for left anchored LIKE/ILIKE queries (`'%example\.com` vs `'%example\.com%`) unless we enable `pg_trgrm` and use a GIN or GIST index. Correct me if this behavior has changed in recent releases.

**Comment by jacobherrington** [comment]
For posterity: This is not working in production. Current hunch is that it has something to with Fastly, but we haven't verified that.

**Comment by rhymes** [comment]
@jacobherrington can you share some additional info if you have it?

**Pull request merged**
