### PR TITLE
Improve onboarding UI and UX (P1)

### LINKED ISSUE #6312: [P1] Implement onboarding UI updates
**Requirements**
- Implement 3d modal style
- Implement new padding
- Add overlay background

### PR DESCRIPTION
**Pull request by lisasy**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

- Introduce Crayons variables
- Remove unnecessary CSS files to have just one CSS file

## Related Tickets & Documents
Closes #6312.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
https://www.dropbox.com/s/4m7pfv3cteylba6/2020_03_23%20V1%20PR.mp4?dl=0

## Added tests?

- [x] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by vaidehijoshi** [comment]
I think we can ignore the code climate issues here; they are all JS-related, and we plan on fixing up some of the JS stuff in this cycle anyways, so it seems like that shouldn't block this PR, which is mostly just CSS changes.

**Comment by vaidehijoshi** [comment]
This PR is a continuation of https://github.com/thepracticaldev/dev.to/pull/6667, and closes  https://github.com/thepracticaldev/dev.to/issues/6312

**Comment by maestromac** [comment]
@vaidehijoshi Hmm I'm getting a different final page though
image

**Comment by vaidehijoshi** [comment]
@maestromac that looks right! better than mine :)

@lisasy mentioned that she'll file a bug for this an address it in a separate PR. since yours looks normal, i suspect that it's actually something about my setup rather than some change introduced in this PR.

**Pull request merged**
