### PR TITLE
Fixed bug with comments overlapping on IE and Edge

### PR DESCRIPTION
**Pull request by BearPro**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description

Fixed bug with overlapping comments in Microsoft Edge and Internet explorer.  
Bug occurs because `<details>` is not supported by Edge and Internet Explorer.  
_There also Opera Mini and IE Mobile (https://caniuse.com/#search=details), but I don't know how to fix it for this browsers._  
@Link2Twenty suggested simply solution in https://github.com/thepracticaldev/dev.to/issues/1593#issuecomment-455677866, I have just expanded it for Internet Explorer.

## Related Tickets & Documents

https://github.com/thepracticaldev/dev.to/issues/1593 - Comments overlapping in Edge

## Screenshots

Edge, before:
Edge - Before
Edge, after:
Edge - Afterpng

Internet Explorer, before:
IE - Before
Internet Explorer, after:
IE - After

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @BearPro, thanks a lot for this, I was wondering if you could add screenshots of the before and after for IE and Edge

Thank you!

**Comment by Link2Twenty** [comment]
> I was wondering if you could add screenshots of the before and after for IE and Edge

@BearPro has added those now @rhymes 😁

I've never seen the `_:-ms-lang(x)` CSS hack before, I'll have to remember that one. It may be worth commenting the rule to make it clear that `_:-ms-lang(x)` is, in essence, a shorthand media query.

**Comment by rhymes** [comment]
@Link2Twenty I've search for it a little bit and it seems to rely on the fact that CSS will stop parsing the rule if it doesn't recognize that trick, hence it doesn't apply to any other browser.

**Comment by rhymes** [comment]
@BearPro could you write a comment that makes it clear that `_:-ms-lang(x)` is a media query that only applies to IE11 and Edge? You'd also need to sign the CLA

Thanks!

**Comment by BearPro** [comment]
@rhymes I have used it just because I learned this feature watching this [page]( https://bl.ocks.org/feo52/raw/b6198873e0bbaeda098e4ca6f62ca887/) opened in different browsers.  
I have not theoretical basis for it.

**Comment by rhymes** [comment]
@BearPro the feature is fine, I was suggesting we could write a comment like:

```css
// this ms-lang hack (which behaves like a media query) is going to be ignored by all browsers 
// except IE and 11 and it fixes indentation on the unsupported <details> tags
_:-ms-lang(x),
.comment-deep-1,
.comment-deep-2 {
  margin-top: 0px;
}
```

to make it clearer for future readers

**Comment by maestromac** [comment]
Since all that is left is a comment adjustment, I'm going to go ahead do that and merge this.

**Pull request merged**
