### PR TITLE
db transactions for safer merging of users

### PR DESCRIPTION
**Pull request by ConSou**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Adds db transactions to allow for rollbacks if exceptions are raised.  This will guard the data against program errors or database break-downs and make for safer merging of user accounts.

## Related Tickets & Documents

#2230

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

N/A

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by jessleenyc** [comment]
@lightalloy what are your thoughts here? I had originally (dramatically) removed all callbacks because we had been running into some DJ errors and it seemed like things were deleting out of order. I think it makes sense to add some async back into all of this and I know you had created that issue for transaction.

**Comment by jessleenyc** [comment]
I've never worked w/ transactions before but would it make since to wrap the entire thing in one instead of multiple? We'd probably want to rewind if any aspect of it fails.

**Comment by lightalloy** [comment]
Hey. I'm for using methods like `update_columns`, `update_all` (that just perform SQL w/o validations and callbacks) where possible. There could be a lot of callbacks and validations which are not necessary, and they create additional app load and add too much to a transaction (there's also a space for improvement in the callbacks/validations logic).

I think database constraints should be enough here to prevent invalid values from being written to the database in this case. I added them in my pull requests - #2255 #2237

**Comment by rhymes** [comment]
What happens to the merging process if one of the transactions fails? Shouldn't the entire `merge` method be wrapped in a transaction instead of multiple sub transactions as @jessleenyc said?

One could use nested transaction / [savepoints](https://www.postgresql.org/docs/current/sql-savepoint.html) if there's a need for a more granular step by step process.

**Comment by lightalloy** [comment]
@rhymes I agree with @jessleenyc's point. Probably, ideally, all actions should be done in one transaction. I'm a bit concerned by the transaction could become too large. I haven't used `savepoint`s yet, will check them out.

**Comment by rhymes** [comment]
> @rhymes I agree with @jessleenyc's point. Probably, ideally, all actions should be done in one transaction. I'm a bit concerned by the transaction could become too large. I haven't used `savepoint`s yet, will check them out.

PostgreSQL savepoints are what Rails uses automatically when you employ [nested transactions](https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html#module-ActiveRecord::Transactions::ClassMethods-label-Nested+transactions)

There are caveats though...

**Comment by ConSou** [comment]
@jessleenyc, @rhymes  it makes sense to wrap all actions in one transaction and potentially use nested transactions for save points.  @lightalloy, I think you are right that the database constraints should be enough to prevent invalid values from being written to the database so that we can limit callbacks and validations.  I can rework some of this today and update the pull request.

**Comment by ConSou** [comment]
Hey, so a couple thoughts and things I have run into when doing more work and research on transactions.  Calling all of the methods within `merge` seem like it may be counterintuitive as it will create some anti-patterns we should look out for when using transactions.  First being some of the methods only update a single record which a transaction would not be needed for.  Another common anti-pattern I ran across is using transactions on code that won’t cause a rollback.  The `update_all` and  `update_columns` will not raise exceptions if a record is not updated correctly mean that the transaction won’t rollback and will not be of us in helping prevent issues when merging and updating the data.  Do we need a transaction on methods that won’t trigger a rollback?  In addition to this I am having a hard time figuring out how to wrap all of the methods within `merge` in a transaction block.  I am finding no examples of using it this way and when attempting to do this in a verity of ways it messes up the actual merge functionality.  If you have an idea on how this could be implemented let me know.  It seem to me that we would want to find the places where we would want a rollback triggered and where it *would* be triggered by an exception and add transactions to these sections.  Transactions act on a single database connection and limiting the amount of unnecessary code in a transaction may be beneficial.  Wrapping all methods in `merge` may not be useful as in many cases the transaction may not add any additional safety.  I’d love to hear your thoughts on all of this. @jessleenyc @rhymes @lightalloy

**Comment by rhymes** [comment]
@ConSou thanks for your thoughtul response, that's a lot of corner cases to deael with. The code is probably relying too much on side effects (aka callbacks) that become less discernible in cases like this with the peril of mass updates resulting in a thundering herd. 

What I initially meant was to wrap the entire merge merge in a transaction, for example:

```ruby
def merge
  raise "You cannot merge the same two user id#s" if @delete_user.id == @keep_user.id

  # everything inside here runs in a transaction
  ActiveRecord::Base.transaction do
    handle_identities
    merge_content
    merge_follows
    merge_chat_mentions
    merge_profile
    remove_additional_email
    update_social
    @delete_user.delete
    @keep_user.touch(:profile_updated_at)
  end

  CacheBuster.new.bust "/#{@keep_user.username}"
end
```

As you eloquently noticed though, this transaction is not fool proof for two reasons:

* `update_all` and `update_columns` go on silently even if there was an error. A workaround would be to either use the singular updates (with the risk a triggering hundreds of callbacks) or to call `valid?` on each of them separately and collect those that are not. I don't like either solution TBH :D
* there might be side effects that would make the outer transaction fail anyway

>  Do we need a transaction on methods that won’t trigger a rollback?

What happens if the transaction gets rollbacked but these rows have the columns updated? Judging by the code it shouldn't be a big deal, for example:

https://github.com/thepracticaldev/dev.to/blob/5cc1109de4f461482287185e0ce41bcbebaf14c9/app/services/moderator/merge_user.rb#L68-L71

This AFAIK means that badge achievements are moved from one user to the other, if the goal is to move everything from one user to the other, does it matter if we can't roll it back? I would say no. Because if there's something broken in the external transaction which causes it rollback, the operator is going to fix the error and then run it again, and update is idempotent in thie case: running the updates twice with the same value will result in the same result, and those badges that have already been switched over, will have been switched over to the correct user anyway.

> Transactions act on a single database connection and limiting the amount of unnecessary code in a transaction may be beneficial

Sure, in this case it might be more a matter of time of execution. I honestly have no idea how long this method runs usually but maybe @jessleenyc and @lightalloy can shed some light if needed

> Wrapping all methods in merge may not be useful as in many cases the transaction may not add any additional safety.

I think the central point here are callbacks. If callbacks have to run then we probably need a reversible transaction, if not... well maybe we only need to check if the few `update()` calls do invoke needed callbacks. If those callbacks are not needed, they can be transformed in `update_columns` as well and we don't need a transaction after all

**Comment by ConSou** [comment]
@rhymes,  thanks for getting back to me!  I appreciate your response and the clarification and thoughts on some of the topics.  When you mentions wrapping the entire merge in a transaction like your example shows this is what I initially though as well.  It makes sense that if there are any exceptions thrown for any reason with these methods the transaction would be able to assist.  The problem is that when I set up the transaction like it is in the example all tests relating to merging users fails with `ActionDispatch::Cookies::CookieOverflow:`.  While this option is still not fool proof it does add a bit of addition safety and if it is the route we want to go I can work on trying to resolve the issues with CookieOverflow.  Do you have any thoughts on this?  I agree that only using updates that trigger callbacks could easily risk triggering hundreds of them which wouldn’t be a good option either.  As you mention maybe we do only need to check some specific updates with callbacks that we want to ensure run together or not at all.  I also agree that as there are few that would invoke a callback it is also valid to discuss other options that don’t include using transactions.  I am happy to get this moving in what ever direction you feel fits this project best.  Thanks!

**Comment by lightalloy** [comment]
> `update_all` and `update_columns` will not raise exceptions if a record is not updated correctly.

If there are violations of the database constraints, an exception will be raised and the transaction will be rolled back.

> Calling all of the methods within merge seem like it may be counterintuitive

Agree, the code is not ideal, but we can't address all the issues at once.

The @rhymes' suggestion to put all the methods inside one transaction is reasonable, but we should check for the number of sql-queries (and amount of other logic) made (including the callbacks and validations).
If there's a lot, it's probably not optimal to put everything in one transaction.
Maybe it's better to have several transactions to move content step by step. Agree with @rhymes that having only some content moved from one user to another in case of an error is not a big problem.

**Comment by lightalloy** [comment]
Hey, @ConSou . Sorry for no feedback for a long time. I have revisited the problem once again. 
The current solution could work, but I'm still concerned with a large number of queries inside a transaction. There are also several `update` method calls inside the merge, which will trigger validations and callbacks, and so additional SQL queries.

What I would do for now:
- replace `update`'s with `update_column`'s.
- wrap in a transaction only the queries in the `update_social`
The other queries are not tied to each other so much, we are just moving content from one user to another. If one of the steps fails for any reason, we can repeat it later after resolving the cause of the problem. So there's no need to rollback the previous steps.

**Comment by ConSou** [comment]
@lightalloy, no worries on the delayed feedback.  I agree with you concerns about the many callbacks and think your idea on what to do for now is good.  I can get working on these changes, thanks for the feedback!

**Comment by lightalloy** [comment]
@ConSou, thanks for the changes. I would approve this pr. Could you remove the WIP if you don't plan to make other changes?

**Comment by ConSou** [comment]
@lightalloy, no problem.  I have removed WIP from the title, let me know if there is anything else!

**Pull request merged**
