### PR TITLE
Tag removal textarea changes: replaced placeholder text with improved …

### LINKED ISSUE #2001: [Feature Request] Prepopulate tag removal textbox
It might be handy to include a block of default text into the tag removal's reason box.  This could help ensure the tone is kept nice and the messages be consistent.

**Describe the solution you'd like**
This could be an example of what the text box could be pre-populated with:

> Hi. In an effort to keep dev.to's tag system as accurate as possible, I'm removing the **< TAG >** tag from your post.   **< Reason for removal - be super kind >**
>
> If you disagree regarding your tag removal, please contact yo@dev.to and explain why.
>
> 🙏 Thank you for your contribution to dev.to and I look forward to reading more articles from you.

### PR DESCRIPTION
**Pull request by davefollett**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Tag removal textarea changes:
* ~Replaced placeholder text with improved sample text~ Improved placeholder text to be clear that moderators only need to provide a reason.
* Increased height so all text shows by default

## Related Tickets & Documents
Resolves #2001 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Screenshot_20190313_231631

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by dance2die** [comment]
I love this change as the text area has been a bit too cramped IMHO.

Thanks @davefollett ~

**Comment by benhalpern** [comment]
Hmmm the `tagadjustment.html.erb` notification already contains some of this text, so this would be redundant (unless I'm missing something).

And that might not be clear to mods.

But I feel like a lot of the time this message would be about the same, so I feel like we could include a fully useable placeholder you'd only change or extend for specific cases—just to limit the mental burden of the process.

**Comment by davefollett** [comment]
I didn't realize the tag moderator's reason got wrapped with additional text, I though each moderator had to do put those kinds of things in.

I could try to switch this PR to make things more clear to the moderators or close it.  I could switch the placeholder text to something like this:

```Reason for Removal (Be super kind) - Only the reason is needed, the notification will take care of the rest.```

**Comment by jessleenyc** [comment]
@davefollett sorry about that! I didn't realize it got wrapped in more text either. I think your revised placeholder text makes sense.

**Comment by davefollett** [comment]
No problem at all, glad Ben caught it.  Here is an updated screenshot.

Screenshot_20190318_221341

**Pull request merged**
