### PR TITLE
Upgrade Rails to 5.2.3

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Inspired by https://github.com/thepracticaldev/dev.to/pull/477 I've tried to bump Rails to the latest version, 5.2.2. 

In addition to bumping Rails and its dependencies I've upgraded `act-as-taggable-on` to 6.0 as @greysteil did earlier, because it's the first version in the changelog to support Rails 5.2: https://github.com/mbleigh/acts-as-taggable-on/blob/master/CHANGELOG.md

Lastly, I ran `rails app:update` to upgrade all config files (adding also bootsnap). The update process added code for active storage, a new disabled initializer for content security policy and the framework defaults that in the future can be switched on to mimick Rails 5.2 defaults.

I'm currently, locally, fighting an error with Algolia's indexing in the tests with Rails 5.2. Upgrading Algolia's gems to the latest versions does not fix the issue.

If you have suggestions, I'm all hears.

I've also encountered a possible bug (yet to be determined) in Rails 5.2.2 and the handling of the `Cache-Control` header disallowing `public, no-cache` as a value. See https://github.com/rails/rails/issues/34780.

There's work to do to bring dev.to's source to 5.2 but I think it can be done :)

## Related Tickets & Documents

* https://github.com/thepracticaldev/dev.to/pull/477
* [Ruby on Rails 5.2 Release Notes](https://guides.rubyonrails.org/5_2_release_notes.html)
* [Upgrading from Rails 5.1 to Rails 5.2](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-1-to-rails-5-2)
* Closes https://github.com/thepracticaldev/dev.to/pull/556

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by maestromac** [comment]
This is awesome @rhymes ! Can I see what error you are experiencing with Algolia?

**Comment by rhymes** [comment]
@maestromac I ran `rspec -b ./spec/requests/chat_channel_memberships_spec.rb:15`

The short error is 

```ruby
  1) ChatChannelMemberships POST /chat_channel_memberships creates chat channel invitation
     Failure/Error: cache_name = "user-#{id}-#{updated_at}/followed_tag_names"
     
     ActiveModel::MissingAttributeError:
       missing attribute: updated_at
     # ./app/models/user.rb:264:in `cached_followed_tag_names'
     # ./app/models/user.rb:486:in `tag_list'
     # ./app/controllers/chat_channel_memberships_controller.rb:12:in `create'
     # ./spec/requests/chat_channel_memberships_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:57:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:57:in `block (2 levels) in <top (required)>'
```

The long error is here: [ccm.txt](https://github.com/thepracticaldev/dev.to/files/2712991/ccm.txt)

It's triggered by this line: https://github.com/rhymes/dev.to/blob/rhymes/rails-522/app/controllers/chat_channel_memberships_controller.rb#L12

**Comment by rhymes** [comment]
Apparently they fixed the bug I submit - https://github.com/rails/rails/issues/34780 - with this PR - https://github.com/rails/rails/pull/34885

🎉

**Comment by maestromac** [comment]
As per @rhymes , we'll wait for the next minor release of Rails 5.2

**Comment by rhymes** [comment]
@maestromac I'm giving you an update:

* the caching problem was fixed in Rails 5.2.3.rc1 (the final should be released today 27th of March, probably afternoon your time)
* the other issue unfortunately is still an issue, described here https://github.com/thepracticaldev/dev.to/pull/1408#issuecomment-450199450

If you have any ideas let me know.

A side note: the update changed `config/puma.rb` usage of `MAX_THREADS` to `RAILS_MAX_THREADS` which is the new env variable used by Rails 5.2+. This would require adding a new env variable to your Heroku's instances, otherwise we can just tell Ruby to check both env vars before booting up :)

**Comment by rhymes** [comment]
I re-ran `bundle exec rspec -b ./spec/requests/chat_channel_memberships_spec.rb:15` after having commented out https://github.com/rhymes/dev.to/blob/05132a7cc7e21c971611de9491830299fbc07c4c/app/controllers/chat_channel_memberships_controller.rb#L12-L13 and the test passed, so at least now I'm sure the issue is somewhere there.

I wonder if this [closed algoliasearch-rails issue](https://github.com/algolia/algoliasearch-rails/issues/316) has something to do with what is happening, it's a russian doll of callbacks and monkey patching, one of those few things I dislike about Rails gems :D 

I'll keep hunting the bug...

**Comment by rhymes** [comment]
Ok I've narrowed it down to this lines:

```ruby
cc = ChatChannel.last
cc.index! # this works

ccm = ChatChannelMembership.create(user_id: User.first.id, chat_channel_id: cc.id, status: "pending")
cc.index! # this breaks

ccm.destroy!
cc.index! # this works
```

Basically, indexing the `ChatChannel` after creating a pending membership breaks, it works before, it works after I destroy the membership

🤷‍♂️

**Comment by rhymes** [comment]
I think I'm close to the solution and I think an exception is masked by another one:

on master the serialization of the dynamic field `pending_users_select_fields` works correctly, with Rails 5.2.3 it doesn't.

I've narrowed it down more to https://github.com/algolia/algoliasearch-rails/blob/d389875f5c07b7e405eb0786d10f6738bff1c2f1/lib/algoliasearch-rails.rb#L173 that calls:

```ruby
Hash[attributes.map { |name, value| [name.to_s, value.call(object) ] }]
```

`attributes` is a hash of Procs, created by Algolia from the defined attributes in the `ChatChannel` model. When this method calls `value.call(object)` (object is the `ChatChannel` instance, `value` is the proc inside Algolia which in turn calls:

```ruby
  def pending_users_select_fields
    pending_users.select(:id, :username, :name)
  end
```

inside `chat_channel.rb`

On master that select produces:

`#<ActiveRecord::AssociationRelation [#<User id: 1, name: "Byron Abshire", username: "byron_abshire">]>`

ends up in the hash to be serialized and goes on with its business. On Rails 5.2.3 the same select returns a different type of object:

`#<User::ActiveRecord_AssociationRelation:0x00007fbd6f2c3b00>`

which seems to break the association. 

As a confirmation, if I remove `pending_users_select_fields` from the indexable attributes, everything works fine!!

I'm definitely close to the solution :D

**Comment by maestromac** [comment]
@rhymes 👏 how did you figure out that it needs `updated_at`?

**Comment by rhymes** [comment]
@maestromac just a hunch - I was lost in the rabbit hole of serialization/deserialization, then I went to eat something and I got the idea :D

On a related note: I think they recently changed how relationships in Algolia are supposed to work https://www.algolia.com/doc/framework-integration/rails/indexing/working-with-relationship/

**Comment by rhymes** [comment]
@maestromac Rais 5.2.3 is officially out :-)

https://weblog.rubyonrails.org/2019/3/28/Rails-5-2-3-has-been-released/

**Comment by rhymes** [comment]
Woot, woot! Thanks @maestromac - we've worked on this branch for three months :D

**Comment by maestromac** [comment]
and thank you @rhymes for pushing to the finish line!

**Pull request merged**
