### PR TITLE
Added image viewer

### PR DESCRIPTION
**Pull request by araslanov-e**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Image previewer in articles

## Related Tickets & Documents
Resolves https://github.com/thepracticaldev/dev.to/issues/413
## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by araslanov-e** [comment]
image

**Comment by araslanov-e** [comment]
Used https://github.com/imgix/luminous

**Comment by deadcoder0904** [comment]
Just a personal opinion but I like the Medium one more.

If it's not too much change, then https://github.com/francoischalifour/medium-zoom or https://github.com/spinningarrow/zoom-vanilla.js/ support Medium-style & both are vanilla js libraries :)

**Comment by araslanov-e** [comment]
@deadcoder0904 How it works with links (html tag "a")? Because on dev.to images are wrapped in links

**Comment by deadcoder0904** [comment]
@araslanov-e the first one (https://github.com/francoischalifour/medium-zoom) works i suppose. just had a quick look at the readme & found https://github.com/francoischalifour/medium-zoom#selectors which should work with any tag :)

**Comment by araslanov-e** [comment]
@deadcoder0904 I tried in https://codesandbox.io/s/github/francoischalifour/medium-zoom/tree/master/website, don't work

**Comment by deadcoder0904** [comment]
It does work, open the URL https://40ym819vjw.csb.app/ in a new window :)

**Comment by araslanov-e** [comment]
@deadcoder0904 I don't understand you. Show me, please, example with link

**Comment by deadcoder0904** [comment]
@araslanov-e it's pretty simple. i made a sandbox for u https://codesandbox.io/s/medium-zoom-vanilla-demo-dp8vr

check out `index.html` & `src/index.js` :)

**Comment by araslanov-e** [comment]
@deadcoder0904 edit example. doesn't work B)
```
<a href="https://unsplash.it/300/300">
    <img src="https://unsplash.it/300/300" alt="Unsplash Demo" />
</a>
```

**Comment by deadcoder0904** [comment]
why would anyone want to add `href="https://unsplash.it/300/300"` if it already zooms 🤔

idk why u r making this complicated. its as simple as the codesandbox.

if anyone wants to open an image they can do it using right-click>open in new tab or open image.

i really think it doesn't need to be more complicated than this :)

**Comment by araslanov-e** [comment]
@deadcoder0904 https://github.com/araslanov-e/dev.to/blob/master/app/labor/markdown_parser.rb#L225

**Comment by araslanov-e** [comment]
To use the zoom, we need to change the image display logic, this is a different modernization requiring the coordination of many interested people

**Comment by araslanov-e** [comment]
P.S. I like medium-zoom B)

**Comment by deadcoder0904** [comment]
Never did ruby but can't u just remove `href` part?

Replace

```ruby
i.swap("<a href='#{i.attr('src')}' class='article-body-image-wrapper'>#{i}</a>")
```

with

```ruby
i.swap("<a href='#' class='article-body-image-wrapper'>#{i}</a>")
```

Or something like that? And I understand it requires coordination of other people who understand both Ruby & JS. Just make it a/c to the codesandbox whoever does it :)

I think it's long overdue for dev.to :)

**Comment by araslanov-e** [comment]
@deadcoder0904 I can change anything, but such a PR may not be accepted. I need someone from the core team to evaluate. There is a problem, this will work for new articles, but links to the old ones will remain.

**Comment by araslanov-e** [comment]
@benhalpern What do you think about this?

**Comment by rhymes** [comment]
Hi @araslanov-e I fired up the branch for a spin and I've noticed a few things:

- the library is being included directly instead of being added through npm, I guess it's this one? https://www.npmjs.com/package/luminous-lightbox

- when I click it opens the image in the lightbox yes but it also opens the image in the underlying tab, without staying on the article. When I press esc I'm still on the image URL instead of the article. I think this bug defeats the purpose of this PR

- I think it doesn't play well with InstantClick. I have some weird routing issues sometimes. 

Personally I'm still not a huge fan of these lightboxes/galleries. But that's how I navigate which could be different from someone else's way.

I have literally no opinions about which library to use because I'm not familiar with them, but on a general notice it would have been great to have a public discussion (via an issue) before submitting these types of PRs. This way the team or anyone else could have chimed in on UI issues or which library would fit best for what we want to accomplish before committing down to the code.

**Comment by rhymes** [comment]
Hi @araslanov-e, we still like this feature, let us know if you're still interested in working on this or if you'd prefer to have us work on it

**Comment by araslanov-e** [comment]
@rhymes I'm interested, let's discuss

**Comment by rhymes** [comment]
@araslanov-e I think the main points here are:

- which library to use
- what's the UX like

which in a sense are the same point. 

A list of requirements:

- the library has to be maintained, added through npm and loaded asynchronously into the page
- no JS tricks on right click (the user still needs to be able to open the image's URL)
- it needs to be seamless: the user clicks, it opens the modal, the user clicks outside or presses esc and the overlay closes
- it shouldn't be too hard to customize the CSS
- it needs to work with InstantClick

**Comment by araslanov-e** [comment]
@rhymes I like medium-zoom, but need to get rid of the link wrapper

**Comment by rhymes** [comment]
@araslanov-e what link wrapper? what do you mean?

**Comment by araslanov-e** [comment]
@rhymes https://github.com/thepracticaldev/dev.to/blob/master/app/labor/markdown_parser.rb#L270

**Comment by rhymes** [comment]
Ah! I didn't even know we had that :)

**Comment by mstruve** [comment]
Hey @araslanov-e! 

Thank you so much for the PR to add this incredible feature! With that said, we are in the process of going through and cleaning up some of our PR history to help us better prioritize what we need to be focusing on. Since this PR has not been active for a while and has some conflicts I am going to close it for now. 

If you would still like to get this merged please feel free to resolve the conflicts, make the requested changes, and then open the PR back up. We would be more than happy to help push this through if you would like!

Thanks so much for being an awesome contributor! Ping us anytime if you have questions!

**Pull request closed without merging**
