### PR TITLE
Fixing alignment of save button in profile page

### PR DESCRIPTION
**Pull request by Rafi993**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This PR fixes alignment of **Save** button in the profile section in http://dev.to/settings

## Related Tickets & Documents

Closes https://github.com/thepracticaldev/dev.to/issues/7560

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

localhost_3000_settings_profile(iPhone X) (2)

## Added tests?

- [ ] yes
- [X] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
@Rafi993 thanks a lot! A tip for the future. If you write `Closes #7560` anywhere in the PR description, GitHub will automatically close the linked issue when a PR is merged. It's magic :D

**Comment by Rafi993** [comment]
> @Rafi993 thanks a lot! A tip for the future. If you write `Closes #7560` anywhere in the PR description, GitHub will automatically close the linked issue when a PR is merged. It's magic :D

Thanks @rhymes

**Comment by Rafi993** [comment]
> Works great, tested manually. Would you be willing to do the same in the other settings pages?
> 
> I see it's broken in `/ux` (also it should be named `Save` as the other pages) and `/notifications` :-/

Sure will do it

**Comment by rhymes** [comment]
> > Works great, tested manually. Would you be willing to do the same in the other settings pages?
> > I see it's broken in `/ux` (also it should be named `Save` as the other pages) and `/notifications` :-/
> 
> Sure will do it

thank you!!

**Pull request merged**
