### PR TITLE
Fix widths and add controls to <video> tag

### LINKED ISSUE #1885: <video> tag in markdown doesn't respect the blog posts container
**Describe the bug**
I crosspost all my blog posts from my personal blog and in the most recent particular post I used a lot of video tags that were not using YouTube or Vimeo.

**To Reproduce**

1. Go to https://dev.to/new and create a new post.
2. In the Markdown, add ` video tag like the one below 
```
<video controls style="max-width: 590px;">
  <source src="https://www.a11ywithlindsey.com/marcy-sutton-clapping-tweet-1fca86b197aff683ffd0a940e70e5737.mp4" type="video/mp4">
</video>
```
3. In the Front Matter, keep `published: false`, but add all necessary fields save the post so you can video the page.
4. Go to the post, and see the video. It extends past the blog post container.

**Expected behavior**
A video should have a max-width of the container. 

**Screenshots**
screen shot 2019-02-25 at 7 28 57 am

**Desktop (please complete the following information):**

- OS: Mac Mojave
- Browser: Chrome Version 72.0.3626.109
- Version: 10.14.3

### PR DESCRIPTION
**Pull request by mariocsee**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Adding max-widths to prevent videos from extending past article body and controls for non-Youtube/Vimeo sources.

Update on __Caveat__: seems like the video doesn't load for Safari either because of authorization or ~the file size I'm testing for the example~ due to unfulfilled byte range requests where the video is served. 

Update: Looks good on mobile/tablet based on Chrome. Works on Firefox as well. 

## Related Tickets & Documents
resolves #1885 

### v2 - editor -> preview -> published article
screen shot 2019-02-28 at 11 14 54
screen shot 2019-02-28 at 11 15 13
screen shot 2019-02-28 at 11 16 41

### v1 - editor -> preview -> published article
screen shot 2019-02-28 at 11 15 54
screen shot 2019-02-28 at 11 16 08
screen shot 2019-02-28 at 11 16 24

## Added to documentation?
- [x] no documentation needed

### CODE REVIEW

**Comment by Link2Twenty** [comment]
ping @Zhao-Andy @maestromac

**Comment by rhymes** [comment]
@mariocsee why did you close your reviewed and approved PR :D ?

**Comment by mariocsee** [comment]
@rhymes @Link2Twenty DEV won't be supporting the video tag it seems so I'm closing the PR

**Comment by Link2Twenty** [comment]
Oh, I didn't realise they'd said that 😕

**Comment by rhymes** [comment]
@mariocsee they didn't say that :D read this https://github.com/thepracticaldev/dev.to/issues/1885#issuecomment-467455895

**Comment by Zhao-Andy** [comment]
Hey, sorry for the silence. We decided to not support the external video embeds besides YouTube and Vimeo for now. The main reason is because we'd rather support uploads from our backend as opposed to untrusted external sources. 

We do support native video upload, and have plans to support multiple native video uploads/embeds. But for the time being, if you'd like to embed multiple videos in a single post, you'll have to use YouTube or Vimeo embeds.

**Comment by jessleenyc** [comment]
Hey @rhymes and @Zhao-Andy -- it was my mistake for approving that issue! @mariocsee is actually an apprentice on our team so when he said we said that...he meant IRL on a call earlier this week 🙈

**Comment by rhymes** [comment]
ahhahaha sorry I didn't realize either of those things 

thanks for the explanations @Zhao-Andy and @jessleenyc 

ps. congrats @mariocsee !

**Pull request closed without merging**
