### PR TITLE
On Follower page, retry on Error 429 (too many requests) #7815

### PR DESCRIPTION
**Pull request by reiallenramos**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
For every follower listed in the Followers page, there is a request to check if you are able to follow that person or not. Some of those requests fail with status 429 (too many requests), creating a label-less button. This PR will create a retry function to make sure the button has a label.

## Related Tickets & Documents
#7815 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Note: To replicate the bug, I created another account, used it to follow my main account, then displayed my only follower multiple times to trigger a lot of requests. Then in the Rails controller, I created a boolean randomizer to simulate error 429.

before:
before

after:
after

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [x] no, because I need help

Not sure which test to run in https://docs.dev.to/tests/ therefore I cant identify which specs to update.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?
none
## [optional] What gif best describes this PR or how it makes you feel?

topgun

### CODE REVIEW

**Comment by reiallenramos** [comment]
Okay I accidentally closed this PR from the dev.to app 😪 my bad

**Comment by mstruve** [comment]
@rhymes Thanks for the tag! I need to update this page to use the bulk endpoint, I didn't realize there were follow buttons on the followers page. With the bulk endpoint we shouldn't come close to reaching the limit here.

**Comment by rhymes** [comment]
> @rhymes Thanks for the tag! I need to update this page to use the bulk endpoint, I didn't realize there were follow buttons on the followers page. With the bulk endpoint we shouldn't come close to reaching the limit here.

@mstruve I learned how this page works this morning too 👀

**Comment by mstruve** [comment]
This should fix it! https://github.com/thepracticaldev/dev.to/pull/7849

With the bulk endpoint in place, the 429s should no longer be a problem. What do you think @rhymes, should we forgo complicating the logic with retries or add it anyways? I lean towards pushing out the bulk endpoint first and letting that fix it

**Comment by rhymes** [comment]
@mstruve agreed!

**Comment by mstruve** [comment]
Hey @reiallenramos, I am currently deploying the bulk fix. Would you mind verifying that the bug has been fixed and then closing this PR?

THANK YOU so much for reporting the bug and creating this PR to fix it! It's great contributors like yourself that make our job easier as open-source maintainers ❤️

**Comment by reiallenramos** [comment]
@mstruve happy to help! Checked the bug and all the buttons indeed have labels now. Although I noticed that when you reach a second "page" after scrolling all the way to the bottom, the buttons are gone entirely.

IMG_20200515_062117_262

I'll close this PR now but should I go ahead and start a new issue for ^that one or is it a known bug?

**Comment by mstruve** [comment]
Yeah feel free to open an issue for that! Thanks!

**Pull request closed without merging**
