### PR TITLE
[WIP] Change PKs and FKs from integer to bigint

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

To get "ahead of the curve" and to avoid what happened to Basecamp 3 that [ran out of integer autoincrementing primary keys](https://m.signalvnoise.com/update-on-basecamp-3-being-stuck-in-read-only-as-of-nov-8-9-22am-cst-c41df1a58352) I am submitting this PR to upgrade all integer PKs to [bigint](https://www.postgresql.org/docs/9.1/datatype-numeric.html) (signed 8 bytes). 

Rails defaults to bigints since the end of 2016: https://github.com/rails/rails/pull/26266

Some tables in the database, like `badge_achievements`, `badges`, `buffer_updates`, `events` and others, already default to bigint. 

I've also changed the integer ids in referenced tables to bigints

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by benhalpern** [comment]
I like this PR. I'm nervous that this migration could stall. This definitely has to be merged with care.

Note to self:
Before running this migration, we'll need to modify relevant timeout time and likely run this in a detached Heroku process.

**Comment by rhymes** [comment]
@benhalpern you could also setup a clone of production, run the migration on that and see what happens.

**Comment by rhymes** [comment]
Hi @benhalpern, I just rebased the PR :-)

**Comment by benhalpern** [comment]
Hey @rhymes, haven't forgotten about this, and we'll give this some focus to get it merged shortly.

**Comment by rhymes** [comment]
@benhalpern don't worry, thanks! Let me know if you want me to rebase it at some point

**Comment by rhymes** [comment]
I feel I fell victim of the classic "random test error that has nothing to do with your PR and when you run it locally, the test passes"

**Comment by Zhao-Andy** [comment]
Based on the failed test, would also agree with that sentiment @rhymes 😅 Rerunning the CI now.

**Comment by rhymes** [comment]
@benhalpern @Zhao-Andy any thoughts on finalizing this? Have you had a chance to review it and test it?

Thank you!

**Comment by benhalpern** [comment]
Hey @rhymes, can you open another PR that makes a smaller migration. Maybe just `change_column :articles, :id, :bigint`

And then depending on how that goes, we could run this all at once or break it up further?

**Comment by benhalpern** [comment]
I think this will probably be pretty seamless, but I just want to be safe and sound unless I have 100% conviction otherwise.

**Comment by rhymes** [comment]
good idea! i'll do it tomorrow, and after that we can break the PR down table by table or something like that. thanks!

**Comment by rhymes** [comment]
@benhalpern a question: did you manage to previously test the PR on a copy of the DB?

I just wanted to make you aware that changing the column type will require locking the table because it's essentially a rewrite. If the table contains a significant amount of rows (usually in the order of tens of millions, though I don't think it's the case for `articles` yet) it could end up in downtime for the site. These operations are always a drag :-)

From [PostgreSQL 9.6 doc](https://www.postgresql.org/docs/9.6/sql-altertable.html#AEN76108):

> Adding a column with a DEFAULT clause or changing the type of an existing column will require the entire table and its indexes to be rewritten. As an exception when changing the type of an existing column, if the USING clause does not change the column contents and the old type is either binary coercible to the new type or an unconstrained domain over the new type, a table rewrite is not needed; but any indexes on the affected columns must still be rebuilt. Adding or removing a system oid column also requires rewriting the entire table. Table and/or index rebuilds may take a significant amount of time for a large table; and will temporarily require as much as double the disk space.

I'd also double check the [heroku vacuum settings](https://devcenter.heroku.com/articles/managing-vacuum-on-heroku-postgres) and if needed run vacuum manually on the single table after the migration is run.

In the meantime I'll send a PR just for `articles.id` and we go from there.

**Comment by benhalpern** [comment]
Hey @rhymes, we're going to just move this as an in-house item to remove confusion about this feature. We're definitely clear on how to do it but handling this via async has just been tough, so we're going to close this.

Of course, we very much value the contribution!

**Pull request closed without merging**
