### PR TITLE
Automated DEV setup using Gitpod

### PR DESCRIPTION
**Pull request by jankeromnes**
👋 Hello!

I work on gitpod.io, a one-click online IDE for GitHub, and I'd like to contribute an almost fully-automated dev setup for DEV. ⚡️

Please let me know what you think.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [x] Documentation Update

## Description

In this PR, I've configured Gitpod to:
- pre-install PostgreSQL and the correct Ruby version (via `.gitpod.dockerfile`)
- initialize DEV workspaces with a `config/application.yml` and run `bin/setup`
- automatically start `bin/startup` and open the app in a preview

Here is what it looks like:

[Open in Gitpod](https://gitpod.io/#https://github.com/jankeromnes/dev.to)
Screenshot 2019-04-07 at 15 00 01

## Related Tickets & Documents

(none)

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

The only non-automated part are the Algolia credentials, which Gitpod will ask for on startup like so:

Screenshot 2019-04-07 at 14 55 54

## Added to documentation?

- [ ] docs.dev.to
- [x] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

frictionless coding

### CODE REVIEW

**Comment by nickytonline** [comment]
This looks very cool. Like codesandbox.io with a backend. Just loaded it up, but I'm on mobile and don't have my api keys handy. Will check this out more later.

**Comment by benhalpern** [comment]
This is absolutely amazing, I've been dreaming of making this happen.

@jankeromnes just sign the CLA and this is good to go.

**Comment by jankeromnes** [comment]
Thanks @nickytonline and @benhalpern! CLA signed :)

**Comment by jankeromnes** [comment]
Hi VimalRaj Selvam,

> could not connect to server: Connection refused
> Is the server running on host "localhost" (::1) and accepting
> TCP/IP connections on port 5432?

Oops, this looks like the PostgreSQL server isn't running. It should
automatically start on every session, but you can easily verify whether
it's running:

```bash
$ pg_ctl status
# pg_ctl: server is running (PID: 654)
```

And if not, you can start it like so:

```bash
$ pg_start
```

**Pull request merged**
