### PR TITLE
Added lazy loading for iframes

### LINKED ISSUE #4671: Add loading="lazy" to all liquid iframes
[Native lazy loading](https://dev.to/yashints/native-lazy-loading-is-landed-in-chrome-2kli) is a thing for iframes and images. We went in and added it to a bunch of images, but not yet for iframes.

Any iframes we use should have this attribute added, as all of them qualify as valid for lazy loading in order to help the user experience.

Some tests may need to be updated.

### PR DESCRIPTION
**Pull request by rohan-techfreak**
## What type of PR is this? (check all applicable)

- [ ] Bug Fix

## Description
It resolves the issue raised #4671 

## Related Tickets & Documents
Fixes #4671 
## Added to documentation?

- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by maestromac** [comment]
Hello @rohan-techfreak , If you run `approvals verify` after running our test on your machine (ie `bin/rails rspec rspec /spec/liquid_tags/`) , you'll be prompted with approval fixtures to update.

**Comment by maestromac** [comment]
Hello @rohan-techfreak , the commit history of this PR is out of order. I'd recommend the following steps to fix it.

1. on this very branch `git reset --hard b5e3b4fcf4417207b4ac927e9c4e60c98201020e`
2. pull-down latest on your master then merge master to this branch `git merge master`
3. force push up the work here. There should only be 2-4 commits to this branch with changes only reflecting your work

alternatively, let me know if you would like me to do it for you

**Comment by benhalpern** [comment]
Hey @maestromac @rohan-techfreak I think this was my fault with the commits. I went to push a small change because I wasn't sure the status and introduced this problem. I didn't realize until right now that I'd made this mistake. My bad.

**Comment by maestromac** [comment]
Oh no worries, if that's the case i'll go ahead and undo that change

**Pull request merged**
