### PR TITLE
Fix cloudinary helper

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
We use this custom view helper `cloudinary` which broke when we shifted to requiring strict signing on the backend. This fixes it.

It's kind of a hot fix in that it doesn't preserve _all_ the logic, but this isn't used much and I think the old logic wasn't entirely necessary.

### CODE REVIEW

**Comment by mstruve** [comment]
Do we still need this? Can you point to the error this has caused in Honeybadger to give some more insight?

**Comment by rhymes** [comment]
@benhalpern @mstruve 

would this fix be related to this issue? https://github.com/thepracticaldev/dev.to/issues/7991

**Comment by mstruve** [comment]
Good question...

Few duplicates of that issue @rhymes we should cleanup https://github.com/thepracticaldev/dev.to/issues/7889
https://github.com/thepracticaldev/dev.to/issues/6595

**Comment by atsmith813** [comment]
Good call @mstruve, let's see if that fixes it 💯

**Pull request merged**
