### PR TITLE
Move from env variables to SiteConfig

### PR DESCRIPTION
**Pull request by citizen428**
What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR only deals with the first remaining part outlined in #5384, starting to use existing SiteConfig keys instead of the env variables

## Related Tickets & Documents

[Migrate from ENV vars to SiteConfig](https://github.com/thepracticaldev/dev.to/issues/5384)

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

n/a

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

@rhymes Requested you as reviewer, since you did most of the original work from what I saw.

### CODE REVIEW

**Comment by citizen428** [comment]
Related question: there are quite a few places left where the Twitter account is directly references as "@ThePracticalDev", e.g.

```html
<meta name="twitter:site" content="@ThePracticalDev">
```

Should we change them to 

```erb
<meta name="twitter:site" content="@<%= SiteConfig.social_networks_handle %>">
```

as part of this PR?

**Comment by rhymes** [comment]
Could this PR be split in separate PRs? I fear it's too risky of a move to switch _all_ environment variables in one go

**Comment by citizen428** [comment]
It could definitely be done, but would involved a bit of work on my end. Would this time potentially be better spent on increasing text coverage for areas you are nervous about?

I understand the concern, but despite the huge number of changes, this is essentially just text replacement and I *did* verify that all of the methods exist on `SiteConfig`.

**Comment by rhymes** [comment]
@citizen428 ok let's keep it like this, the PR looks fine!

Can you undo the change in the Envfile? This way we can have a separate PR to remove those and @mstruve can remove the unneeded variables on Heroku separately

**Comment by citizen428** [comment]
I restored the `Envfile` to its original version.

**Comment by benhalpern** [comment]
I think it should be fine to do all of this at once.  @mstruve and myself should do this synchronously and be ready to roll back if there are defects.

The risks that @rhymes brings up are definitely valid if there's anything we're missing, but I think this is a pretty safe rollback if there are problems.

**Pull request merged**
