### PR TITLE
[#339] fixed broken markup on /readinglist page

### PR DESCRIPTION
**Pull request by markfrst**
## What type of PR is this? (check all applicable)
- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Added to documentation?
  - [ ] docs.dev.to
  - [ ] readme
  - [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
alt-text

### CODE REVIEW

**Comment by maestromac** [comment]
Thanks for this pr @markfrst ! Can you please kindly provide a before & after sreenshot of your UI change?

**Comment by markfrst** [comment]
@maestromac you can look here https://github.com/thepracticaldev/dev.to/issues/339#issuecomment-415952149

**Comment by markfrst** [comment]
👍

**Comment by benhalpern** [comment]
At the time of this PR, I originally thought we'd be faster to provide a different solution which would alleviate this more generally.

Since that clearly never happened, this PR wins!

**Pull request merged**
