### PR TITLE
Enable hyphens in tags

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Solves #2347 

Though I'm not sure if this is the solution we've decided to go with, it seemed super easy to just add it and we can close the PR if it's not the best solution.

I believe this should not be merged until #3895 is merged (assuming that either of these PRs should be merged).

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Screenshot_2019-09-02 test

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by jacobherrington** [comment]
Rebased to fix the conflicts after #3895! This should be good for review. 🤠

**Comment by jacobherrington** [comment]
Thanks @maestromac, should be good now! Fairly rudimentary change, but it should work.

Is there any plan to phase the V1 editor out, or will if be supported indefinitely? I think the v2 editor is a little rough around the edges for the time being, but I'm just curious.

**Comment by maestromac** [comment]
@jacobherrington  no, we don't plan to phase out V1 editor. V2 editor is definitely a little rough right now 😅 . There are a few more things that need to be straighten out for both of the editor's output to be identical.

one last thing, can you please update the failing specs?

**Comment by jacobherrington** [comment]
I'll fix the tests, but I'm interested in seeing the discussion on #2347.

**Comment by jacobherrington** [comment]
@Zhao-Andy Updated the tests, and that's a good call. I'd love to see some discussion. Personally, I think it's a good idea! 🤠

**Pull request closed without merging**
