### PR TITLE
Fixed .rspec - require rails_helper

### PR DESCRIPTION
**Pull request by araslanov-e**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Fixed .rspec - used require rails_helper

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
@araslanov-e can you describe the rationale behind this PR :) ? Thank you!

**Comment by araslanov-e** [comment]
@rhymes LGTM B)

**Comment by rhymes** [comment]
@araslanov-e sorry, I don't understand what you mean. What I'm asking is what prompted you to submit it. I'm not saying is wrong or right, just asking your thought process :)

(BTW there's a conflict)

**Comment by katafrakt** [comment]
I don't think this is a good change. This way every spec will require `rails_helper`. Unlike `spec_helper`, `rails_helper` is really heavy to load. Additionally, many specs do not (or should not) require whole Rails stack to be run. Having Rails required everywhere encourages developer to write specs carelessly.

**Comment by araslanov-e** [comment]
@rhymes Sorry, the last time I wrote a test, out of habit, I did not add rails_helper and the test crashed, and decided to fix it so that no one would think about it in the future

**Comment by araslanov-e** [comment]
@katafrakt I thought about it and looked through all the files, and rails_helper is used everywhere, so I decided to make

**Comment by katafrakt** [comment]
Ok, then it's up to maintainers I guess. I would advise against it anyway and perhaps tried to make some tests operate only on `spec_helper`, but it's their call.

**Comment by rhymes** [comment]
Hi @katafrakt, you raise a great point and our test code could benefit for some improvement (for design and speed reasons).

Right now all test effectively include `rails_helper.rb` which includes `spec_helper.rb`.

@araslanov-e thanks for explaning why you did this, it makes the PR quite clearer, I thought there was a bug somewhere.

I'm personally not in favor of changing the explicitness of the require, especially if in the future we can find a way to split those helpers in multiple smaller ones that will be required by file which need only the code inside each separate helper.

Pinging @maestromac which probably has a different take on all of this than I do

**Comment by maestromac** [comment]
Thank you for this PR @araslanov-e 

I completely understand the justification behind this PR. Similar to what @rhymes stated, the eventual plan we have is to follow a similar approach [Gitlab is doing](https://docs.gitlab.com/ee/development/testing_guide/best_practices.html#fast-unit-tests); offering multiple helpers depending on a test's need, which makes the explicit `require` on each file conducive to that goal.

And on `RSpec.describe` vs `describe`, I'm uncertain if [these benefits](https://stackoverflow.com/a/27832744/5494108) still apply but I'd prefer to keep it there to be explicit and to [disable monekypatching](https://github.com/rubocop-hq/rubocop-rspec#enforcing-an-explicit-rspec-receiver-for-top-level-methods-disabling-monkey-patching)

We appreciate all the contributions you've done so far @araslanov-e . I'm sorry to close this after you've spent the time creating it. For changes like this, It would helpful if is proposed as an issue first for discussion.

**Pull request closed without merging**
