### PR TITLE
Remove unused onboarding files

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

This is primarily the removal of some files that don't seem to be in use. As far as I can tell, the files I'm removing aren't being used in onboarding. It seems like they were ported into the Onboarding pack, but not deleted. Please correct me if I am misunderstanding.

This also includes a few ESLint motivated changes to the onboarding files that are actually in use.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

proxy duckduckgo com

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @jacobherrington, just a note, I think this PR would have conflicts somehow with https://github.com/thepracticaldev/dev.to/pull/4240, I quickly parsed both and there's seem some overlapping work on similar set of files. Can you take a look and maybe coordinate with the other one?

**Comment by jacobherrington** [comment]
@rhymes If that PR is good to go we can merge it and I will deal with the conflicts in my branch. 👍

**Comment by rhymes** [comment]
@jacobherrington I think it needs reviewing, we haven't gone over it yet

**Comment by jacobherrington** [comment]
@rhymes I will review that PR first thing tomorrow. This PR needs the snapshots updated before it should be reviewed anyway 😅

**Comment by rhymes** [comment]
@jacobherrington I think some specs are failing because they are importing files that have been removed :) Let me know when that's corrected and I'll double check everything, thanks!

**Pull request merged**
