### PR TITLE
feat: add per-user Open Dyslexic font setting

### PR DESCRIPTION
**Pull request by codebytere**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

This PR adds a new user-customizable font, [OpenDyslexic](https://en.wikipedia.org/wiki/OpenDyslexic), to `/settings/misc`.  OpenDyslexic is a typeface designed against some common symptoms of dyslexia; it will allow for users of Dev.to to more easily read posts and thus serves to improve general accessibility of Dev.to.

## Related Tickets & Documents

Closes https://github.com/thepracticaldev/dev.to/issues/5036.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Screen Shot 2019-12-08 at 1 21 50 PM

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by benhalpern** [comment]
This is exciting. I think we will likely need s lightly different import approach, but let me gather my thoughts and give better direction here.

**Comment by codebytere** [comment]
Awesome! I tried to follow existing conventions as best i could but i'm happy to approach this in whatever direction you feel is best for maintainability/consistency/etc :)

**Comment by jacobherrington** [comment]
Really excited to see this move forward. This is a great idea! :clap:

**Comment by benhalpern** [comment]
@codebytere I'll close the loop on this in the next few days. No further actions required from you, I'll figure out the little things to get this working.

**Comment by benhalpern** [comment]
And to be clear, @codebytere, you followed conventions really well. It's just a few elements of uncharted territory with importing a font in this way we need to figure out, and I have some time to get to that now. 🙂

**Comment by codebytere** [comment]
no worries! i'll rebase this soon, i saw yall's great update to the ux settings page ⭐️

**Comment by benhalpern** [comment]
@codebytere I pushed some changes here, and it's good to go as far as I can tell. I'll wait for other folks from the team to double check next week.

Thanks for opening the issue @bnb

Can't wait to get this into prod!

**Pull request merged**
