### PR TITLE
Return 404 NotFound error if @moderatable Is Not Found instead of failing with 500

### LINKED ISSUE #5791: Return 404 NotFound error if @moderatable Is Not Found
In the event that an article can't be found, we should exit this action early and return a 404 not found error rather than trying and failing to continue to load necessary models. 
Honeybadger: https://app.honeybadger.io/fault/66984/184d0d115e69e18889765fd6ffd15d6a
Error:
```
NoMethodError: undefined method `id' for nil:NilClass
moderations_controller.rb  22 article(...)
[PROJECT_ROOT]/app/controllers/moderations_controller.rb:22:in `article'
20     @moderatable = Article.find_by(slug: params[:slug])
21     @tag_moderator_tags = Tag.with_role(:tag_moderator, current_user)
22     @adjustments = TagAdjustment.where(article_id: @moderatable.id)
23     @already_adjusted_tags = @adjustments.map(&:tag_name).join(", ")
24     @allowed_to_adjust = @moderatable.class.name == "Article" && (current_user.has_role?(:super_admin) || @tag_moderator_tags.any
```

ApplicationController has a handy `not_found` method that you can use to do this. I think you will want to implement a solution similar [to this one](https://github.com/thepracticaldev/dev.to/pull/5646/files#diff-cae59de326d9d5bfb471bb23bbd25c1fR62).

### PR DESCRIPTION
**Pull request by Zeko369**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

closes #5791 

## Description
Return 404 for not found when @moderatable is not found, instead of failing with 500 when calling id on it later

## What gif best describes this PR or how it makes you feel?

Me adding a ! and fixing bugs

When you fix a bug just by adding "!", tnx DHH

### CODE REVIEW

**Comment by Zeko369** [comment]
@rhymes Hey, could you also review this PR

**Comment by rhymes** [comment]
Hi @Zeko369, sorry for the late reply, I think before accepting this we should find a way to add a test for it, what do you think?

**Comment by Zeko369** [comment]
There are no tests for #article and #comment. Should I create a separate PR for adding those specs @rhymes ?

**Comment by rhymes** [comment]
@Zeko369, it'd be great if you could add a spec related to this change in this PR! :-)

Thank you!

**Comment by mstruve** [comment]
Fixed via https://github.com/thepracticaldev/dev.to/pull/5999

**Pull request closed without merging**
