### PR TITLE
Remove Audit::SaveToPersistentStorageJob and Save Inline

### PR DESCRIPTION
**Pull request by mstruve**
## What type of PR is this? (check all applicable)
- [x] Refactor
- [x] Optimization ?

## Description
When looking at this job to move it over to Sidekiq I realized we were doing a lot of work to serialize and deserialize this event object to simply just save it in the database. Since the AuditLog only has a single validation and is a small object, creating a new one should be very fast. I also saw that we have 30 of these in our database so it doesn't happen often. Given these facts I think this is fine to do inline and remove the added complexity and overhead of enqueueing a job. Anyone have thoughts on that?

## Related Tickets & Documents
#5305 

## Added to documentation?
- [x] no documentation needed

alt_text

### CODE REVIEW

**Comment by lightalloy** [comment]
I believe it was done for future scaling. As I remember, this change was implemented by @brarnaudovski

**Comment by rhymes** [comment]
Now that I think about it, if we plan to start using this feature on all or most actions in the internal panel, as it was intended I believe, we might as well keep the job and move it over in the lowest priority queue, this way we don't have to dig it up again

**Comment by mstruve** [comment]
Seeing as its a simple SQL create I still think unless we are doing thousands of these at a time moving it to a job is a bit of a premature optimization.

**Comment by rhymes** [comment]
Good point!

**Pull request merged**
