### PR TITLE
Add file argument to Stackblitz embed.

### LINKED ISSUE #2589: Stackblitz Embed with Specific File
**Is your feature request related to a problem? Please describe.**
As a writer I'd like to be able to focus my Stackbliz embeds on a specific file to most clearly exemplify the code that I may be describing.

**Describe the solution you'd like**
I would like to be able to use the embed code with an additional parameter `{% stackblitz vanilla-portal view=editor file=portal-destination.js %}`

While the API in https://github.com/thepracticaldev/dev.to/blob/master/app/liquid_tags/stackblitz_tag.rb is a bit out of my personal specialities, it seems pretty straight forward to add another set of tests to add `def parse_file(input)` and `def valid_file?(option)` in order to support this.

**Describe alternatives you've considered**
The ability to make my own `<iframe/>`s, but that's both arduous and possibly dangerous in a security manner.

### PR DESCRIPTION
**Pull request by Westbrook**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Add support for the `file` argument in Stackblitz embeds.

## Related Tickets & Documents
fixes #2589

## Added to documentation?

- [ ] docs.dev.to
- [x] readme
- [ ] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
I think Code Climate is complaining because, at a glance, `parse_file` and `parse_view` are literally doing the same thing.

I think you meant to call `valid_file` inside `parse_file`, which now it's never called.

I don't think Travis noticed because there are no tests for that condition.

If I may, you could refactor the duplication with:

```ruby
def parse_input(input, validator)
  input_split = input.split(" ")

  # Validation
  validated_views = input_split.map { |o| validator.call(o) }.reject(&:nil?)
  raise StandardError, "Invalid Options" unless validated_views.length.between?(0, 1)

  validated_views.length.zero? ? "" : "&#{validated_views.join("")}"
end

# and in the initialize you call 
@view = parse_input(input, self.method(:valid_view?))
@file = parse_input(input, self.method(:valid_file?))
```

**Comment by Westbrook** [comment]
Thanks @rhymes wasn't sure how to do that in Ruby! Hopefully Code Climate's happy now, too.

**Comment by rhymes** [comment]
> Thanks @rhymes wasn't sure how to do that in Ruby! Hopefully Code Climate's happy now, too.

Thank you! I think it is now complaining about the rendundant `self` (my bad) and the string quoting 😅

**Comment by Westbrook** [comment]
Seems happy now. Hopefully
```
    @view = parse_input(input, valid_view?)
    @file = parse_input(input, valid_file?)
````
is actually what it wanted.

**Comment by rhymes** [comment]
> Seems happy now. Hopefully
> 
> ```
>     @view = parse_input(input, valid_view?)
>     @file = parse_input(input, valid_file?)
> ```
> 
> is actually what it wanted.

Did you run the tests? :-)

```ruby
parse_input(input, valid_view?)
```

should be:

```ruby
parse_input(input, method(:valid_view?))
```

without the `self.`, not without `self.method`

almost there heeh

**Comment by Westbrook** [comment]
@rhymes If you had any suggestions around the test coverage, I'd be happy to take those as well. I'm not much of a Ruby dev, so I'm confused why the additions that I made in that area aren't getting the coverage up to where it's being asked to be.

**Comment by rhymes** [comment]
@Westbrook

if we ignore Code Climate for a second you'll see the tests are failing because the first argument to `parse_input` should be `id`, like in the previous code.

If you check here: https://travis-ci.com/thepracticaldev/dev.to/builds/109958477 - you'll see that Ruby can't find the variable "input", but the actual variable should be named `id` which is the argument of the initializer

**Comment by Westbrook** [comment]
Ah, good call. I was looking at the test coverage %s and didn't even see that. Hopefully, this solves both problems.

**Comment by Westbrook** [comment]
Let me now if there is anything I can do to move this along. I've already built the data for this into some of my posts, and it would be really awesome to see this addition therein.

**Pull request merged**
