### PR TITLE
Fixes Github Liquid Tag alignment in notifications page

### PR DESCRIPTION
**Pull request by artoodeeto**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
Github liquid tag header goes out of its parent element
## Related Tickets & Documents
Resolves https://github.com/thepracticaldev/dev.to/issues/3661
## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
**Before**
Screen Shot 2019-10-06 at 9 36 57 AM

**After**
Screen Shot 2019-10-06 at 1 03 13 PM

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
shy-type

### CODE REVIEW

**Comment by artoodeeto** [comment]
this might be a dumb commit because I just comment the code out. I tested it in every liquid tag and every browser and every screen size I have no idea what it is used for or what it is offsetting from but I feel like its being used somewhere so I just comment it out, also I run the test just to get familiar with the workflow, but it didn't pass. This is the error `rspec ./spec/system/user_views_a_reading_list_spec.rb:14` should I fix this here on the same issue or make another one? also found a new bug and an error message directly from ruby.

**Comment by rhymes** [comment]
@artoodeeto I've updated the description of the issue to make it clearer, especially to the casual reader. I've also re-triggered this build because that test failure is unrelated to the CSS change. In general, let's keep unrelated fixes in separate PRs

**Comment by artoodeeto** [comment]
@rhymes thank you for reviewing. I will change it as soon as I get back from work. thanks :)

**Comment by artoodeeto** [comment]
@rhymes hello, I removed the margin. should I close this after it'll be the reviewer?

**Pull request merged**
