### PR TITLE
Change error styling from syntax highlighting for a better UI in all themes

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This fixes a bug we have in syntax highlighting where lines that are marked as an error from the parser are not easiliy readable in the two dark modes:

Screenshot_2020-02-10 Test syntax highlighting dark mode(1)

I followed @benhalpern suggestion to actually remove the styling: https://github.com/thepracticaldev/dev.to/pull/4669#issuecomment-548408741

Disclaimer: there's a PR that was started by a contributor https://github.com/thepracticaldev/dev.to/pull/4669 - but as the contributor has seemingly abandoned it (they haven't responded to it for more than 2 months). I also tried to commit to "takeover" the PR but I'm not allowed to commit to it

## Related Tickets & Documents

- closes https://github.com/thepracticaldev/dev.to/issues/4577
- supersedes https://github.com/thepracticaldev/dev.to/pull/4669

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

This is how it looks now in the two dark modes:

Screenshot_2020-02-10 Test syntax highlighting dark mode(2)

Screenshot_2020-02-10 Test syntax highlighting dark mode(3)

### CODE REVIEW

**Comment by ludwiczakpawel** [comment]
From code point of view it's obviously all good :) 

But I agree with @nickytonline - it's really good suggestion, especially the 2nd option.

**Comment by rhymes** [comment]
I'm not a fan of either option because we can't distinguish between an actual error (as me typing JavaScript into a CSS block) from errors of unsupported features (highlighters are definitely slower to update than the languages they highlight). That was probably Ben's reason to leave error lines as they weren't highlighted at all.

But I'm not firm on this position, so @ludwiczakpawel @nickytonline, if you an the color codes that look nice for both the night theme and the 10x theme, let's do it!

**Comment by ludwiczakpawel** [comment]
@rhymes actually why are you saying this is an issue only on dark themes? i think code blocks (including code highlighting) look exactly the same no matter what theme, right? so we don't need to choose color which looks good on both: light & dark - since these are the same.

anyyyyywayyy... im not sure what the ideal is. to me, error is an error - should be highlighted. but i see your point about highlighters being not up-to-date...

What about wavy underlining but not applying any color to the text itself?
```css
text-decoration-line: underline;
text-decoration-style: wavy;
text-decoration-color: rgba(255, 0, 0, 0.75);
text-decoration-skip-ink: none;
```

^ this would look like:

image

It's not ideal though because of the spaces..

---

Okey, here's another weird idea :D . 

```css
text-shadow: 0 0 3px #ff3030, 0 0 5px #ff3030, 0 0 10px #ff3030;
```

...and the result:

image

(this one in fact is slightly better supported in browsers)

**Comment by rhymes** [comment]
@ludwiczakpawel you're right.

I've applied `text-shadow: 0 0 3px #ff3030, 0 0 5px #ff3030, 0 0 10px #ff3030;`

Screenshot_2020-02-11 Test syntax highlighting dark mode

**Pull request merged**
