### PR TITLE
add anchor links to each heading in editor guide

### LINKED ISSUE #4507: 🌈 Feature Request: Add linkable "id" to each Editor Guide section headers
### Description
Add an "id" field on each header section in the [Editor Guide](https://dev.to/p/editor_guide).

### Issue

We can't refer to a specific section in the Editor Guide because there is no "id" field to link to for headers on https://dev.to/p/editor_guide.

issue

### Example case

e.g.) https://dev.to/dance2die/comment/gmj3

I requested user to `Editor Guide/Video Embed`, which will take the reader to the top of https://dev.to/p/editor_guide, not the "Video Embed" section.

## Describe the solution you'd like

Gatsby documentation page adds a clickable "anchor" as shown below.  
URL shown below - https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/

gatsby documentation

## Describe alternatives you've considered

As adding an anchor could increase the DOM size, we can simply embed, "id" in the header without adding `<a href="..."/>`.

## Additional context

Posts have "id" fields generated automatically for ToC. #682

### PR DESCRIPTION
**Pull request by shindakun**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Went with a normal anchor tag rather than just adding `id=` to the `h3` tags, this is similar to how it's done in articles currently. No need to dupe the CSS this way.

Example:

```
        <a name="jsfiddle_embed" href="#jsfiddle_embed" class="anchor"></a>
        <h3><strong>JSFiddle Embed</strong></h3>
```

## Related Tickets & Documents

closes #4507

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

finish

### CODE REVIEW

**Comment by rhymes** [comment]
The only problem I see with this is that to figure out the anchor one has to look at the code and that the titles are not clickable...

**Comment by shindakun** [comment]
@rhymes I was considering adding a link icon to click on but didn't want to get into messing with the CSS lol. I'll take a closer look at it this evening and see what changes might need to be made to add that.

**Comment by Zhao-Andy** [comment]
If you don't get to adding a link icon -- personally tried doing it the first time around with the anchors and the CSS was not fun -- I think a table of contents at the top with the links would suffice?

**Comment by mstruve** [comment]
Hi @shindakun!
 
Thank you very much for the feature PR! Currently, we are in the process of going through and cleaning up some of our PR history to help us better prioritize what we need to be focusing on. Since this PR has not been active for a while and has a conflict I am going to go ahead and close it for now. If you would still like to get this merged please feel free to resolve the conflict and then open the PR back up. We would be more than happy to help you push this through if you would like!

Thank you so much for contributing! Ping us anytime if you have questions!

**Pull request closed without merging**
