### PR TITLE
Users API: fix characters in user.summary of who to follow 

### LINKED ISSUE #4650: HTML Character References shown in "who to follow"
**Describe the bug**
The "Who to follow" box displays escaped HTML character references.

**To Reproduce**

1. Sign up for a new account
2. Agree to the T&Cs
3. Scroll through the list of people to follow.

**Expected behavior**
Instead of `&#39;` display the apostrophe symbol. Instead of `&quot;,` show the quote symbol.

**Screenshots**
Screen Shot 2019-10-29 at 16 37 12
Screen Shot 2019-10-29 at 16 36 38

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Version: 78

### PR DESCRIPTION
**Pull request by korczynsk1**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description

Fixing bug which was noticed on #4650 .
Bug was created by truncate method. Here is more details https://stackoverflow.com/a/18665289.
 
## Related Tickets & Documents
Fixes #4650 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

image

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## What gif best describes this PR or how it makes you feel?
Alt Text

### CODE REVIEW

**Comment by rhymes** [comment]
@korczynsk1 also don't forget to sign the CLA once you're done (or even before that :D)

**Comment by korczynsk1** [comment]
@rhymes CLA accepted but I don't have no longer possibility to create these tests. Can you participate?

**Comment by rhymes** [comment]
@korczynsk1 for clarity, are you authorizing me to take over this PR and bring it to completion? Thank you

**Comment by citizen428** [comment]
@rhymes What should we do with this PR, as it's been stalled for a while and I think the original author indicated that they will no longer be able to work on it? Also I don't think it actually is related to the linked issue, as this PR makes sure we don't truncate multi-byte characters in the middle, whereas the issue seems related to not marking text with HTML entities as `html_safe`.

**Comment by citizen428** [comment]
As discussed with @rhymes on Slack, closing this as the original author can no longer work on it.

**Pull request closed without merging**
