### PR TITLE
Fix problem vulns brakeman

### PR DESCRIPTION
**Pull request by jeann2013**
## What type of PR is this? (check all applicable)
- [ ] Refactor
- [ ] Feature
- [ x] Bug Fix
- [ ] Documentation Update

## Description
Fix vulns to according Brakeman

### CODE REVIEW

**Comment by Angelicachris321** [comment]
I don’t understand

**Comment by jeann2013** [comment]
According to https://github.com/thepracticaldev/dev.to/issues/511, I ran Brakeman and find many Hight errors, I fixed this errors, look the issues

**Comment by benhalpern** [comment]
Thanks a lot for this. Since this was not user-generated content we sort of let these brakeman issues sit, but thanks for implementing some better practices. Will review the PR more closely after the weekend.

**Comment by jeann2013** [comment]
New fixed for vuln weak in Brakeman

**Comment by jessleenyc** [comment]
Hey @jeann2013, thanks for submitting this. Since we let this sit a little too long, and there are a few merge conflicts, we're going to close this issue. If you'd like to take another go at it, please create an issue first so we can all discuss together! Thanks again.

**Pull request closed without merging**
