### PR TITLE
Improve the clarity of the docs and fix Prettier config

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Documentation Update

## Description

I started working on this Saturday evening after getting past a small blocker @maestromac and I were working on Friday afternoon. I'm going to go ahead and wrap this up as a PR even though there is plenty of work left to do on these docs because it's late and it's the weekend :smile: :+1: 

I do think this change is self-contained enough to be valuable as a PR as-is, and I will wait for some future downtime to continue editing the docs for clarity.

This PR does change quite a bit of copy in a few files, but the change I expect to be controversial is a formatting change that I made in most of the files: linewrapping at 80 characters. The number 80 is arbitrary and it's just the number the VS code extension I was using defaults to, but my reasoning for this change is explained in the commit message :point_down: 

While this change produces a lot of git noise by enacting what seems
like an arbitrary linewrap on most of the files in the documentation it
will result in better version control and tracking of the changes in the
documentation.

For example, as it currently stands, if one was to make a
PR to move a comma in a sentence because each paragraph in most of the
files is on a single line, that small change would look in the git
history like the author had modified the entire paragraph. In reality,
this author just moved a comma.

This change also includes a significant number of modifications to the
more article-esque docs. Many of these docs were written in a sort of
stream-of-consciousness and aren't as easy to read as they could be.
Hopefully this is the first of several readability changes. If we could
get these docs to a more accessible reading level, we would probably see
an increase in contributions. :)

## Added to documentation?

- [x] docs.dev.to
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Unrolling a long scroll

### CODE REVIEW

**Comment by jacobherrington** [comment]
To be completely honest, I should have done this in (at least) two commits: copy-editing and formatting. That would have made it more clear what copy I changed versus the files that I just added linewrapping, but I didn't intend to do the linewrapping until I noticed how the current format was hamstringing the git history.

**Comment by nickytonline** [comment]
Prettier handles markdown formatting on precommit.

See https://github.com/thepracticaldev/dev.to/blob/master/package.json#L41-L45

**Comment by jacobherrington** [comment]
@nickytonline Great callout!

I will update that value to include an auto wrap. I was using another VS Code extension for this, but it's a much better idea to have prettier help with formatting markdown.

**Comment by jacobherrington** [comment]
@nickytonline It looks like [this line](https://github.com/thepracticaldev/dev.to/blob/master/package.json#L41-L44) was missing the [--prose-wrap](https://prettier.io/docs/en/options.html#prose-wrap) option, which defaults to `preserve` accroding to [this issue](https://github.com/prettier/prettier/issues/5123).

**Comment by jacobherrington** [comment]
@benhalpern do we need to get reviews on this agin, or is it okay to merge? The merge from master added a single line from another PR I made.

Would prefer to get this merged sooner rather than later so that managing conflicts doesn't become an issue. :+1:

**Comment by benhalpern** [comment]
Merged!

> do we need to get reviews on this again, or is it okay to merge? The merge from master added a single line from another PR I made.

> Would prefer to get this merged sooner rather than later so that managing conflicts doesn't become an issue. 👍

@jacobherrington Use your judgment in this case and feel free to merge when it's had eyes on it you feel it's low-risk and appropriate. So yeah, you could have merged this. 👍

**Pull request merged**
