### PR TITLE
Fix linting issues in app/views/videos

### PR DESCRIPTION
**Pull request by Glennmen**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
All linting errors have been fixed.

~~Stil 1 linting error that I wasn't sure how to fix:~~
```
Avoid using "text/x-tmpl" as type for `<script>` tag. Must be one of: text/javascript (or no type attribute).
In file: app/views/videos/new.html.erb:25
```

## Related Tickets & Documents
#1842 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by Glennmen** [comment]
Maybe this can solve the open linting error: https://github.com/Shopify/erb-lint/blob/master/README.md#allowedscripttype

**Comment by lightalloy** [comment]
I'm not sure about the `script` issue. Maybe @benhalpern is aware of this?

**Comment by maestromac** [comment]
@Glennmen What/which script issue are you referring to?

**Comment by Glennmen** [comment]
@maestromac I was getting this linting error:
```
Avoid using "text/x-tmpl" as type for `<script>` tag. Must be one of: text/javascript (or no type attribute).
In file: app/views/videos/new.html.erb:25
```

**Comment by benhalpern** [comment]
Yeah, this is a functional signal for jQuery based on how this library is written. It's designed to not trying to interpret the inner contents of the script as JS.

https://github.com/waynehoover/s3_direct_upload

So it looks like adjusting the linting rules or messing around with some of the alternate approaches for this lib is the way to go.

All in all, replacing this library with something else is the longterm approach we need. See this issue:
https://github.com/thepracticaldev/dev.to/issues/293

**Comment by lightalloy** [comment]
@Glennmen, For now, you can add this code to the `linters` section of the `.erb-lint.yml` file:
```
  AllowedScriptType:
    enabled: true
    allowed_types:
      - 'text/javascript'
      - 'text/x-tmpl'
    allow_blank: true
    disallow_inline_scripts: false
```

**Pull request merged**
