### PR TITLE
Fixed the overflowing user name in the top bar under profile thumbnail

### PR DESCRIPTION
**Pull request by grv19**
## What type of PR is this? (check all applicable)
- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
screen shot 2018-09-04 at 9 27 01 pm

- [ ] Documentation Update

## Description
If the user name is too long it flows out of the div tag. I've just added the break-word to fix this.
## Added to documentation?
  - [ ] docs.dev.to
  - [ ] readme
  - [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
alt-text

### CODE REVIEW

**Comment by benhalpern** [comment]
Looks good to me @grv19. Can you sign the CLA and then we can merge?

**Comment by Gaurav-Shankar** [comment]
Signed! :)

**Comment by Gaurav-Shankar** [comment]
@Zhao-Andy @benhalpern  How do i get the contributor badge on dev.to now ?

**Comment by maestromac** [comment]
Hey @Gaurav-Shankar , I believe you just received it.

**Pull request merged**
