### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by AdamLombard**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Fix minor indentation issue, per RuboCop and Code Climate

## Related Tickets & Documents
n/a

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
n/a

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

First time contributing here, and hoping I did it right, so...
here goes nothing...

### CODE REVIEW

**Comment by benhalpern** [comment]
Thanks a lot for this, but looks like I _just_ fixed this myself 😳
https://github.com/thepracticaldev/dev.to/pull/906/files

**Comment by AdamLombard** [comment]
I saw that an instant before you messaged. 😂 
Other than my terrible timing, was that the right way to help out on the Code Climate refactors?

**Comment by maestromac** [comment]
Hey @AdamLombard , yep that is the right way to help out with any form of refactor.

**Comment by AdamLombard** [comment]
Thanks, @maestromac!

**Pull request closed without merging**
