### PR TITLE
Update i18n copy

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

There is a bit of subjectivity in this PR, but the ultimate goal is to move content from static pages into i18n so that it is easy to customize the content and add new translations for those pages.

These commits could be squashed depending on preference.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

There might be a follow-up PR explaining how to add new translations, but I'm not sure if that's necessary unless this PR is merged.

## [optional] What gif best describes this PR or how it makes you feel?

Ms. Doubtfire using a broom as an air guitar

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @jacobherrington, thanks for this PR!

While going through the description and the PR code itself I was thinking that this would have been a perfect case of a PR in need of a previous discussion.

i18n, while an understandable and agreeable goal for everyone, always has nuances and possible different approaches.

In this case I'm not entirely sure a quick win is a "win" at all, I'll explain my thoughts on this.

At the present moment as you might have noticed there's no internal framework for i18n. The are no translations and the file for english contains less than a dozen keys. So effectively we can start from scratch. 

Having the luxury to start from scratch means that we can give a little bit of thought on how we want to proceed and how to setup i18n. Do we want to just use the default Rails support or something more? Do we want to put all keys in a single file (not personally a fan of that because it becomes unmaintanable super fast) or have multiple files with a structure? How do we namespace keys? Should we have tooling that helps us keeping track of these trees of keys and handle obsolete keys or duplicate ones? Which locales should we officially support other than English, if any? Should there be parts of the website always in English? What about design issues in case of different text lengths? Should the whole copy of an entire page be a single key or should it be broken in paragraphs?

These and probably other questions could lead to a more comprehensive solution supported by the community with our help as maintainers.

I'm not convinced that just moving the content of static pages in the translation is going to help maintenance at the present moment, since there's nothing else which could just add burden to the contributor that has to edit the translation file containing multiple strings instead of just editing the file containing the text. 

Hope all of this makes sense.

**Comment by jacobherrington** [comment]
@rhymes, I agree! 😃👍 Thanks for your thoughtful feedback, I totally understand your perspective and want to make the best decision for this project.

Let's have that conversation now; I'd love to hear your opinions on how this could be implemented more intelligently and in a way that doesn't require undue support.

This PR was motivated by a few things: language accessibility, maintainability, and customization.

**Language Accessibility and Maintainability**

I'm less concerned with ease of maintenance with this change and more concerned with the potential for language localization and felt that the static pages were the best place to begin testing an approach.

When it comes to keys, I agree with most of the points you made, but I'm ignorant when it comes to tooling/techniques to help us with maintaining these YAML files; I'd love some suggestions.

Personally, I'd like to see most of the content (excluding UGC) in the application wrapped in i18n even if there is no specific goal to support another language at the moment because it is much easier to establish a pattern early than retrofit an application with support for other languages. 

Also, due to the Open Source nature of this project, implementing an i18n framework allows native speakers to add translations if they'd like to have them -- much like the [ruby-lang site](https://github.com/ruby/www.ruby-lang.org) or https://github.com/solidusio/solidus_i18n. Later, if sufficiently skilled speakers are willing, the project can choose to support a language officially.

In terms of accessibility, a little is better than nothing... I think, right?

**Customization**

I also see this as a step towards the idea mentioned in [Self hosting DEV](https://docs.dev.to/self-hosting/). People who want to host an instance of the application might be able to take advantage of an i18n framework to swap content out easily, for example, if they have their own preferred CoC or want to change the text on the about page without writing too much code.

Further features around i18n would need to be built, but doing some work around i18n now would be a step in that direction.

Ultimately, as I mentioned earlier, it would probably be better to lay a foundation for g11n/i18n now. To your point, we need to make sure we are laying the right foundation now. I'd love to hear your thoughts on how I can align this PR with your perspective on this kind of feature.

If we determine closing this PR is the best course of action, I don't see it as wasted effort because it allowed me to get more familiar with the project, which was all I intended to do when I made this change.

**Comment by rhymes** [comment]
@jacobherrington would you be willing to open a separate issue starting with your thoughtful comment up here? There are better chances of it having a successful outcome than by burying the conversation under a PR that people might or might not see. It's also easier to link on DEV in case you want to open a conversation there as well.

I'll definitely engage and hopefully others will too, after that.

Regarding this PR I'd probably close it for now, I think it'll become clearer how to proceed once we have some solid discussions under our belts and if needed we can revisit this or start anew

**Comment by jacobherrington** [comment]
Closing this PR to continue the conversation in #3929.

**Pull request closed without merging**
