### PR TITLE
Move exporting into a job

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

I've moved the exporter logic into a proper active job like @lightalloy is doing for the rest of the async logic.

This should also help understand/evade export requests. I've been currently waiting for more than a week for an export and I suspect it has something to do with the default queue delayed job uses for jobs created with `.delay`.

## Related Tickets & Documents

It possibly sheds some light for https://github.com/thepracticaldev/dev.to/issues/2031

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Those two failing tests don't fail on local 🧐

**Comment by maestromac** [comment]
You are right. I ran the test locally and it passed. Let me try to rerun this.

**Comment by rhymes** [comment]
> _Something is rotten in the state of Denmark_ 😂

**Comment by lightalloy** [comment]
@rhymes @maestromac If the test is run individually, it passes, but if I run the whole test suite, the test fails (same as on the CI).

**Comment by lightalloy** [comment]
I suppose there's some inconsistency in setting `ActiveJob::Base.queue_adapter` setting (`:inline` or `:test`). For the `export_requested` flag it should  be `:test`. 
As we move to `ActiveJob` the `run_background_jobs_immediately` in tests should be replaced with `ActiveJob::Base.queue_adapter = :inline`  where applicable:

https://github.com/thepracticaldev/dev.to/blob/7ade3380027d4ff3a5f22476bf9ae6d1dba43d26/spec/requests/user_settings_spec.rb#L101-L111

**Comment by rhymes** [comment]
@lightalloy thank you! I'll fix it shortly

**Comment by rhymes** [comment]
BTW @lightalloy  do you agree on my hypothesis about what's going on with the old export jobs created with `delay` or `handle_asynchronous` ? Is the default queue on your end backed up or too big?

**Comment by rhymes** [comment]
Shouldn't `config/environments/test.rb` be setting 

```ruby
config.active_job.queue_adapter = :test
```

I thought all tests were running with the test adapter, not the one used by default

**Comment by lightalloy** [comment]
@rhymes not sure, need more research on this. I tried adding `before { ActiveJob::Base.queue_adapter = :test }` and the test passed. This may need additional checks.

>  Is the default queue on your end backed up or too big?
I don't have access to the production data, will pass the question to the team.

**Comment by rhymes** [comment]
> @rhymes not sure, need more research on this. I tried adding `before { ActiveJob::Base.queue_adapter = :test }` and the test passed. This may need additional checks.

Yeah, now Travis fails for an unrelated test but it worked! I'll investigate into setting the queue_adapter by default as test in a separate test once this is merged.

Thanks for the help!

**Pull request merged**
