### PR TITLE
Fixed article stories in Storybook

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Storybook stories for Articles got messed up at some point. Not sure when. Styles were all off.

To see these changes, check out the latest [deployed Storybook](https://devto-storybook.now.sh).

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Before

image

image

image

image

After

image

image

image

image

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Red Hot Chili Peppers on the Simpsons. Flea says, "Wow! That's much better. Everyone can enjoy that."

### CODE REVIEW

**Comment by fdoxyz** [comment]
@nickytonline silly question: In order to try these out locally do you run `npm run storybook`?

With this I'm getting "blank results" for some reason (also see the `?path=/story/undefined` in the URL). I'm not able to see these like they show in https://devto-storybook.now.sh/

Screen Shot 2020-05-15 at 09 59 00

**Comment by nickytonline** [comment]
> @nickytonline silly question: In order to try these out locally do you run `npm run storybook`?
> 
> With this I'm getting "blank results" for some reason (also see the `?path=/story/undefined` in the URL). I'm not able to see these like they show in [devto-storybook.now.sh](https://devto-storybook.now.sh/)
> 
> Screen Shot 2020-05-15 at 09 59 00

@fdoxyz, hmm... odd. `yarn storybook` or `npm run storybook` should run Storybook and you shouldn't be receiving the message "No preview available".

When I run one of those commands and go to Article -> default, this is what I see.

image

Your storybook looks very out of date. Maybe it's a browser caching issue. Can you do a hard refresh?

**Comment by fdoxyz** [comment]
Pretty odd indeed, I ran `bin/setup` again to make sure everything is updated. This is my output when doing `yarn storybook`. Are we on Storybook `5.3.18`?

Screen Shot 2020-05-15 at 10 26 10

After doing a hard refresh I see a card but the left sidebar still has no content 🤔
(also showing some warnings in dev tools)

Screen Shot 2020-05-15 at 10 27 47

Tried Safari too but same result. This may be something very dumb I'm overlooking but just can't figure out what exactly 😳

**Comment by nickytonline** [comment]
> Pretty odd indeed, I ran `bin/setup` again to make sure everything is updated. This is my output when doing `yarn storybook`. Are we on Storybook `5.3.18`?
> 
> 
> After doing a hard refresh I see a card but the left sidebar still has no content 🤔
> 
> (also showing some warnings in dev tools)
> 
> 
> Tried Safari too but same result. This may be something very dumb I'm overlooking but just can't figure out what exactly 😳

The Storybook version is right, but it’s still showing the Storybook stories how they looked almost two months ago.

I’ve even deployed the latest Storybook which is based off this PR, https://devto-storybook.now.sh .

**Comment by fdoxyz** [comment]
Yeah, at least I'm pretty sure I'm on the right branch 😂

Screen Shot 2020-05-15 at 10 50 14

I'll continue to try working this out, if any one else approves I'll reach out to you directly later on to see If I can find a way to fix this

**Comment by nickytonline** [comment]
> Yeah, at least I'm pretty sure I'm on the right branch 😂
> 
> Screen Shot 2020-05-15 at 10 50 14
> 
> I'll continue to try working this out, if any one else approves I'll reach out to you directly later on to see If I can find a way to fix this

@fdoxyz, try doing a `git clean -dfx` (ensure you have your application config backed up somewhere) and then run `yarn` or `npm install` followed by `yarn storybook` or `npm run storybook`.

I've found cleaning your git when you've been switching branches fixes weird issues like this.

**Pull request merged**
