### PR TITLE
Removed frequency - query with INNER JOIN and COUNT

### PR DESCRIPTION
**Pull request by araslanov-e**
## What type of PR is this? (check all applicable)
- [x] Refactor
- [ ] Feature
- [ ] Bug Fix

## Description
One query instead map, sort_by.

## Added to documentation?
  - [ ] docs.dev.to
  - [ ] readme
  - [x] no documentation needed

### CODE REVIEW

**Comment by benhalpern** [comment]
I like this, but it does call into question what we we're actually doing with the "service" naming. We could stand to standardize on some conventions in this regard.

**Comment by araslanov-e** [comment]
@benhalpern may be method move to Comment (model)?

**Comment by araslanov-e** [comment]
@maestromac what about this?

**Comment by maestromac** [comment]
I tested in my development and I am getting this error

```
ActiveRecord::StatementInvalid at /internal/dogfood
PG::GroupingError: ERROR:  column "users.username" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT users.username, COUNT(comments.user_id) AS number_of_...
               ^
: SELECT users.username, COUNT(comments.user_id) AS number_of_comments FROM "comments" INNER JOIN "users" ON "users"."id" = "comments"."user_id" WHERE "comments"."user_id" IN (2, 1, 41) AND ("comments"."created_at" > '2018-08-29 19:36:09.360605') GROUP BY "comments"."user_id" ORDER BY number_of_comments DESC
```

**Comment by araslanov-e** [comment]
@maestromac try again

**Pull request merged**
