### PR TITLE
Add mini_racer and switch to sassc-rails

### LINKED ISSUE #7383: Running a single system test is very slow (takes over 40 seconds)
**Is your feature request related to a problem? Please describe.**

I worked on a PR and wrote some system tests. Running a single system test takes 40-50 seconds.

I'm willing to investigate why it's so slow, and potentially fixing it.

**Describe the solution you'd like**

A system test taking ~5 seconds would be great.

**Describe alternatives you've considered**

CI is great, but immediate feedback is often needed.

**Additional context**

```
$time ./bin/rspec spec/system/articles/user_creates_an_article_spec.rb
DEPRECATION WARNING: Default values will be removed in the next minor-release of ENVied (i.e. > v0.9). For more info see https://gitlab.com/envied/envied/tree/0-9-releases#defaults. (called from block in load at /home/ledestin/work/dev.to/Envfile:4)
[Zonebie] Setting timezone: ZONEBIE_TZ="Chatham Is."
..

Finished in 1 minute 0.74 seconds (files took 8.82 seconds to load)
2 examples, 0 failures

Coverage report generated for RSpec to /home/ledestin/work/dev.to/coverage. 2723 / 15816 LOC (17.22%) covered.

real    1m12.136s
user    1m8.128s
sys     0m7.584s
```

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Optimization

## Description

Based on the discussion in #7383 I experimented with mini_racer and sassc to speed up our *system specs*, especially running single ones in isolation. 

See [relevant comment 1](https://github.com/thepracticaldev/dev.to/issues/7383#issuecomment-618288345) and [relevant comment 2](https://github.com/thepracticaldev/dev.to/issues/7383#issuecomment-618291113).

Results:

```
current: 
  Run 1: Finished in 59.24 seconds (files took 21.55 seconds to load)
  Run 2: Finished in 1 minute 4.24 seconds (files took 16.61 seconds to load)
  Run 3: Finished in 56.66 seconds (files took 15.89 seconds to load)

with mini_racer: 
  Run 1: Finished in 24.47 seconds (files took 15.08 seconds to load)
  Run 2: Finished in 28.25 seconds (files took 16.36 seconds to load)
  Run 3: Finished in 27.76 seconds (files took 14.19 seconds to load)

with mini_racer + sassc
  Run 1: Finished in 18.54 seconds (files took 8.12 seconds to load)
  Run 2: Finished in 21.73 seconds (files took 10.9 seconds to load)
  Run 3: Finished in 22.46 seconds (files took 11.27 seconds to load)
```

## Related Tickets & Documents

Closes #7383

## Added tests?

- [X] no, because they aren't needed

## Added to documentation?

- [X] no documentation needed

### CODE REVIEW

**Comment by mstruve** [comment]
What were you running to get those run times? I just tried running model specs on master and this branch and got the same run times for both. I want to make sure we are comparing apples to apples.

**Comment by citizen428** [comment]
@mstruve You won't see a difference for model tests, as this is specifically for system specs as the issue discussed. I'll update the PR description.

**Comment by rhymes** [comment]
I can't run all system tests together (they always break or freeze on my machine) so I can't be sure, I tried to run a couple of files (ran 3 times each, took the best timing):

**master**

```shell
Finished in 58.41 seconds (files took 12.11 seconds to load)
26 examples, 0 failures
50.92s user 10.78s system 72.55s real 492132kB mem -- rspec spec/system/authentication
```

**branch**

```shell
Finished in 28.67 seconds (files took 13.97 seconds to load)
26 examples, 0 failures
28.80s user 6.87s system 44.61s real 580820kB mem -- rspec spec/system/authentication
```

I'd say the difference is noticeable :D 

ps. I rebased on master as the count of test was different between the two branches

**Comment by citizen428** [comment]
> I  can't run all system tests together (they always break or freeze on my machine) 

Interesting, this happens to me too. Maybe something to investigate during the next downtime.

**Comment by citizen428** [comment]
I'll mark this as ready for review now. Note that this only affects system tests and will show the biggest benefit when running single tests in isolation.

**Pull request merged**
