### PR TITLE
Refactor ProfileImage

### PR DESCRIPTION
**Pull request by seb1441**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
As suggested by @citizen428, here's the minor refactor to go from `ProfileImage.new.get(150)` to `ProfileImage.new.get(width: 150)`. This makes the `get` method more explicit on what it actually does and also allows later, if needed, to easily add more optional arguments like `height`.

## Related Tickets & Documents
https://github.com/thepracticaldev/dev.to/pull/5583#discussion_r369931445

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by mstruve** [comment]
Shoot, we waited a little too long on this! @seb1441 any chance you can resolve the conflict that we have? Or maybe @rhymes can do it quickly since he is very familiar with those API builders.

**Comment by rhymes** [comment]
For some reason, probably permissions, I can't resolve this conflict:

Screenshot_2020-02-07 Refactor ProfileImage by seb1441 · Pull Request #5803 · thepracticaldev dev to

I rebased the branch manually to see where the conflict was and the issue is that `
app/views/api/v0/users/me.json.jbuilder` does not exist anymore in `master`.

**Comment by seb1441** [comment]
@rhymes Thank you for the steps, it worked perfectly. Weird that you had permissions issues. When I create PR's, I always check the box to let the maintainers have access to my repo. Maybe because the permissions are only on the branch related and not the master branch?

@mstruve Conflict fixed!

**Comment by rhymes** [comment]
@seb1441 it looks like there are a few broken specs this time around https://travis-ci.com/thepracticaldev/dev.to/builds/147858632 - likely new specs using the old signature, that entered with the rebase :)

**Comment by seb1441** [comment]
@rhymes Newly added tests fixed :)

**Pull request merged**
