### PR TITLE
Enable viewport scaling for a11y

### LINKED ISSUE #1214: A11y: User Scalable
**Describe the bug**
Currently, users are not able to zoom in on content, if a user has poor eyesight they may not be able to use the sight without this.

https://github.com/thepracticaldev/dev.to/blob/1b60ee50091caf0d190e15f66b3771e0e9fb84cb/app/views/layouts/application.html.erb#L59
```HTML
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
**Expected behaviour**
A user should be able to zoom in.

**Additional context**
Another accessibility issue and another simple fix so again, a good first issues.

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description

Lighthouse signalled that the viewport should not disable zooming using `user-scalable`.

More information on [Zooming and scaling must not be disabled (2x)](https://dequeuniversity.com/rules/axe/2.2/meta-viewport):

> Remove the user-scalable=no parameter from the content attribute of the <meta name="viewport"> element in order to allow zooming and ensure the maximum-scale parameter is not less than 2.

and [Quick tip: Never use maximum-scale=1.0](https://a11yproject.com/posts/never-use-maximum-scale/):

> By setting maximum-scale=1.0, you are disabling the functionality to use pinch zoom on certain mobile devices, forcing people to view your page a certain way.

This will affect the iOS experience, though maybe we can set a `maximum-scale` to something higher than 1 if that's needed. From [MDN section on Viewport width and screen width](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag#Viewport_width_and_screen_width):

>  If web developers want their scale settings to remain consistent when switching orientations on the iPhone, they must add a maximum-scale value to prevent this zooming, which has the sometimes-unwanted side effect of preventing users from zooming in: `<meta name="viewport" content="initial-scale=1, maximum-scale=1">`

## Related Tickets & Documents

Closes #1214 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by rhymes** [comment]
@Link2Twenty maybe you have suggestions about this :)

**Comment by Link2Twenty** [comment]
reference #1214

**Comment by Link2Twenty** [comment]
@benhalpern didn't want to implement this if it meant losing the app feel. But was open to persuasion.

**Comment by benhalpern** [comment]
I'm thinking now that we can let the native app itself dictate this behavior. (Described [here](https://medium.com/@maxcampolo/making-javascript-feel-like-native-ios-with-wkwebview-d92dfefe8d56) how to do it).

So yeah, we can lose the constraint on the web and then let the native apps themselves determine how they want to treat the app "feeling native".

Let's hold off on merging until we make the native-side change on iOS. I know it's not a cut and dry argument, but _feeling native_ via the webviews is important IMO—and the device has specific a11y functionality to help from there.

Someone want to make the issue and/or PR on the native side?

https://github.com/thepracticaldev/DEV-ios

@maestromac as you work on Android, you can keep this in mind, but since that's newer don't think of this as an important day 1 issue.

P.S. In general I feel like welcoming some of us web devs to try hacking on the native side of things.

**Pull request merged**
