### PR TITLE
[SMALL] UX: Rename "Start an ask me anything" to "Start an AMA"

### PR DESCRIPTION
**Pull request by venarius**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
I randomly noticed the "Start an ask me anything" button and found that it looked very squished. I increased its width.

### Before
Screenshot from 2019-04-13 22-17-10

### After
Screenshot from 2019-04-13 22-19-55

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by maestromac** [comment]
Which browser are you using? 

With Chrome 73 I don't notice this issue. It might have something to do with the front.

**Comment by abraham** [comment]
I have Chrome 74 on Ubuntu and have the issue with all the font options available in settings.

Screenshot from 2019-04-16 16-11-57

**Comment by venarius** [comment]
yup, same. It have the same issue on ubuntu and chrome

**Comment by benhalpern** [comment]
Having thought about this, I don't think the button should be meaningfully bigger. How about we change the text here to "START AN AMA" instead?

The font problem is that helvetica-condensed is not compatible across all browsers. We should explore other ideas related to how we deal with fonts across the site. I'm still pretty happy that we don't load in heavy external fonts.

**Comment by venarius** [comment]
@benhalpern sounds like a good idea, but I don't think a greater button width would have done harm here. Just force-pushed with the change you suggested.

**Pull request merged**
