### PR TITLE
Fix stale fuzzy timestamps on notifications

### PR DESCRIPTION
**Pull request by kaspermeyer**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
Fuzzy timestamps on cached notifications are now being displayed correctly.

**Implementation details:**

Instead of using the `time_ago_in_words` Rails helper, timestamps are now being rendered dynamically with JavaScript.

Timestamps are stored in a `data` attribute on the element. When paired with the `time-ago-indicator-initial-placeholder` class it works as an anchor for the `insertTimes()` JavaScript helper. It replaces the element with a fuzzy timestamp generated by `timeAgo()`.

**This fix changes the existing implementation in a couple of ways:**
* The styling is a bit different now due to the nature of the `insertTimes()` helper. It replaces the element (originally a `<small>` element) with a `<span>` element.
(_see screenshots below_)
* Comment notifications aren't cached at the moment, but since post and comment notifications can be viewed alongside each other on the "ALL" menu option, I replaced them as well for consistency.
* The `timeAgo()` helper doesn't render timestamps older than 24 hours by default.
(_see screenshots below_)

Let me know if these issues need to be dealt with in some way ✌️ 

## Related Tickets & Documents
Fixes issue #3548

Other related issues: #2997 and #3183 

### Style changes
_Before_
timeago_before
_After_
timeago_after

### Notifications older than 24 hours
_Before_
24_hours_before
_After_
24_hours_after

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @kaspermeyer, thanks for the PR! I've see you've gone the hardest route :D I would have worked on caching :D

A few things:

- it's a little weird we're relying on an initializer meant for articles for this behavior, it might make future refactoring more complicated. The frontend code right now is not very well organized but I see there's an [initNotifications.js](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/initializers/initNotifications.js) that can be used, I would add a custom function there. This way you don't need to use `time-ago-indicator-initial-placeholder`. I think it's cool that the styling will be consistent to the list of articles in the home page

- [timeAgo](https://github.com/thepracticaldev/dev.to/blob/4689cdd266e7e678511e733d24c719d9f89948cd/app/assets/javascripts/utilities/timeAgo.js#L28) is admittedly an odd function in that it doesn't return a value but an entire element. BTW I noticed it takes a second argument that is how far back it can go, I think you can trick it with `timeAgo(seconds, -Infinity)` to always return a value.

- if you look at [initNotifications.js](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/initializers/initNotifications.js) you'll notice there's some business logic called on pagination, we probably need to make sure that when triggered the `time ago in words`  logic gets recalled for the new notifications that are appended

:)

**Comment by kaspermeyer** [comment]
Thank you so much for getting back to me that fast—and for all of the pointers! That’ll be a big help when I get back to the keyboard 👨‍💻

I’m glad you caught the pagination issue, that definitely needs to be handled as well!

By working on caching, do you mean remove caching altogether like on comment notifications? Admittedly, that would’ve been easier but I was a bit worried about the performance implications it would have.

I won’t mind doing this over if we decide the old solution with a `time_ago_in_words` and a cache fix is the better way to go, but I can see some benefits by continuing down this path of handling fuzzy timestamps with JavaScript more consistently across the site. Then we won’t have to worry so much about stale caches.

Let me know what you think 🙂

**Comment by rhymes** [comment]
> By working on caching, do you mean remove caching altogether like on comment notifications? Admittedly, that would’ve been easier but I was a bit worried about the performance implications it would have.

No, not removing it altogether, finding a better caching strategy, but I'd like to discuss this with the team and get back to you

> but I can see some benefits by continuing down this path of handling fuzzy timestamps with JavaScript more consistently across the site. Then we won’t have to worry so much about stale caches.

I agree, there's that advantage, but I feel that having both the partial cache and the JS to rewrite the "time ago" it's not the perfect solution. I like that with this PR both the articles index and the notifications index behave the same way

**Comment by kaspermeyer** [comment]
Sure, that sounds good! Get back to me, and I'll put in the work on whatever solution gets decided on 🙂 

I thought about different caching strategies, but since the `time_ago_in_words` hard-codes the fuzzy timestamp in the template, I couldn't see any other solution than invalidating the cache constantly, rendering it useless. But maybe I'm missing something here. I look forward to see what come up with! ✌️

**Comment by rhymes** [comment]
I'm closing this because by removing the cache in https://github.com/thepracticaldev/dev.to/pull/4122 the behavior should have disappeared, maybe in the future we could switch to client side rendering (which has to take into account pagination and eventually i18n)

**Pull request closed without merging**
