### PR TITLE
Remove correct tag when deselecting on listings page

### PR DESCRIPTION
**Pull request by majakomel**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
onClick event was triggered twice - on wrapper <a> element and enclosed `x`

## Related Tickets & Documents
Closes https://github.com/thepracticaldev/dev.to/issues/7514
Closes https://github.com/thepracticaldev/dev.to/issues/7499

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
I think I opened a duplicate issue :-( This should also fix https://github.com/thepracticaldev/dev.to/issues/7499, right?

**Comment by msarit** [comment]
@majakomel Looks like you have a conflict Maja 😄

**Comment by majakomel** [comment]
@rhymes Whoops, the same issue is described in https://github.com/thepracticaldev/dev.to/issues/7499 indeed.

**Comment by rhymes** [comment]
> @rhymes Whoops, the same issue is described in #7499 indeed.

I updated the description to close both at the same time

**Pull request merged**
