### PR TITLE
Add GitDocs to "🔑 Key App tech/services" [skip ci]

### PR DESCRIPTION
**Pull request by jbbn**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [X] Documentation Update

## Description

I just added GitDocs to "🔑 Key App tech/services" section of the documentation.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Let's work!

### CODE REVIEW

**Comment by jbbn** [comment]
I know it is not the "Hacktoberfest", and the contribution is really simple.
I just like the dev.to community and I am looking for a way of start contribuiting 😜

**Comment by rhymes** [comment]
@jbbn the documentation is a great place to start! don't forget to sign the CLA (see the comment above yours)

**Comment by jbbn** [comment]
@rhymes I just sign the CLA, but I didn't understand why the build failed at Travis step. I believe it's not related to my changes.

I found an error reported in the line 1109 (https://travis-ci.com/thepracticaldev/dev.to/builds/102926281#L1109):

```
Failures:
  1) Visiting article comments when root is specified displays related comments
     Failure/Error: raise Pundit::NotAuthorizedError, "You must be logged in" unless user
     
     Pundit::NotAuthorizedError:
       You must be logged in
     # ./app/policies/application_policy.rb:5:in `initialize'
     # ./app/controllers/chat_channels_controller.rb:8:in `index'
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   ./spec/rails_helper.rb:60:in `block (3 levels) in <top (required)>'
Finished in 10 minutes 36 seconds (files took 12.09 seconds to load)
1464 examples, 1 failure, 14 pending
```

**Comment by jbbn** [comment]
> @jbbn the documentation is a great place to start! ...

and thanks for the warm welcoming :wink:

**Comment by Glennmen** [comment]
@jbbn That test seems to fail a lot, I have had that same test fail before with a couple of my PR's. Not sure why that keeps happening.
But indeed it is not related to your PR and probably if someone from the DEV team reruns Travis it will succeed with no errors.

**Comment by jbbn** [comment]
thanks @Glennmen :fist_oncoming:

**Comment by benhalpern** [comment]
Yeah, sorry there are a few random false failures that happen every once in a while with the test suite. We'll get it worked out. Thanks for the PR!

**Comment by jbbn** [comment]
I earned a badge :open_mouth:
It really was not my intention, but thanks.
My next contribution will  more relevant :pray: 
Go DEV :rocket:

**Pull request merged**
