### PR TITLE
Display comment published timestamp according to user's locale

### LINKED ISSUE #406: Datetime for thread
## Feature Request or Task

Showing full date time on hovering the date at the right top edge of thread comment/reply (eg `Aug 19` as in SC below)

Thanks

-------

### Mobile & Desktop Screenshots/Recordings
image

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

This PR does two main things:

* embeds a ISO 8601 timestamp in each `comment-date` tag
* displays such timestamp as a title (hence triggered by hover) with a string converted to the the user/browser's locale

It contains a few additional things:

* I've moved `.eslintrc.js` from the main folder to `app/assets/javascripts` and set the correct ECMA version. The reason is that my VS Code kept complaining the code wasn't ES2016, which it isn't, it's ECMA 5. The folder with the "modern" JavaScript is `app/javascript` and it already has its own ESLint configuration file.

* I've deleted `app/assets/javascripts/utilities/getLocalTime.js` because it wasn't used anywhere and it contained a duplicate function already contained inside [initializeTimeFixer.js](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/initializers/initializeTimeFixer.js)

A note: I couldn't test it with the "reading list -> comment activity" comments because I'm swamped by async jobs that are taking forever. If anybody has suggestions about what to do with those (beside delete them) please let me know. This is my current situation locally:

screenshot_2019-03-04 delayed job web

## Related Tickets & Documents

Closes #406 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

This is how it looks if I set my browser to Italian for example:

screenshot 2019-03-04 at 5 58 43 pm

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

i am a master of time

### CODE REVIEW

**Comment by lightalloy** [comment]
@rhymes As for the async jobs: maybe you haven't run them for a long time, and the jobs just kept adding? (just for the clarification)
In some cases, an async job adds several more jobs, and overall they take a long time to run. I optimized some of these cases, but probably there're more of these.

**Comment by lightalloy** [comment]
Thanks for providing a separate `eslint` config, I struggled with its rules in the old code a bit )

**Comment by rhymes** [comment]
@lightalloy it's totally possible :D I "fixed it" by deleting all the jobs from PostgreSQL, fresh start.

> Thanks for providing a separate `eslint` config, I struggled with its rules in the old code a bit )

Yeah me too, I wonder if there's a "plan" to slowly migrate those files to either Preact or ES6.

I'll take a look at the failed tests :)

**Comment by lightalloy** [comment]
I think deleting is a good enough solution in your case )

I haven't heard of any plan for migration to es6 yet 👀, but that would be cool

**Pull request merged**
