### PR TITLE
Upgrade to Ruby 2.6.0

### PR DESCRIPTION
**Pull request by vinistock**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Upgrade Ruby version to the recently released 2.6.0.

Nokogiri, Webmock and Rubocop had to be upgraded as well to support the new Ruby.

## Added to documentation?

- [ ] docs.dev.to
- [X] readme
- [ ] no documentation needed

### CODE REVIEW

**Comment by vinistock** [comment]
@maestromac Rubocop is failing in [Code Climate]. I don't understand why, but [Code Climate] is running Rubocop 0.52.1 instead of the upgraded 0.62.0, which has breaking changes related to the .rubocop.yml configuration file.

Any ideas on this one?

[Code Climate]: https://codeclimate.com/github/thepracticaldev/dev.to/pull/1482

**Comment by rhymes** [comment]
@vinistock you need to tell Codeclimate to change Rubocop's version, because it defaults to 0.52.1
https://docs.codeclimate.com/docs/rubocop#section-using-rubocop-s-newer-versions

**Comment by vinistock** [comment]
I changed Rubocop's version in the .codeclimate.yml file. Thanks @rhymes for the info.

**Comment by maestromac** [comment]
That's for adding/updating `.codeclimate.yml`. It seems to be messing up our code climate's in-app config. I will move all of that configuration to this newly generated `.codeclimate.yml`.

**Comment by vinistock** [comment]
@maestromac cheers! Always happy to contribute.

**Pull request merged**
