### PR TITLE
Allow CodePen usernames to be up to 30 characters long

### LINKED ISSUE #3487: CodePen Liquid tag username regex allows only 20 characters
Based on this comment, there are CodePen usernames that are over the 20 character limit: https://github.com/thepracticaldev/dev.to/pull/2985#discussion_r303446301

This should be a one character fix to adjust our limit from `20` to `30` in our current regex checker:
https://github.com/thepracticaldev/dev.to/blob/47eaa9ece11fd5e748cf53af6bccde7929d00686/app/liquid_tags/codepen_tag.rb#L50

### PR DESCRIPTION
**Pull request by raquelcps**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
Change CodePen usernames regex to allow up to 30 characters.  ~~I didn't see that character limit was explicitly tested in `codepen_tag_spec.rb` so I'm assuming it's fine to leave it that way.~~ 

## Related Tickets & Documents
Fixes #3487

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text
My first open source commit!

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @raquelcps, thanks for this PR!

Could you perhaps add a test to it?

You can find the relevant code in https://github.com/thepracticaldev/dev.to/blob/master/spec/liquid_tags/codepen_tag_spec.rb

If you have trouble running the code, let me know!

**Comment by raquelcps** [comment]
Hi @rhymes!
A test makes sense to me. I'll haven't tried running the specs, but I'll let you know if I have trouble. I should get to it later tonight.
Thanks!

**Comment by raquelcps** [comment]
I will get to this over the weekend. The Getting Started documentation is helpful but I need more time to work through it.

**Comment by raquelcps** [comment]
Added the test! 
And wanted to say thanks for having such thorough docs for contributing and testing. 
👏 👏 👏

**Pull request merged**
