### PR TITLE
Improve rubocop config #2021

### PR DESCRIPTION
**Pull request by lightalloy**
## What type of PR is this? (check all applicable)
- [x] Refactor

## Description
- Moved `Rails/SkipsModelValidations` to the `.rubocop.yml` because it shouldn't be enabled
- fixed the gems order
- Enabled a couple of `Layout` cops that have no violations

## Related Tickets & Documents
#2021

### CODE REVIEW

**Comment by rhymes** [comment]
I wonder if we can safely enable `Rails/TimeZone` as well, I haven't tried yet

(thanks for fixing the gems order)

**Comment by lightalloy** [comment]
@rhymes At least there are 28 violations to be fixed. Btw, thanks for your previous pr.

**Comment by rhymes** [comment]
> @rhymes At least there are 28 violations to be fixed. Btw, thanks for your previous pr.

ok maybe I'll send a PR for that. Rubocop sometimes feels like a never ending battle but I feel like the code is close to have a great set of defaults with the relentless work you've been doing 🎉

**Comment by lightalloy** [comment]
It seems like, but I think we are close to "good enough". It's ok if the code style won't be ideal, but it should meet certain standards.

**Pull request merged**
