### PR TITLE
Adjust cloning example to use SSH rather than HTTPS

### PR DESCRIPTION
**Pull request by juliannatetreault**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description

Rework the Installing DEV example to use an SSH clone rather than an HTTPS clone.

## Added to documentation?

- [x] docs.dev.to
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

smiling_dog

### CODE REVIEW

**Comment by rhymes** [comment]
I sometimes have weird behaviors cloning with SSH. I'm +1 on keeping the status quo.

@juliannatetreault what prompted the change? Did you have an issue cloning the HTTPS during installation?

Maybe we can instead add a note on cloning with SSH if HTTPS doesn't work and add a link to what @jacobherrington linked, in the documentation

**Comment by juliannatetreault** [comment]
> I sometimes have weird behaviors cloning with SSH. I'm +1 on keeping the status quo.
> 
> @juliannatetreault what prompted the change? Did you have an issue cloning the HTTPS during installation?
> 
> Maybe we can instead add a note on cloning with SSH if HTTPS doesn't work and add a link to what @jacobherrington linked, in the documentation

Apologies for the delayed response--I did not see that there were replies on this PR! 😅

The reason I decided to make this change was because I ran into an issue with linking my GitHub email and signing the CLA when cloning with HTTPS, so I like the idea of adding a note about cloning with SSH if need be. What do you both think? @rhymes @jacobherrington

**Comment by rhymes** [comment]
@juliannatetreault agreed! Let's keep HTTPS as a default and mention SSH :)

Thank you!

**Comment by juliannatetreault** [comment]
> @juliannatetreault agreed! Let's keep HTTPS as a default and mention SSH :)
> 
> Thank you!

Sounds great--I'll make the change! Thank you, too @rhymes 😁

**Comment by mstruve** [comment]
Feel free to merge this when you are ready 💃

**Comment by juliannatetreault** [comment]
> Feel free to merge this when you are ready 💃

Thanks, @mstruve! I don't have merge permissions though, so I will need another team member to merge it for me. 😊

**Comment by Zhao-Andy** [comment]
Leaving a note to hold off on merging since I'll pair with Julianna on the merge!

**Pull request merged**
