### PR TITLE
Use atomic increment for rate limiter counters

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

Use [atomic Redis increment](https://redis.io/commands/incr) for counters.

I tested this with:

```ruby
# try this after toggling `rails dev:cache` on and off
# `rails runner cache_test.rb`

key = "key-#{rand(10_000)}"

# this will print nothing with the :null_store
# but it will work with :redis_cache_store

puts "Initial value: #{Rails.cache.read(key)}"
Rails.cache.increment(key, 1)
value = Rails.cache.read(key)
puts "After increment: #{value}, #{value.class}"

# Cache read: key-1639 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>3600, :race_condition_ttl=>nil})
# Initial value:
# Cache increment: key-1639 ({:amount=>1})
# Cache read: key-1639 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>3600, :race_condition_ttl=>nil})
# After increment: 1, String
```

and verified with:

```shell
➜  devto ✗ redis-cli
127.0.0.1:6379> get key-1639
"1"
127.0.0.1:6379> incrby key-1639 2
(integer) 3
127.0.0.1:6379> get key-1639
"3"
127.0.0.1:6379>

➜  devto ✗ rails runner "puts Rails.cache.read('key-1639')"
Cache read: key-1639 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>3600, :race_condition_ttl=>nil})
3
```

The correct way to make it work in testing is to use the [https://api.rubyonrails.org/classes/ActiveSupport/Cache/RedisCacheStore.html](https://api.rubyonrails.org/classes/ActiveSupport/Cache/RedisCacheStore.html):

```ruby
if Rails.env.test?
  Rails.cache = ActiveSupport::Cache::RedisCacheStore.new
end

key = "key-#{rand(10_000)}"

puts "Key: #{key}"
puts "Initial value: #{Rails.cache.read(key)}"
Rails.cache.increment(key, 1)
value = Rails.cache.read(key)
puts "After increment: #{value}, #{value.class}"
```

see:

```shell
➜  devto ✗ rails runner -e test t.rb
Key: key-3825
Initial value:
After increment: 1, String
➜  devto ✗ redis-cli get key-3825
"1"
```

The reason why it didn't work in the tests is because we're using the memory store, [which I believe contains a bug in how it works](https://github.com/rails/rails/blob/4dcc5435e9569e084f6f90fcea6e7c37d7bd2b4d/activesupport/lib/active_support/cache/memory_store.rb#L160-L164):

```ruby
            if num = read(name, options)
              num = num.to_i + amount
              write(name, num, options)
              num
            end
```

As you can see, it will increment the counter, only if it's already initialized to 0 (which in Ruby is a truthy value and will end up in the increment block), otherwise it will fail :(

[Redis cache store on the other side](https://github.com/rails/rails/blob/4dcc5435e9569e084f6f90fcea6e7c37d7bd2b4d/activesupport/lib/active_support/cache/redis_cache_store.rb#L262):

```ruby
            redis.with { |c| c.incrby normalize_key(name, options), amount }
```

uses [Redis INCRBY](https://redis.io/commands/incrby) which has this behavior:

> Increments the number stored at key by increment. If the key does not exist, it is set to 0 before performing the operation.

this is why with Redis works, with MemoryStore doesn't. 

I'll see if I can raise the issue with Rails and see what they tell me about the discrepancy.

## Added tests?

- [x] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

### CODE REVIEW

**Comment by rhymes** [comment]
Further exploration if you're curious:

```ruby
require "tempfile"

cache_stores = %i[
  file_store
  mem_cache_store
  memory_store
  null_store
  redis_cache_store
]

increment_values = {}

cache_stores.each do |cache_store|
  store = if cache_store == :file_store
            ActiveSupport::Cache.lookup_store(cache_store, Tempfile.new)
          else
            ActiveSupport::Cache.lookup_store(cache_store)
          end

  Rails.cache = store
  puts "Using #{cache_store}..."

  key = "key-#{rand(10_000)}"

  puts "Initial value: #{Rails.cache.read(key).inspect}"

  Rails.cache.increment(key, 1)

  value = Rails.cache.read(key)
  puts "Final value: #{value}, #{value.inspect}"

  increment_values[cache_store] = value

  puts
end

puts increment_values
```

this will result in:

```text
Using file_store...
Cache read: #<File:0x00007fcbe0e5b808>/24D/F00/key-6466
Initial value: nil
Cache read: #<File:0x00007fcbe0e5b808>/24D/F00/key-6466
Cache read: #<File:0x00007fcbe0e5b808>/24D/F00/key-6466
Final value: , nil

Using mem_cache_store...
Cache read: key-7594
Dalli::Server#connect localhost:11211
Initial value: nil
Cache increment: key-7594 ({:amount=>1})
Cache read: key-7594
Final value: , nil

Using memory_store...
Cache read: key-2
Initial value: nil
Cache read: key-2
Cache read: key-2
Final value: , nil

Using null_store...
Cache read: key-5155
Initial value: nil
Cache read: key-5155
Final value: , nil

Using redis_cache_store...
Cache read: key-2909 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>nil, :race_condition_ttl=>nil})
Initial value: nil
Cache increment: key-2909 ({:amount=>1})
Cache read: key-2909 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>nil, :race_condition_ttl=>nil})
Final value: 1, "1"

{:file_store=>nil, :mem_cache_store=>nil, :memory_store=>nil, :null_store=>nil, :redis_cache_store=>"1"}
```

as you can see, on Redis has that side effect behavior (so technically Rails documentation is wrong about the RedisCache store needing the initial value).

If we add `Rails.cache.write(key, 0)` or `Rails.cache.write(key, "0")` both MemCachStore and RedisStore fail because in both cases they receive the key is initialized with the wrong data type:

```
Using mem_cache_store...
Cache write: key-462
Dalli::Server#connect localhost:11211
Cache read: key-462
Initial value: 0
Cache increment: key-462 ({:amount=>1})
DalliError (Response error 6: Incr/decr on a non-numeric value): Response error 6: Incr/decr on a non-numeric value
Cache read: key-462
Final value: 0, 0
```

```
Using redis_cache_store...
Cache write: key-1872 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>nil, :race_condition_ttl=>nil})
Cache read: key-1872 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>nil, :race_condition_ttl=>nil})
Initial value: 0
Cache increment: key-1872 ({:amount=>1})
Traceback (most recent call last):
bin/rails: Bootsnap::LoadPathCache::FallbackScan
...
/Users/rhymes/.rvm/gems/ruby-2.7.1/gems/redis-4.1.3/lib/redis/client.rb:126:in `call': ERR value is not an integer or out of range (Redis::CommandError)
```

If we add `Rails.cache.write(key, 0, raw: true)` then they all behave in a similar way (except for data types), though by needing an initalization value for a key value store you're kinda defeating the purpose of `.increment` in a concurrent scenario.

```
Using file_store...
Cache write: #<File:0x00007fd00965d9a8>/245/D60/key-1517 ({:raw=>true})
Cache read: #<File:0x00007fd00965d9a8>/245/D60/key-1517
Initial value: 0
Cache read: #<File:0x00007fd00965d9a8>/245/D60/key-1517
Cache write: #<File:0x00007fd00965d9a8>/245/D60/key-1517
Cache read: #<File:0x00007fd00965d9a8>/245/D60/key-1517
Final value: 1, 1

Using mem_cache_store...
Cache write: key-9338 ({:raw=>true})
Dalli::Server#connect localhost:11211
Cache read: key-9338
Initial value: "0"
Cache increment: key-9338 ({:amount=>1})
Cache read: key-9338
Final value: 1, "1"

Using memory_store...
Cache write: key-8583 ({:raw=>true})
Cache read: key-8583
Initial value: 0
Cache read: key-8583
Cache write: key-8583
Cache read: key-8583
Final value: 1, 1

Using null_store...
Cache write: key-5652 ({:raw=>true})
Cache read: key-5652
Initial value: nil
Cache read: key-5652
Final value: , nil

Using redis_cache_store...
Cache write: key-7796 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>nil, :race_condition_ttl=>nil, :raw=>true})
Cache read: key-7796 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>nil, :race_condition_ttl=>nil})
Initial value: "0"
Cache increment: key-7796 ({:amount=>1})
Cache read: key-7796 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>nil, :race_condition_ttl=>nil})
Final value: 1, "1"

{:file_store=>1, :mem_cache_store=>"1", :memory_store=>1, :null_store=>nil, :redis_cache_store=>"1"}
```

**Comment by rhymes** [comment]
@mstruve you read my mind! I was actually thinking to update the test to use :redis_store, to make sure we don't get blindsided by this in the future. I'll update the PR :)

**Comment by mstruve** [comment]
@rhymes I was able to use it successfully in `attack_spec.rb` which tests our rack attack throttling if you want to try to grab some already usable code.

**Comment by rhymes** [comment]
@mstruve I was able to reproduce this (by chance, because I mistyped :D):

```ruby
  1) ImageUploads POST/image_uploads when uploading rate limiting works counts number of uploads in cache
     Failure/Error: expect(cache.read(cache_key)).to eq(1)

     ArgumentError:
       marshal data too short
```

by using:

```ruby
ActiveSupport::Cache.lookup_store(:redis_store)
```

instead of the correct

```ruby
ActiveSupport::Cache.lookup_store(:redis_cache_store)
```

With the correct store, the "caching" one, it works

**Comment by mstruve** [comment]
🤦‍♀️ YEP that was my error!!!  Mystery solved!

**Comment by Ridhwana** [comment]
This looks really good @rhymes and you're awesome for putting such a verbose description which let me follow along and test!

**Pull request merged**
