### PR TITLE
Show User a LiquidTag error for an invalid YouTube ID 

### PR DESCRIPTION
**Pull request by mstruve**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
I noticed that [this error](https://app.honeybadger.io/projects/66984/faults/59411310) was getting raised for an invalid youtube tag but when that happens the user gets no valuable feedback
```
StandardError: Invalid YouTube ID
youtube_tag.rb  26 parse_id(...)
[PROJECT_ROOT]/app/liquid_tags/youtube_tag.rb:26:in `parse_id'
24   def parse_id(input)
25     input_no_space = input.delete(" ")
26     raise StandardError, "Invalid YouTube ID" unless valid_id?(input_no_space)
27     return translate_start_time(input_no_space) if input_no_space.include?("?t=")
```
By raising a`Liquid::SyntaxError` we will catch the error and display the message helpfully to the individual. 

Screen Shot 2020-01-10 at 10 49 50 AM
Screen Shot 2020-01-10 at 10 49 57 AM

## Added to documentation?
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by mstruve** [comment]
Not sure why the Youtube tags act different than the rest but this will at least fix the error and stop alerting Honeybadger when it happens. It might be worth making an issue if someone wants to put more time into it.

**Comment by rhymes** [comment]
@mstruve since we don't know exactly why this happens it might be worth it not silencing the error, especially because I couldn't reproduce it, either on local on in production

**Comment by mstruve** [comment]
Was able to reproduce in production by submitting a comment with an invalid Youtube ID. Basically when you try to submit the comment the page just hangs and requires a reload.

Screen Shot 2020-01-12 at 8 41 00 AM

More backtrace:
```
StandardError: Invalid YouTube ID
[PROJECT_ROOT]/app/liquid_tags/youtube_tag.rb:26 :in `parse_id`
24   def parse_id(input)
25     input_no_space = input.delete(" ")
26     raise StandardError, "Invalid YouTube ID" unless valid_id?(input_no_space)
27     return translate_start_time(input_no_space) if input_no_space.include?("?t=")
[PROJECT_ROOT]/app/liquid_tags/youtube_tag.rb:6 :in `initialize`
[PROJECT_ROOT]/app/labor/markdown_parser.rb:20 :in `finalize`
[PROJECT_ROOT]/app/models/comment.rb:215 :in `evaluate_markdown`
[PROJECT_ROOT]/vendor/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235 :in `mon_synchronize`
[PROJECT_ROOT]/app/controllers/comments_controller.rb:57 :in `create`
```

**Comment by rhymes** [comment]
Thanks! This problem is present in every and all liquid tags that can be used in the markdown editor in the comments. For that reason I think I came up with an alternative solution that encompasses all tags, with the hope that we'll rivisit both the UI and use custom errors for liquid tags soon: https://github.com/thepracticaldev/dev.to/pull/5485

**Comment by mstruve** [comment]
Closing in favor of https://github.com/thepracticaldev/dev.to/pull/5485

**Pull request closed without merging**
