### PR TITLE
Added nickytonline.dev-to-extension-pack to the VSCode recommendations

### LINKED ISSUE #5202: Add a DEV VS Code extension pack to the recommended VS Code Extensions
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

We've added several extensions to the [list of recommended extensions for VS Code](https://github.com/thepracticaldev/dev.to/blob/master/.vscode/extensions.json) when working on the DEV repository. After I added a few more extensions to the recommended ones, I made an [unofficial extension pack](https://github.com/nickytonline/dev-to-extension-pack) that I decided to use instead.

I thought it'd be fun to instead have a DEV VS Code extension pack.

Maybe?.

Thoughts? This would also make a great first PR for someone.

**Describe alternatives you've considered**

N/A

**Additional context**

### PR DESCRIPTION
**Pull request by brobertsaz**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
- Added a new VSCode Dev.to extension pack to the VSCode extension recommendations
- This Closes #5202

## Related Tickets & Documents
https://github.com/thepracticaldev/dev.to/issues/5202

## Added tests?

- [ ] yes
- [X] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

### CODE REVIEW

**Comment by citizen428** [comment]
Good idea @brobertsaz, thanks! One question though: the extension pack overlaps with several of the other recommendations, e.g. `waderyan.nodejs-extension-pack`. I don't necessarily think this is a problem, but is there a best practice around this?

**Comment by brobertsaz** [comment]
@citizen428 Good point. I was tempted to remove the `extra` extensions but there might be users that want to use one or more but not all of the available extensions and therefore not want to use the all inclusive `nickytonline.dev-to-extension-pack`

**Comment by brobertsaz** [comment]
@citizen428 Good point. I was tempted to remove the `extra` extensions but there might be users that want to use one or more but not all of the available extensions and therefore not want to use the all inclusive `nickytonline.dev-to-extension-pack`

**Comment by nickytonline** [comment]
Good point @brobertsaz about not all users wanting to potentially use everything in the extension pack as it's an all or nothing. I had good intentions when I created the extension pack, but the more I think about it, the recommended extensions make sense to be on a per extension basis, i.e. leave things as is and just keep adding recommended extensions as we see fit.

Thoughts @citizen428 @maestromac?

**Comment by brobertsaz** [comment]
@nickytonline I myself prefer the packaged packs and yours is pretty clear as to what it includes :)

**Comment by nickytonline** [comment]
> @nickytonline I myself prefer the packaged packs and yours is pretty clear as to what it includes :)

Ahh, I see what you were doing now in the PR. Not enough coffee 😺 Give them the option to install the DEV extension pack, but if they decide not to, they can just pick out of the list of recommended extensions.

If that's the case. I would just add the DEV extension pack to the list and include all that were originally there as well.

**Pull request merged**
