### PR TITLE
Internal: Add a table for negative reactions

### PR DESCRIPTION
**Pull request by jacobherrington**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This is a simplified version of a feature that should be fleshed out
in the near future.

Despite the fact that this project is taking a new direction, I think
this table could be useful in the meantime.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Peek 2020-03-20 19-29

## Added tests?

- [x] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @jacobherrington.

This PR reminded me that there was a first attempt of auditing moderators actions and this looks a lot like an auditing table but without using the auditing logs, so we might want to have the two features converge.

See https://github.com/thepracticaldev/dev.to/pull/3449

**Comment by jacobherrington** [comment]
@rhymes Thanks for pointing me in that direction! That is exactly the context I needed to build the next step of this project. :heart: :tada: 

I will get caught up on that auditing implementation and seek the best way to build on that existing good solution.

In the meantime, I think this is a short-term pragmatic approach and worth merging -- it will help Michael, Peter, and anyone else interested imagine how they'd use a more fleshed out audit log. That should allow use to shorten the feedback loop and collaborate more effectively.

**Comment by benhalpern** [comment]
Hey @jacobherrington I just talked to Peter about this and yeah, the approach we want to take is closing the loop on the built-but-not-used audit logging as @rhymes pointed out.

I think this is a really nice implementation though and I think we may want to keep it around as a list of negative reactions anyway, just because that is different from logging anyway, which is highly de-normalized and not going to give this same query abilities as reactions.

So I'm cool with whatever your team comes up with but I don't think it needs to be an either or. Kudos for making such early progress either way.

I'm cool to merge this if you see fit, but want to ask whether we want to change the naming of this and put a bow on it as the interface to query for negative reactions and then make the audit logging its own feature.

**Comment by jacobherrington** [comment]
@benhalpern I agree, thanks for the feedback!

I tweaked this a bit to be a "Negative Reactions" table irrespective of users. :+1:

**Pull request merged**
