### PR TITLE
Export comments

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

I've added comments to the export and changed/updated the copy.

## Related Tickets & Documents

https://github.com/thepracticaldev/dev.to/issues/1461

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
The [WIP] is for three reasons:

1. the list of allowed attributes needs to be finalized. @benhalpern [here](https://github.com/thepracticaldev/dev.to/issues/1461#issuecomment-451543347) listed those to remove. If `reactions_count` shouldn't be included then we should probably remove it from the export of the articles as well. Unless it works differently among the two resources

2. In the copy I changed `data` with `content` which seems less impersonal

3. I was wondering if in the comments export we should add some information about what the comment is attached to. Not the ancestry/tree information, but the path (or URL?) of the `commentable`. Otherwise the comment is a little "lost" in the export

**Comment by benhalpern** [comment]
@rhymes 
1. Yeah, you're right. Not highly sensitive info, but that shouldn't have been included. Our bad on the proofread.
2. 👌
3. Yeah that makes sense.

**Comment by rhymes** [comment]
@benhalpern 

I've removed the field `reactions_count` from both articles and comments and added `commentable_path` as an extra field in the comments export with the path (not the URL) for the resource the comment is attached to

**Comment by rhymes** [comment]
Thanks!

**Pull request merged**
