### PR TITLE
Add codesandbox support

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

New liquid tag hot addition

### CODE REVIEW

**Comment by dance2die** [comment]
May I ask when this feature will be available on production?

This feature is a game changer 😄

**Comment by davefollett** [comment]
I'm wondering the same thing.  I was literally just looking into how to embed codesandbox with dev.to and was about to switch to use a codepen instead.   But now I'm wondering if I should wait for this to get merged and deployed.

**Comment by dance2die** [comment]
This feature will be quite helpful 
as I've been adding `Edit on CodeSandbox` button as embedding hasn't been available.

**Comment by maestromac** [comment]
@dance2die @davefollett the feature is available now! There's typo in the editor guide right now; the proper usage is `{% codesandbox 23948skjfksjdf %}`

**Comment by benhalpern** [comment]
This is currently available in production.

This should have gone in long ago because it's very simple for us to add these.

First instance of its use:

https://dev.to/dan_abramov/making-sense-of-react-hooks-2eib

**Comment by davefollett** [comment]
Maybe I'll be the second one, I will be publishing in a few minutes.  Thank you very much.

**Comment by dance2die** [comment]
Thank you guys. Much appreciated.

**Comment by firatoezcan** [comment]
Is this already documented somewhere?

**Comment by nolear** [comment]
(https://github.com/thepracticaldev/dev.to/files/2646330/js.txt) hepl my coding npm up node_modules

**Pull request merged**
