### PR TITLE
REF: react eslint

### PR DESCRIPTION
**Pull request by venarius**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Since most of the *.jsx files don't seem to be refactored and husky automatically refactors them when changing a line in of these files, I thought "why not refactor all of them now?"

Now, prettier seems to be happy with all *.jsx files. Eslint still has about 250 errors to report but these can't be fixed automatically. Because of this its also currently not possible to commit a change on a jsx file without needing to use the `--no-verify` flag.

We should either disable some of these rules or try to get all 250 errors fixed.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by venarius** [comment]
Regarding the codeclimate issues: I would much more prefer this commit to be merged how it currently is and then I will fix these issues one by one in their seperate PRs, so it's easier to review them.

**Comment by rhymes** [comment]
@venarius why has the order of execution between prettier and eslint changed? I never seem to get that right 😅 First eslint and then prettier or first prettier and eslint? What if prettier messes up and eslint doesn't catch it?

**Comment by rhymes** [comment]
@venarius why has the order of execution between prettier and eslint changed? I never seem to get that right 😅 First eslint and then prettier or first prettier and eslint? What if prettier messes up and eslint doesn't catch it?

**Comment by venarius** [comment]
@rhymes from my experience eslint is better than prettier when it comes to refactoring but prettier should come after eslint for things like tabspaces, etc...

This is for example some output that eslint generates:
```
const tags = articleState.tagList.split(', ').map(tag => {
    return (
      <span>
        <div className="tag">{tag}</div>
{' '}
      </span>
    );
  });
```

It's just something I experienced when husky ran over some files I changed and then suddenly the tabspaces were all over the place. 😅

**Comment by rhymes** [comment]
@venarius thanks! what's `{' '}` ? I've seen a few in the diff

**Comment by venarius** [comment]
@rhymes it inserts whitespace without random html tags. See https://stackoverflow.com/questions/40264084/best-practice-when-adding-whitespace-in-jsx

**Comment by benhalpern** [comment]
> Now, prettier seems to be happy with all *.jsx files. Eslint still has about 250 errors to report but these can't be fixed automatically. Because of this its also currently not possible to commit a change on a jsx file without needing to use the --no-verify flag.

Want to make an additional PR about this?

**Pull request merged**
