### PR TITLE
Moving babel to dev dependency

### PR DESCRIPTION
**Pull request by Rafi993**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This PR moves babel and its supporting packages from **dependencies** to **devDependencies**

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
@Rafi993 could you explain the reasoning behind this? Sorry but it's not clear from the PR description.

**Comment by Rafi993** [comment]
> @Rafi993 could you explain the reasoning behind this? Sorry but it's not clear from the PR description.

Sorry I did not make the description clear. The reason I moved these babel and supporting libs from dependencies to devDependencies is because these packages are used during development  (and for creating production build) but are not part of user facing code.

**Comment by rhymes** [comment]
Thanks @Rafi993 for the explanation.

Agreed in principle, though I think they were moved there due to issues we were encountering with Herou deploys, see https://github.com/thepracticaldev/dev.to/pull/6799 and https://github.com/thepracticaldev/dev.to/pull/6800

cc @nickytonline which might know if these should stay put where they are still or they can be moved back to `devDependencies`

**Comment by nickytonline** [comment]
I’ve encountered this at my last job as well. The reason there are some devDependencies in dependencies is because when we build on Heroku, Heroku only installs dependencies, not devDependencies.

See [pruning dependencies](https://devcenter.heroku.com/articles/nodejs-support#skip-pruning) in Heroku’s bodega documentation.

**Comment by nickytonline** [comment]
Closing as we won't be moving these dependencies.

**Pull request closed without merging**
