### PR TITLE
Fixed invalid body_markdown in article with video

### PR DESCRIPTION
**Pull request by araslanov-e**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
After upload video creates an article with body_markdown with an empty description and failed to parse tags

## Related Tickets & Documents
https://github.com/thepracticaldev/dev.to/issues/3846

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @araslanov-e, it's not clear to me what the fix is :) Is it about indentation in the creation service body markdown strings?

**Comment by araslanov-e** [comment]
Hi @rhymes, I added a link to the related ticket https://github.com/thepracticaldev/dev.to/issues/3846

**Comment by araslanov-e** [comment]
I'm looking for a solution for MarkdownFixer, there are more tests and a clearer problem

**Comment by rhymes** [comment]
@araslanov-e sorry, I wasn't clear, I was referring to the diff, what is not clear to me is where the fix is in the code :)

The code on the left looks a lot similar to the code you changed, that's why I was asking!

**Comment by araslanov-e** [comment]
@rhymes Aaa, sorry. There was no space before after `description:`

**Pull request merged**
