### PR TITLE
add hover effect to buttons on articles (#656)

### PR DESCRIPTION
**Pull request by omenking**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
add hover affect to button.

## Related Tickets & Documents
Read my journey to complete this ticket via original ticket:
https://github.com/thepracticaldev/dev.to/issues/656

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Before and after hover.
If you have some sort of preference to styling tell me, I'm a styling wizard.

Screen Shot 2019-04-09 at 5 51 07 PM

Screen Shot 2019-04-09 at 5 51 10 PM

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Watch out for wheelers!

### CODE REVIEW

**Comment by Glennmen** [comment]
Not saying this is bad but isn't the default behaviour for hover on DEV currently to add opacity?

I checked a couple of elements, for example on the homepage -> article -> owner name, and on hover it adds `0.9` opacity.

**Comment by omenking** [comment]
@Glennmen I have checked and I confirm it is `0.9`. I can set it to as such but that opacity `0.9` provides very little in contrast to change.

I am personally indifferent and welcome anyone to make a final decision and I will tweak accordingly.

**Comment by Link2Twenty** [comment]
I think you can probably simplify this and have it still work with themes like so.

```css
&.comments-count {
  left: 93px;
  img {
    width: 28px;
  }
  &:hover {
    opacity: 0.9;
  }
}
&.reactions-count {
  left: 20px;
  &:hover {
    opacity: 0.9;
  }
}
```

**Comment by jessleenyc** [comment]
Hey all, we're working on some design changes for the home page and we'll take this suggestion into consideration. I'm going to close this PR since we're doing an overhaul and haven't heard from y'all in a little while.

**Pull request closed without merging**
