### PR TITLE
Prepare for ENVie gem default value processing deprecation

### PR DESCRIPTION
**Pull request by keithrbennett**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Response to Gem Deprecation

## Description

I'm not certain this approach is satisfactory, but implementing it moves the default setting out of ENVie and does not change the success or failure of the unit tests.

Previously, a default parameter was passed to ENVie to manage. I changed this to modify ENV itself if there was no non-nil value and if the environment was not production (please see comment in code regarding that condition).

Whereas a numeric default value was passed to ENVie as a number, I am setting the ENV value to the string representation of the number. The data type is passed to ENVie, and I am assuming it will handle any necessary conversions.

## Related Tickets & Documents

Issue #5152 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by keithrbennett** [comment]
As you will see in the recent commit, I've fixed the error that was causing the build failures until now. That said, I'm a little confused as to why the parameter being passed was previously a Proc (see comment), and if my strategy of computing a string immediately is correct.

**Comment by keithrbennett** [comment]
(I will of course remove those comments from the code if we go ahead with this.)

**Comment by keithrbennett** [comment]
On second thought, I have removed the temporary comments. The question I posed in the previous comment still applies.

**Comment by mstruve** [comment]
Hi @keithrbennett 

I first want to say it looks like our team majorly dropped the ball on getting back to you on this amazing PR. I am incredibly sorry about that.  We know your time is valuable and we appreciate every min of it you put towards improving DEV. 

With that said, we are in the process of going through and cleaning up some of our PR history to help us better prioritize what we need to be focusing on. Since this PR has not been active for a while and has a few conflicts I am going to go ahead and close it for now. If you would still like to get this merged please feel free to resolve the conflicts and then open the PR back up. We would be more than happy to help you push this through if you would like! We also have a much larger team now so we can ensure it gets the attention it needs.

Thank you so much for contributing! Ping us anytime if you have questions!

**Pull request closed without merging**
