### PR TITLE
Add post as an alias to the link liquid tag

### PR DESCRIPTION
**Pull request by luke-jones-1**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Added an alias (post) for the 'link_tag' liquid test, along with a test to check that it would function as an alias. It's my first  time contributing to an OSS so any feedback would be appreciated.

## Related Tickets & Documents

Fixes https://github.com/thepracticaldev/dev.to/issues/3376

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by luke-jones-1** [comment]
Hi @rhymes, i think ive got a working test now and ive edited the editor guide as well, let me know if anything is wrong and ill try to fix it.

**Comment by luke-jones-1** [comment]
@rhymes thanks, it was a lot of fun learning how these sort of sites are developed and tested, is there any other beginner level issues i could try working on?

**Comment by rhymes** [comment]
Thank you! @luke-jones-1 

you can have a look at the ones labeled "good first issue": https://github.com/thepracticaldev/dev.to/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+

**Comment by luke-jones-1** [comment]
alright, will do

**Pull request merged**
