### PR TITLE
[WIP] Change feature tests to system test

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
- [x] Feature
## Description
- Switch from feature spec to system spec
  - which allows us to removed Database-cleaner and also needs to downgrade Capybara.
- Also removed `react-textarea-autocomplete` because we aren't using it.
## Related Tickets & Documents
n/a
## Added to documentation?
- [x] no documentation needed

### CODE REVIEW

**Comment by abraham** [comment]
Out of curiosity, what is the reason for downgrading `capybara`?

**Comment by maestromac** [comment]
@abraham because [Rails 5.1.x locks capybara to](https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_dispatch/system_test_case.rb#L1) `>= 2.15` 🔪. 
 
also see,  https://github.com/rails/rails/pull/32151

**Comment by abraham** [comment]
That's sad.

**Comment by rhymes** [comment]
> @abraham because [Rails 5.1.x locks capybara to](https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_dispatch/system_test_case.rb#L1) `>= 2.15` 🔪.
> 
> also see, [rails/rails#32151](https://github.com/rails/rails/pull/32151)

aaaaah :( 
I hope we can find a way to upgrade dev.to's code up to Rails 5.2 at some point 😭 crossing fingers!

**Comment by maestromac** [comment]
@rhymes yeah we gotta do that. This is motivating me top upgrade.

**Comment by maestromac** [comment]
I’m shelving my attempt to move feature specs to system spec. While it was done and the test suite passes, around 8-10 specs needs to run twice to pass. It was making our test suite worse and I can’t figure out what’s causing the flakiness. The capybara downgrade definitely doesn't help. Will revisit after 5.2 is in place.

**Pull request closed without merging**
