### PR TITLE
Upgrade gems to fix installation on Windows

### PR DESCRIPTION
**Pull request by rhymes**
This references #298. The rationale behind the changes:

* msgpack supports Ruby 2.5 on Windows starting from 1.2.4
* pg supports Ruby 2.5 on Windows starting from 1.0
* stackprof is Linux/OSX only

Also: PostgreSQL < 9.2 are not supported anymore with pg 1.0, so if this conflicts with the version of PostgreSQL that runs dev.to I can undo that change.

## What type of PR is this? (check all applicable)
- [ ] Refactor
- [ ] Feature
- [x] Bug Fix

## Description

In this issue https://github.com/thepracticaldev/dev.to/issues/298 @Nirajn2311 was attempting to execute `bundle install` on a Windows machine with Ruby 2.5 and it succeded only after making this three changes.

### CODE REVIEW

**Comment by Nirajn2311** [comment]
This only allows to install the gems but after that bin/setup and bin/startup doesn't work. I gave up trying and will wait until someone gives clear info on how to set up in Windows.

**Comment by rhymes** [comment]
Can you open an issue with the exact errors and stack trace?

**Comment by greysteil** [comment]
@maestromac would you be up for automatically creating dependency update PRs like this one? I built [Dependabot](https://dependabot.com) to do that, and it's free for open source (and always will be).

I think it would save you a bit of time and help keep dev.to up-to-date, but I also have a bigger plan for it: I'm keen to get more open source apps using it so I can use the data on the CI runs for dependency updates to find bugs in new releases and point the maintainers to the failing CI run as a reproduction step.

Obviously needs a bit of work to detect issues reliably, but I think it can get there, and having well-tested open-source apps like dev.to use it should enable it to do awesome things, like automatically test release candidates of Rails and report back on any breakages, etc.

What do you reckon?

**Comment by benhalpern** [comment]
Hey @greysteil yeah, we can give Dependabot a go. @maestromac will set it up.

I'm fairly conservative about adopting new tools. Can you stay involved in our project and help us make the most of it over time? I feel like this project will always be a good way to show it off to a lot of developers. 😄

**Comment by greysteil** [comment]
Awesome, and yes, absolutely, I was going to suggest the same!

@maestromac - the easiest way to set it up is [here](https://github.com/apps/dependabot) (skips the GitHub Marketplace, which can be slightly confusing). Once you've done that ping me and I'll help out with the initial PRs. 😄

**Comment by greysteil** [comment]
And it looks like you're one step ahead of me! I'll take a look at those PRs now :-)

**Pull request merged**
