### PR TITLE
Add style for images on email to turn them responsiveness

### LINKED ISSUE #1393: Images in emails are not responsive in Gmail
**Describe the bug**

Images in comment notification emails can be large and not display in a scaled manor.

**To Reproduce**

1. Comment on a post.
1. Have someone else reply to your comment with an embedded image.
1. Look at the comment notification email in Gmail on the web.

**Expected behavior**

I would expect that the image would be no wider than the width of the displayed email.

**Screenshots**

screenshot from 2018-12-21 15-53-19

**Desktop (please complete the following information):**

- OS: Ubuntu 18.10
- Browser: Chrome
- Version: 71.0.3578.98 (Official Build) beta (64-bit)

**Additional context**

The particular comment I was notified about: https://dev.to/rhymes/comment/7kna

Potential solutions: https://stackoverflow.com/questions/10711638/how-to-dynamically-resize-an-image-inside-an-email-client

### PR DESCRIPTION
**Pull request by luchiago**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description
Add style for images on email to turn them responsiveness

## Related Tickets & Documents
Closes #1393 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Peek 2020-04-13 00-02

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

css_is_awful

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @luchiago, thanks for doing this! This applies only to one kind of email, though right? Is there a possibility to it happening in other emails as well?

**Comment by luchiago** [comment]
@rhymes I have no idea, but I can investigate if you want. The resource of preview emails is very useful.

**Comment by rhymes** [comment]
> @rhymes I have no idea, but I can investigate if you want. The resource of preview emails is very useful.

thanks!

**Comment by luchiago** [comment]
@rhymes If I find it, do you want me to send separate PR for each file or send a PR? Or push the changes here?

**Comment by luchiago** [comment]
@rhymes If I found do you want me to send in separated PR's every file or send in one PR? Or push the modifications here?

**Comment by rhymes** [comment]
> @rhymes If I find it, do you want me to send separate PR for each file or send a PR? Or push the changes here?

I thought this PR was for all emails in the first place so here it's fine :) I'm going to put WIP just in case

**Comment by ludwiczakpawel** [comment]
I'm not an expert re email templates, but is it possible that there will be a _small_ image that shouldn't take full width?

**Comment by luchiago** [comment]
> I'm not an expert re email templates, but is it possible that there will be a _small_ image that shouldn't take full width? Just thinking out loud here: maybe instead of `width: 100%;` we should have `max-width: 100%;`? But I haven't tested it...
> 
> Also, shouldn't this be within some kind of [gmail-supported media query](https://developers.google.com/gmail/design/reference/supported_css#supported_media_queries)?

I see your point @ludwiczakpawel. I tested here with a 512x512 logo and see the problem. With `max-width` solve it.

**Comment by luchiago** [comment]
@rhymes Hey, sorry for the delay, but I found the problem in `mentions_email` and correct it. I'm not sure if the same applies to `new_message_email` bc I don't know if I can send images through the message.

**Comment by rhymes** [comment]
Thanks a lot @luchiago, I'm going to merge this as-is. If we discover this applies to `new_message_email` as well, we can fix it then now that we know how :D

**Pull request merged**
