### PR TITLE
Standardise tag list data between Articles API endpoints

### PR DESCRIPTION
**Pull request by Turnerj**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description

This brings the "show" endpoint and the "index" endpoints for the Articles API inline with how they represent the tag list data.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Doesn't this affect the frontend? I'm asking because I'm not sure how extensive the tests are on that side, but maybe you've already double checked :)

**Comment by Turnerj** [comment]
To be perfectly honest, I have no idea. I've never worked on Ruby before and my understanding of where the APIs are used is relatively limited.

There is a high probability I've missed something where the API is used - perhaps the iOS app. For the main web though, looking at the "show" view for articles, it doesn't seem to touch the API.

https://github.com/thepracticaldev/dev.to/blob/master/app/views/articles/show.html.erb

**Comment by rhymes** [comment]
> To be perfectly honest, I have no idea. I've never worked on Ruby before and my understanding of where the APIs are used is relatively limited.

I meant the web app frontend. The API is used in some cases by the JavaScript layer as well as you said by iOS. 

Although by a quick look this change shouldn't break anything, it's worth keeping that in mind

**Comment by Turnerj** [comment]
Cool, I'll go over the JS code to double check and poke around the [iOS](https://github.com/thepracticaldev/DEV-ios) codebase to see what it is calling. 🙂

**Comment by Turnerj** [comment]
So the iOS app looks safe - no direct calls to the articles API, it primarily wraps the web app. Going through the JS, there is one potential reference but will need to investigate it further in the morning: https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/chat/chat.jsx#L527-L535

**Comment by benhalpern** [comment]
I just marked this as approved, but I just realized I didn't think it entirely through.

I _think_ this is all safe, but let me give it some more thought.

**Comment by Turnerj** [comment]
I've gone through that `chat.jsx` file I linked to earlier and tracked down how it uses the Articles API. For whatever circumstances that trigger the Article API call in Chat (I'm guessing linking to an Article but that part is still unclear), it renders a special control for the Article with the following file:

https://github.com/thepracticaldev/dev.to/blob/60d38ef787b45b8bc7404927879d9561229818ab/app/javascript/chat/article.jsx

While it seems to display everything else about an article from reactions, title, published date etc, it doesn't actually use the tag list at all.

**Comment by Turnerj** [comment]
@benhalpern are you still wanting to think about this one a bit more? If you don't want to proceed with it because it impacts something else or you have other plans with the API, it is all good. 🙂

**Pull request closed without merging**
