### PR TITLE
Update MethodLength to 40

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)

- [x] Misc

## Description
- Increase line limit threshold to 40 lines
- Fixed lints introduced by that
- Remove `/spec` from being excluded from CodeCliamte
## Related Tickets & Documents
n/a
## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
n/a
## Added to documentation?
- [x] no documentation needed

### CODE REVIEW

**Comment by maestromac** [comment]
I have fixed a few lint and added some eluded files @lightalloy 

but removing `/spec` from being excluded introduced 222 lints 😒

**Comment by lightalloy** [comment]
@maestromac I looked into these issues and I think that we should have different codeclimate code settings for the `/spec` folder if that's possible, like disabling or increasing allowed file length. If we decide to do that I would make it a part of another pr.

**Comment by maestromac** [comment]
@lightalloy I don't think it's possible to use multiple code climate config files and I can't figure out how to only exclude specs from being checked by the "line-length" metric. I think either we endure the lint (there seems to be 11 line-length lints for specs) and fix what we can or go back to excluding all the spec files again.

you have any thought on this @rhymes ?

**Comment by maestromac** [comment]
I will revisit this

**Pull request closed without merging**
