### PR TITLE
Social previews should also be generated for decorated objects

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Closes https://github.com/thepracticaldev/dev.to/issues/6206

### CODE REVIEW

**Comment by awebartisan** [comment]
@rhymes with this PR, already generated URLs will also be fixed?

**Comment by mstruve** [comment]
Overrode 2 review to get this out to expedite the fix for social preview urls.

**Comment by rhymes** [comment]
@awebartisan no need, it's now fixed in production, thanks again!

**Comment by awebartisan** [comment]
Yaaaas! Thank you so much for quick response :)

**Pull request merged**
