### PR TITLE
Fix rubocop issues

### PR DESCRIPTION
**Pull request by lightalloy**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

### CODE REVIEW

**Comment by Glennmen** [comment]
What rubocop issue are you referring to?

Is it about `Pundit::NotAuthorizedError`? This happens randomly and I have also seen it in my PR's.
https://github.com/thepracticaldev/dev.to/pull/1951#issuecomment-469033086

**Comment by lightalloy** [comment]
@Glennmen if you run `rubocop` in the master branch, it will show several style violations, which are not excluded in the `rubocop` configs. This pr just fixes them.

**Comment by lightalloy** [comment]
@Glennmen You're talking about failing build on Travis, which is a different thing.

**Comment by Glennmen** [comment]
Thanks for the clarification! 😄 Still learning all these Ruby tools

**Comment by lightalloy** [comment]
Thanks for the link btw, I have also encountered that error.

**Comment by Glennmen** [comment]
@lightalloy I know that this is not the right place but I only now noticed you are a DEV team member. I keep on getting surprised about how big the DEV team actually is, I keep finding new team members 😂 I also didn't know they had remote employees: https://twitter.com/GlennCarremans/status/1100677055371456512

**Pull request merged**
