### PR TITLE
Fix article submission error

### LINKED ISSUE #4502: [Resolved via rollback] articles being duplicated on edit
**Describe the bug**

Editing an existing article and publishing it creates new copy of the article and publish that.

**To Reproduce**
1. Edit an existing article
2. Save changes and publish
3. See copy of the article is published and old one still exists

**Expected behavior**
Existing article should be updated rather than creating new article.

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Browser: 
- Version: 

**Smartphone (please complete the following information):**

- Device: MotoG5S+
- OS: Android
- Browser: Chrome
- Version: latest

**Additional context**
I checked the article slug, it's also updated.

### PR DESCRIPTION
**Pull request by hoangvvo**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description

This brings back the missing fields in `this.state` caused by #4217 

## Related Tickets & Documents

Fix #4502

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

this is fine

### CODE REVIEW

**Comment by hoangvvo** [comment]
I would also like to remove unnecessary fields when `submitArticle()` is called as mentioned in https://github.com/thepracticaldev/dev.to/issues/4502#issuecomment-544214966 since it is a quite big payload in every fetch.

For now, I assume those not needed would be `previewShowing`, `helpShowing`, `previewResponse`, `helpHTML`, `imageManagementShowing`, `moreConfigShowing`, `errors`?

**Comment by benhalpern** [comment]
This is not fixing the problem for me when I test it locally

**Comment by hoangvvo** [comment]
@benhalpern  Ooops, sorry about that :rofl: 
I thought I added the thing before commiting.

The reason for this bug was that `state.id` is not supplied.

`submitArticle` in `actions.js` depends on `state.id` to determine if this is an edit or a new post. However, since `state.id` is not defined, it is always assumed as a new post, which, of course, create post duplication.

**Comment by Zhao-Andy** [comment]
@hoangvvo hah nice, I was just about to comment on that. Glad you're online and fixed it!

That `processPayload` is a nice clean up, too. Will help our logs a bit :)

**Comment by hoangvvo** [comment]
@Zhao-Andy I could not determine which of those fields are actually used because I cannot find (or read) the Ruby script responsible for post submission. 

Tell me if I left something out. I would have added some more to the exclude list like `submitting`, `editing` (assumed this was also handled by the `payload.id ? 'PUT' : 'POST'`, etc. but was afraid that would break things.

**Comment by Zhao-Andy** [comment]
@hoangvvo I believe the current `neededPayload` is good enough. To determine the list, you can look at:
https://github.com/thepracticaldev/dev.to/blob/0d2506f9ef79a32f7474001337161314d1062134/app/controllers/articles_controller.rb#L244-L276

The final array of allowed keys -- all permissions allowed -- should be this:
```ruby
[
  title, body_markdown, main_image, published, description,
  video_thumbnail_url, tag_list, canonical_url, series, collection_id, archived, 
  version, user_id, organization_id
]
```

**Comment by Zhao-Andy** [comment]
Rerunning the build since an unrelated Ruby `rspec` test failed. All JS tests passed though 👍

**Pull request merged**
