### PR TITLE
Let's keep politics out of dev.to

### PR DESCRIPTION
**Pull request by AgrimPrasad**
## What type of PR is this? (check all applicable)
- [x] Refactor
- [ ] Feature
- [ ] Bug Fix

## Description
dev.to should be a welcoming global community. Talking about Trump, or US politics in general, makes it seem quite petty and US-focused IMHO.

As a non-American who has never stepped foot in the United States, this sentence just gives me weird vibes. So, I think removing this sentence from the `offline` page makes sense here.

## Added to documentation?
  - [ ] docs.dev.to
  - [ ] readme
  - [x] no documentation needed

## What gif best describes this PR or how it makes you feel?
No Trump

### CODE REVIEW

**Comment by AgrimPrasad** [comment]
@coolshaurya I respectfully disagree there too mate. This is a website about software engineering, not about politics or science.

**Comment by maxx1128** [comment]
We need at least a little snark here, IMO. Maybe some dismissive remark about how weird JavaScript is, that's always fun (sort of) :)

**Comment by domcorvasce** [comment]
I'm not from USA but I find it hilarious.
However, I can understand your point of view and I agree.

Trump Over Again

**Comment by benhalpern** [comment]
@AgrimPrasad Hey, I see where you are coming from, regarding the US-centric rhetoric on this page, and we will consider making a change to this affect in the not-too-distant future in one way or another. But this is also not really a central part of the application itself, just like Chrome's offline screen is a pixel-art dinosaur, it’s more of an easter egg than a platform feature.

We will take this feedback into consideration, but not make any at change at this very moment. I’m going to close this for now, but we’ll keep you posted. Feel free to DM me on https://dev.to/connect to keep the convo going with me if you like.

**Comment by AgrimPrasad** [comment]
No worries @benhalpern Just wanted to see how the community views this really and happy that you guys would take it under consideration.

**Pull request closed without merging**
