### PR TITLE
[WIP] rename mastodon_url to fediverse_url and remove whitelisting

### LINKED ISSUE #2617: Please understand decentralized social networks, remove Mastodon whitelist (get Fediverse)
**Describe the bug**
As [argued here](https://twitter.com/rugkme/status/1122908656482361350), you seem to whitelist Mastodon instances.

**To Reproduce**

1. Enter any not known Mastodon instance.

**Expected behavior**
It shoudl accept any Mastodon instance automatically. (if you want, verify via a ActivityPub request that it is Mastodon or so, but accept it.)

**Screenshots**

grafik

**Additional context**
Seriously, this is a **decentralized** network, thus any implementation of a whitelist is prone to fail.
And yes, it fails.

### PR DESCRIPTION
**Pull request by morganda**
## What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Documentation Update

## Description
- Renames Mastodon URL to Fediverse URL (refactor with migration)
- Validates that Fediverse URL is a valid http/https URL
- Removes Mastodon instance whitelisting

2 things I could use feedback on before removing the WIP:
1. I'm a bit new to Rails, but I wanted to know what the preferred way to set up the migration would be. It seems like there would be some potential downtime with just doing a rename since the code also needs to line up with the new column name. I guess an alternative would be to add a `fediverse_url` column, somehow copy the data to the new column, and then remove the old column in a later release. I would definitely appreciate some feedback on the best approach here.
2. The error message prints two errors if the URL is not valid - the 2nd error indicating some kind of further validation of a fediverse URL which is expected to be addressed in #2830. I assume leaving it as is should be okay for now? If not, I can change it to just print the one error message about the invalid URL.

## Related Tickets & Documents
Fixes #2617

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Only the actual wording changes in the UI.

Showing the updated field in the profile:
Screen Shot 2019-10-22 at 12 23 01 PM

Showing the error when the link submitted is not http or https
Screen Shot 2019-10-22 at 12 22 15 PM

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

puppy saying "I helped"

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @morganda, as discussed in https://github.com/thepracticaldev/dev.to/issues/2617 - I think we need to have a way to verify these URLs are indeed part of the fediverse, removing the whitelist is contingent to that...

**Comment by morganda** [comment]
Hi @rhymes that's fine with me. I assumed by @jessleenyc 's comment https://github.com/thepracticaldev/dev.to/issues/2617#issuecomment-492322189 that verification would be handled in #2830 and wouldn't be a blocker for removing the whitelist. If that's not the case anymore I can look into that.

**Comment by rhymes** [comment]
Hi @morganda, thanks for the update, I think I assumed wrongly this was to be done in one step. 

My only concern is that by removing the whitelist and doing this in two steps we allow a window when users can put whatever they want in the URL field and if after that we'll add the verification, these users will likely have an invalid status in the DB and probably in the UI as well.

What do you think @jessleenyc ?

**Comment by morganda** [comment]
I didn't realize #2830 was actually closed so maybe there isn't a task to verify the link. I've been reading about the fediverse and trying to considering the thread model for a user supplied link. The biggest issue is that because anyone can spin up their own Mastodon (or whichever platform) instance, pretty much any link can be supplied and a positive test for an instance can easily be fooled.

2 Risks Without Validation:
1. An attacker links to a malicious site - there are some things that can be done to mitigate risk
2. Some promotion of some random thing - this is hard to mitigate because they could have a valid instance be all about them, but then they could change their instance post-validation to promote spam of some sort. This is probably not too serious of a concern though.

Some Risk Mitigation Approaches From My Perspective:
1. What was suggested in #2617 is that there might be an endpoint to consume that would confirm whether it was a valid site. This positive test doesn't do a great job of reducing risk as it can be easily fooled by an attacker.
2. Pass URLs through [Google's Safe Browsing API](https://developers.google.com/safe-browsing/v4) to check for known malicious URLs. This would help mitigate some of the risk.
3. An abuse button to report dev users doing something suspicious.
4. Keep a separate blacklist of known bad endpoints as malicious users are reported.
5. Continue maintaining a whitelist of instances. Probably one of the safer options, but limits users who have to wait for their instance to be whitelisted - this might not be high demand so maybe this is something that's doable?

I think a good approach would be a combination of 2, 3, and 4. #2 could easily be part of this PR. #3 and #4 could be worked on independently.

I'm fine closing this PR if that's what make sense - it might now that I know more, but it depends on the strategy the DEV team wants to pursue. Thoughts on the best path forward?

**Comment by mstruve** [comment]
> I'm fine closing this PR if that's what make sense

Hey @morganda! I'm in the process of doing some DEV PR history cleanup and since this has been inactive for a bit I am going to take your suggestion and go ahead and close it. Feel free to open a new on in the future if you want to continue to tackle the issue!

**Pull request closed without merging**
