### PR TITLE
#188 No Cancel edit button on comments

### PR DESCRIPTION
**Pull request by JSSaini07**
## What type of PR is this? (check all applicable)
- [ ] Refactor
- [x] Feature
- [x] Bug Fix

## Description
When editing a comment, the only way to leave the edit screen is to navigate back to dev.to from the top nav or using one of the footer links. I have added a "Cancel" button that brings you back to the article your comment was on.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
screen shot 2018-08-11 at 3 30 23 pm

## Added to documentation?
  - [ ] docs.dev.to
  - [ ] readme
  - [x] no documentation needed

### CODE REVIEW

**Comment by benhalpern** [comment]
Oh cool, this probably makes sense. WIll deal with this during week day. In the meantime, make sure to sign the CLA.

**Comment by pkfrank** [comment]
Hey @JSSaini07 , it looks like the CLA Assistant didn't work properly.  This usually happens because the email associated with the commit doesn't match the email associated with your GitHub account.

Before we approve and merge your commit, please either:

Copy/paste `I have read and agree to the CLA` as a comment in this issue.

**OR**

[Add the email](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) you used for the commit to your GitHub account.  We'll then ask the CLA Assistant to re-check.

Thank you for your contribution, and sorry for the extra step!

**Comment by benhalpern** [comment]
Looks like this fails an integration test https://travis-ci.com/thepracticaldev/dev.to/builds/81577208

`/spec/features/user_edits_a_comment_spec.rb:29`

Can you give this a look @JSSaini07?

**Comment by JSSaini07** [comment]
sure, just give me a day. will update

**Comment by maestromac** [comment]
Hey @JSSaini07 , would it be alright for me to take over this PR?

**Comment by JSSaini07** [comment]
@maestromac sure, that'll be fine 👍

**Pull request merged**
