### PR TITLE
Add SRI Support

### LINKED ISSUE #4652: Security issue - use SubResource Integrity on external Javascript
**Is your feature request related to a problem? Please describe.**

External Javascript is subject to manipulation by hostile actors.

SRI is a new W3C specification that allows web developers to ensure that resources hosted on third-party servers have not been tampered with. Use of SRI is recommended as a best-practice, whenever libraries are loaded from a third-party source.

**Describe the solution you'd like**
Use SubResource Integrity to ensure that a compromised 3rd party can't affect users of the website.

In this case, the only external code seems to be `https://unpkg.com/@webcomponents/webcomponentsjs@2.2.10/webcomponents-loader.js`

This should be loaded using

```
<script
   src="https://unpkg.com/@webcomponents/webcomponentsjs@2.2.10/webcomponents-loader.js" 
   integrity="sha384-3HK5hxQbkFqOIxMbpROlRmRtYl2LBZ52t+tqcjzsmr9NJuOWQxl8RgQSyFvq2lhy"
   crossorigin="anonymous"></script>
```

**Describe alternatives you've considered**

Self-host the external JavaScript. If unpkg.com is compromised, it will not affect the local copy of the webcomponents-loader.

**Additional context**

This appears to only impact 4 files - https://github.com/thepracticaldev/dev.to/search?q=https%3A%2F%2Funpkg.com%2F%40webcomponents%2Fwebcomponentsjs%402.2.10%2Fwebcomponents-loader.js&unscoped_q=https%3A%2F%2Funpkg.com%2F%40webcomponents%2Fwebcomponentsjs%402.2.10%2Fwebcomponents-loader.js - but my Ruby isn't good enough to know how to fix it.

### PR DESCRIPTION
**Pull request by edent**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Should add SRI support as per https://www.rubydoc.info/gems/sprockets-rails#SRI_support

I have not tested this because I can't set up the build system.

## Related Tickets & Documents
Fixes #4652 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [X] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Although it looks all right I can't seem to generate the SRI integrity hashes locally. I wonder if we shouldn't replace those directives with a normal JS `<script` and use the webcomponents SRI.

I can takeover the PR if you want @edent, let me know :)

**Comment by Glennmen** [comment]
There are also a couple of places where cdnjs links are used, for example:
https://github.com/thepracticaldev/dev.to/blob/ec6d66018f2c3d107bb12a371fac91bd73d26eb7/app/views/articles/show.html.erb#L8

**Comment by edent** [comment]
@rhymes please take it over with my blessing :-)

**Comment by rhymes** [comment]
@Glennmen yeah, we should look into all external scripts missing SRI :)

@edent thank you!

**Comment by rhymes** [comment]
@Glennmen @edent I've made a couple of changes, have a look

**Comment by rhymes** [comment]
@maestromac only when we update the version. we could also switch to a self hosted version by using a pack and npm so it gets updated by itself... but I would consider it for a separate PR

**Pull request merged**
