### PR TITLE
Update framework defaults to match those in Rails 5.1

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description

Now that the code base has been migrated to Rails 5.2 it should be safe to upgrade framework defaults to match those of the previous version.  The new defaults for Rails 5.2, see [new_framework_defaults_5_2.rb](https://github.com/thepracticaldev/dev.to/blob/master/config/initializers/new_framework_defaults_5_2.rb) can be turned on individually later on.

Regarding the flipped flags:

* [per_form_csrf_tokens](https://guides.rubyonrails.org/configuring.html#configuring-action-controller) increases security by adding CSRF tokens in each generated form
* [forgery_protection_origin_check](https://guides.rubyonrails.org/configuring.html#configuring-action-controller) checks that the request comes from the same origin
* `to_time_preserves_timezone` is an old flag for Ruby 2.4 and date time conversion
* [belongs_to_required_by_default](https://guides.rubyonrails.org/configuring.html#configuring-active-record) fails validation if a `belongs_to` association is not explicitly declared as optional and missing during validation (I checked the code, all the optional associations seem to be correctly declared)
* [form_with_generates_remote_forms](https://guides.rubyonrails.org/configuring.html#configuring-action-view) makes `form_with` (unused in the source code) generate remote form by default

I've also re-enabled two CSRF tokens that were disabled, let me know if they should be left alone (I've tested them manually and they worked)

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by benhalpern** [comment]
I think there may be issues with our current use of Rails that get in the way of how we do stuff.

Currently we can't send CSRF tokens over with typical page requests on articles because we cache a shared version for all users. If we sent the CSRF token it would cache for the first request and then leak to subsequent requests. We load CSRF async to account for this.

I'm not totally clear on the consequences of the proposed changes, but I believe it would compromise this constraint eh?

**Comment by rhymes** [comment]
@benhalpern 

I didn't know that :( I've noticed the async load for the CSRF and I was wondering the reason why, thanks for the explanation.

What the `per_form_csrf_tokens` flag does is to add one more CSRF inside forms (but keeping the global one) to lower the risk of forgery. I don't know the answer to your question yet, I'll investigate further. We can safely revert that anyhow. 

I'd keep`forgery_protection_origin_check` because it checks if the origin of the request matches.

**Comment by rhymes** [comment]
@benhalpern I don't think there's an easy way to have per form CSRF tokens and caching, the same way you had to build this mechanism to get around of caching and tokens in the first place. I reverted the changes related to that and made sure it's explained clearly in the `application.rb` for future readers

**Comment by rhymes** [comment]
Thanks @benhalpern !

**Pull request merged**
