### PR TITLE
[Emojis in Markdown]

### PR DESCRIPTION
**Pull request by juanmanuelramallo**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
- Added the ability to add emojis using colons `:joy: :tada:`
- The emoji conversion is added to the markdown parser labor
- When no emoji is found with the alias, same text is returned
- Used [gemoji gem](https://github.com/github/gemoji) to handle emojis and unicode mapping
- No assets added (no emoji images), so this will only be supported when the browser supports emojis (https://blog.getemoji.com/post/57054354336/which-browsers-support-emoji)
- Tests updated

## Related Tickets & Documents
#203 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Not applicable

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

peasy

### CODE REVIEW

**Comment by juanmanuelramallo** [comment]
# Need help
Any suggestions on how to make codeclimate pass? @benhalpern @jessleenyc

**Comment by benhalpern** [comment]
I think I like this, but it's the kind of thing I have mixed feelings about. Mostly because I haven't really made use of this functionality myself. It _feels_ like markdown maybe shouldn't care about this.

Although. It would be a nice shortcut for custom emojis for dev.to, which I like.

I think I'm in favor but I'm going to give it some thought.

Regarding codeclimate passing, you could extract some of the private methods here into other objects. For example, `user_link_if_exists` and similar methods could be extracted into separate moules like `MentionConverter` etc. or something of that nature and dumped in labor folder. 🙂

**Comment by juanmanuelramallo** [comment]
Please have a look when possible, I just refactored it to make code climate pass by creating a emoji converter class (didn't want to modify any method in the markdown parse labor not related to this feature), and let me know what you think!
cc @benhalpern 
Thanks!

**Comment by benhalpern** [comment]
After a lot of long deliberation, I'm down to make this happen.

@juanmanuelramallo would you mind updating this to make it work alongside some of the changes we've made since?

**Comment by juanmanuelramallo** [comment]
Sure thing @benhalpern! 
I'll rebase with master and fix the conflicts. 
Any other changes in here I'd need to address?

**Comment by juanmanuelramallo** [comment]
Updated pull request in here https://github.com/thepracticaldev/dev.to/pull/1653

**Pull request closed without merging**
