### PR TITLE
Addresses similar blocks of code issue

### PR DESCRIPTION
**Pull request by mudlabs**
## What type of PR is this? (check all applicable)

- [x] Refactor

## Description
Created two helper methods at top of file (below imports) to address the Similar Blocks of Code issue listed on Code Climate. The methods where also applicable at other points within this file, so I've swapped them in there too.

## Related Tickets & Documents
[Code Climate Issue](https://codeclimate.com/github/thepracticaldev/dev.to/issues#issue_5bbcfd110af1d70001000460)

### CODE REVIEW

**Comment by benhalpern** [comment]
Thanks for this! @Zhao-Andy wanna give this a review?

**Comment by mudlabs** [comment]
Is that failed **codeclimate** check something I need to address?

I know they're still _"similar blocks"_, but can't really reduce anymore without obfuscating your code.

**Comment by maestromac** [comment]
Hey @mudlabs , sorry we did not merge this PR sooner. I've went ahead and resolved the merge conflict but I can't update this PR because the branch for this PR doesn't exist. If it's fine with you, I can close this PR and open another one on with your work on it, and merge it.

**Comment by mudlabs** [comment]
@maestromac Sounds good.

**Pull request closed without merging**
