### PR TITLE
Fix linting issues in app/views/layouts

### PR DESCRIPTION
**Pull request by arnellebalane**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Fix linting issues in views located in `app/views/layouts`. The remaining `Lint/UselessAssignment` issues are just left alone since it's already going to be disabled in #1886 .

## Related Tickets & Documents

#1842 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by lightalloy** [comment]
@arnellebalane You can just remove `to_s` in the first line of `app/views/layouts/_styles.html.erb`, cause ruby already does `to_s` for us when we use string interpolation (like `"#{@story_show}"`)

**Comment by lightalloy** [comment]
As for the `Lint/UselessAssignment` it seems to not work correctly, so I would suggest disabling it (probably I'll make a pr).

**Comment by arnellebalane** [comment]
@lightalloy Thanks, I've removed the `to_s` in `_styles.html.erb`.

As for `Lint/UselessAssignment`, I will just leave it alone in this PR for now if that's going to be disabled in a separate PR, if that's fine?

**Comment by lightalloy** [comment]
@arnellebalane I think that's fine.

**Comment by arnellebalane** [comment]
@lightalloy Awesome, thank you 🎉

**Pull request merged**
