### PR TITLE
Add Condition for deployment

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)

- [x] Misc

## Description
We currently by default push all merged PR to production unless the commit message contains `[ci skip]`. This PR makes that the opposite; PR will require to have `[deploy]` in its title in order to for it deploys. The benefits are

- `[ci skip]` also skips the test suite, `[deploy]` does not.
- Explicitly make deploying a premeditated action, instead of applying that on avoiding deployment.

## Related Tickets & Documents
https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
https://docs.travis-ci.com/user/conditions-v1#integration
## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
n/a
## Added to documentation?
WIP doc is in different PR
- [x] docs.dev.to
- [ ] readme
- [ ] no documentation needed

### CODE REVIEW

**Comment by rhymes** [comment]
Would this mean that each PR after approval needs to have its title changed manually with `[deploy]` ? What I'm actually asking here is if it would add another step to the contributors or not :D

**Comment by maestromac** [comment]
@rhymes it will be on the reviewer/committer to make that action, just like how it is now with the manual `[ci skip`

**Comment by benhalpern** [comment]
I currently like that we deploy as often as we do and make the deployments pretty small. I know this wouldn't necessarily add a lot to the process but I kind of like the old default.

I definitely like the idea that everything gets CI now though.

It also seems nice that we can merge more often without the immediate risk of a new deployment. On the other hand, does each deployment become more complex if it is maybe more likely to involve multiple PRs?

This doesn't actually make things much tougher, but changing defaults does change things, culturally if nothing else.

So I'm just thinking outloud on the implications here.

**Comment by mstruve** [comment]
This PR would retain the same system we are using now but makes it more clear by using the [deploy] flag for a deploy rather than ![ci skip] flag to indicate a deploy. 

I'm game for changing the system if we want to deploy on every merge but I think thats a separate discussion. This PR at least makes it very clear what is going out and what is not and is a step in the right direction with CI running for all merges

**Pull request merged**
