### PR TITLE
Remove mentions email notification job

### PR DESCRIPTION
**Pull request by wildeng**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Removed mentions email notification job

## Related Tickets & Documents
#5305 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

dubious

### CODE REVIEW

**Comment by wildeng** [comment]
@mstruve @rhymes I don't know why but running specs on master branch on my local machine was giving me tons of errors due to sprockets. Did you experience anything similar?

**Comment by rhymes** [comment]
Hi @wildeng, can you share a sample of the errors?

**Comment by wildeng** [comment]
> Hi @wildeng, can you share a sample of the errors?

I run it for a while and then I stopped it
```bash
Finished in 3 minutes 25.6 seconds (files took 8.3 seconds to load)
2281 examples, 507 failures
```
```bash

**Comment by rhymes** [comment]
It could, but at a glance I'm not sure what's gone wrong in the setup. Could you please open a separate issue with as much details as possible on your setup?

**Comment by wildeng** [comment]
yes sure

**Pull request merged**
