### PR TITLE
add following button to my tags

### PR DESCRIPTION
**Pull request by renatamarques97**
I propose a solution for issue #5397 

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
@flexdinesh talked about a problem that he was facing, he wanted to delete some old tags and he couldn't do it because some of them changed their name, so my solution is: add a new button "following" to "my tags" for anyone to manage their own tags, following and unfollowing as needed.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
old behavior
image
new behavior
image

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

**Comment by renatamarques97** [comment]
this message is appearing to me 
"You have signed the CLA already but the status is still pending? Let us recheck it."
and when I recheck, the message still there.

**Comment by thomasbnt** [comment]
@renatamarques97 Hello, have you clicked to the badge and connect with you :octocat: account for accept the CLA ?

**Comment by renatamarques97** [comment]
@thomasbnt yes, I did.

**Comment by renatamarques97** [comment]
@Zhao-Andy thanks for the reply, I'm gonna do your suggestion.

**Comment by flexdinesh** [comment]
Unrelated to PR.

@Zhao-Andy I don't see an option to unfollow tags in dashboard [https://dev.to/dashboard/following_tags](https://dev.to/dashboard/following_tags). Is the feature user specific?

**Comment by Zhao-Andy** [comment]
@flexdinesh  Ah you're totally right. Not sure why I thought that...

**Comment by mstruve** [comment]
Hi @renatamarques97! 

Thank you so much for the PR and for taking the leap and contributing to DEV! We are super happy to have your help 😄

With that said, we are in the process of going through and cleaning up some of our PR history to help us better prioritize what we need to be focusing on. Since this PR has not been active for a while, has a few conflicts, and needs some changes made I am going to go ahead and close it for now. 

If you would still like to get this merged please feel free to resolve the conflicts, make the recommended changes, and then open the PR back up. We would be more than happy to help you push this through if you would like! 

Thanks again for contributing! Ping us anytime if you have questions!

**Pull request closed without merging**
