### PR TITLE
two minor typo changes (according to Grammarly)

### PR DESCRIPTION
**Pull request by sonnynomnom**
changed "biproduct" -> byproduct"
changed "submit" -> "submitted"

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description

used Grammarly to check for typos

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by rhymes** [comment]
Hi @sonnynomnom, thanks a lot for this, if you sign the CLA above this will be ready to be merged

**Comment by sonnynomnom** [comment]
yay

**Comment by sonnynomnom** [comment]
yay! just signed. great work at dev.to btw. hope u are all safe and hanging on.

**Comment by Ridhwana** [comment]
Juts merged it 🎉 Congratulations on your commit 😊 and thank you, hope you're doing well and staying safe too!

**Pull request merged**
