### PR TITLE
[WIP]Adding pentester column for users

### PR DESCRIPTION
**Pull request by FeruzOripov**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Added `pentester` column to `users` table. Default is false.
## Related Tickets & Documents
#5068 
## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
image

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by FeruzOripov** [comment]
I have no idea about where to put `I am a pentester` checkbox, so I just inserted it into profile settings.

**Comment by nickytonline** [comment]
My two cents here and maybe I don’t have the full context, but instead of adding a boolean field to the user table, consider making pentester a role instead.

**Comment by mstruve** [comment]
@nickytonline that is definitely another possibility! 

Having it as a role prevents us from adding additional fields to the already bloated User table which I love! The downside is that we have to load an additional db resource whenever we want to check it. My initial thought with regards to Honeybadger was going to be to set it in the context and then use that in the notify block like below. 
```ruby
# start of any request
Honeybadger.context(:pentester => current_user.pentester)

# when an error is raised
config.before_notify do |notice|
  notice.halt! if notice.context[:pentester]
end
```
If we went with a role every request gets one more db query. We could however actually check it in the `before_notify` block so an extra db hit is made only when an error occurs. The problem I see with this is that in the future we will likely want to also send this flag into jobs created by users to ensure job errors get the same treatment which means sprinkling some more role hits around the codebase.

**Comment by mstruve** [comment]
@jacobherrington that is a very interesting thought. Having been at a company where we did extensive pentesting constantly we never had a problem with someone trying to skirt the system using the pentester flag. The flag was used to ignore errors for reporting BUT we also used it when logging so actually having the flag(which was a much smaller subset of users) would likely make it easier to find someone malicious if say you were looking at logs or at the data in general. I guess I am more concerned about alert fatigue causing us to miss real errors and bugs than someone trying to hide behind the pentester flag. But that's just me, definitely interested to hear other takes.  

My main concern is that I want to make sure it is as easy as possible to turn on the flag so that people actually do it and don't lazily skip that step. I feel like having to wait to be given it might be something people aren't willing to do and will just start hacking away. 🤷‍♀ At Kenna we had a specific signup URL for pentest users that has `?pentest=true` in the params and we used that to flag the user and then that was it.

**Comment by mstruve** [comment]
Hey everyone! I slept on this and here is what I think. How about we add a pentester role to start, I will lookup the role only when a HB is raised and then down the road if we need it more places we can if we want switch it to being on the user table itself. I landed on this bc it really is the path of least resistance and we can make it more performant if/when we need to. Thoughts?

That leaves just the question about how to give the role out then. cc @jacobherrington @nickytonline

**Comment by nickytonline** [comment]
It really is a role so I think this approach makes sense. I was concerned about bloating the user table as well like you mentioned @mstruve. Also a good move not doing a [YAGNI](https://www.martinfowler.com/bliki/Yagni.html). 😉

In terms of dolling out the role, we could still use the proposed checkbox in the profile settings. If there is genuine concern about malicious users and we want to vet the user, their role could initially be pending until approved.

**Comment by jacobherrington** [comment]
@mstruve Great thoughts, I think we are on the same page.

@nickytonline I think that's a great compromise. I advise that we implement it that way and follow up with some best practices internally regarding users who self-identify as pentesters.

@FeruzOripov What do you think about this?

**Comment by benhalpern** [comment]
I agree with the role approach and only adding it as part of a HB exception.

On the topic of role n+1 in general, probably outside the scope....

Alongside roles, I think it would make sense to _additionally_ have a cached column on the user which relates to all of the roles we have in place, so, for example `user.cached_roles`. We make use of the functionality the `acts-as-taggable` gem instructs here...

https://github.com/mbleigh/acts-as-taggable-on/wiki/Caching

And I think it makes sense to replicate that functionality in cases like this. The absolute source of truth lies in the `roles` table, but is reflected in a cached user model table. This will allow us to lean into roles more without the concern that @mstruve brings up, covers way more cases than just this.

***

In therms of the user experience, I think this should go in the `accounts` tab. It's not core functionality and I don't think it makes a lot of sense to be right in the path of most users where it only applies to a tiny tiny tiny tiny percent of users. I'd even be in favor of it being even more hidden than that, and linked to only in `/security`, where the instructions for pentesting are provided in the first place. Definitely not in the core profile path. Just doesn't apply broadly enough.

**Comment by rhymes** [comment]
+1 on roles and adding a `settings/security`

**Comment by mstruve** [comment]
Hey @FeruzOripov! 
 
Thank you so much for this incredible feature PR! Currently, we are in the process of going through and cleaning up some of our PR history to help us better prioritize what we need to be focusing on. Since this PR has not been active for a while and has some conflicts I am going to close it for now. 

If you would still like to tackle this feature and get this merged please feel free to resolve the conflicts and then open the PR back up. We would be more than happy to help push this through if you would like! Also when you open the PR up make sure it is ready to be reviewed and does not have the WIP tag. We usually don't look at WIP PRs bc it means they are not ready for review. 

If you would like team help on it we suggest opening a Draft PR and then leaving a comment that you need help and we will do our best to find some time to assist you. 

Thanks so much for being a contributor! Ping us anytime if you have questions!

**Pull request closed without merging**
