### PR TITLE
[WIP] Play around with Travis config

### PR DESCRIPTION
**Pull request by benhalpern**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Mess around with travis config

### CODE REVIEW

**Comment by maestromac** [comment]
closing and re-opening to trigger the build.

**Comment by benhalpern** [comment]
@maestromac if this didn't trigger a build that might be because this config caused a problem where a build was not triggered?

**Comment by maestromac** [comment]
Yep, syntax error
```
Warnings for .travis.yml:
[x] syntax error: (<unknown>): did not find expected '-' indicator while parsing a block collection at line 14 column 3
```

**Comment by maestromac** [comment]
Will continue this attempt in the future. related https://github.com/thepracticaldev/dev.to/issues/1078

**Pull request closed without merging**
