### PR TITLE
Rails 5.2 features: Enable active_record.sqlite3.represent_boolean_as_integer

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

After https://github.com/thepracticaldev/dev.to/pull/4216 I'm submitting this PR to get closer to Rails 5.2 default. We don't use sqlite3 so this doesn't impact the app.

### CODE REVIEW

**Comment by rhymes** [comment]
@mstruve the point of all of these PRs is to slowly get to load Rails 5.2 defaults here:

https://github.com/thepracticaldev/dev.to/blob/c889e6b6c0f230cb81d18192e7aa8caefcc8af6c/config/application.rb#L22-L23

Since this is innocuous and we are clear everywhere that we use and support only PostgreSQL, I don't think it'd generate confusion, but I can tweak the title of the PR if you'd like to

**Comment by mstruve** [comment]
I get that we want to move to the new Rails defaults but why include a default we don't actually need?

**Comment by rhymes** [comment]
@mstruve I'm okay either way, I'm going through all flags, researching what they are about and flipping them if I think they don't cause us issues

**Comment by mstruve** [comment]
I think our convention should be to flip them on if we need them and leave the ones we don't need commented out to avoid any confusion.

**Comment by rhymes** [comment]
Agreed @mstruve, closing this because it's not strictly needed

**Pull request closed without merging**
